<div style="text-align: right"> Марина Архипцева </div>

### Загрузка данных из разных источников

1. Продвинутые параметры read_csv
2. Чтение из архива, xlsx, json, xml
3. Сбор данных по API
4. Скрапинг
5. Чтение данных из БД

In [1]:
import pandas as pd

**Источник:** [ВИЧ-инфекция в России с 2014 года](https://tochno.st/datasets/hiv)

In [15]:
df = pd.read_csv('data_hiv_110_v20240626.csv', sep=';') # on_bad_lines='warn')

In [16]:
df.head(5)

,indicator_section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,source,reason_na
0,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Российская Федерация,страна,0,0,2022,1168076,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,NaN
1,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Свердловская область,регион,65000000,65000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...
2,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Москва,регион,45000000,45000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...
3,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Санкт-Петербург,регион,40000000,40000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...
4,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Самарская область,регион,36000000,36000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...

In [5]:
df.shape

(26244, 13)

In [6]:
df['indicator_section'].unique()

array(['Масштаб', 'Заболеваемость/выявляемость ВИЧ',
       'Профилактика, лечение и диспансерный учет', 'Смертность'],
      dtype=object)

In [7]:
df['year'].unique()

array([2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014])

In [8]:
df['indicator_unit'].unique()

array(['человек', 'на 100 тыс. населения', 'процент', 'годовых курсов',
       'сообщений'], dtype=object)

***

**Источник:** [Заболеваемость онкологией и смертность от нее с 1997 года](https://tochno.st/datasets/cancer_incidence)

Если в ZIP-архиве содержится только один CSV-файл, pandas автоматически его распознает. Если же в архиве несколько файлов, этот метод не подойдёт

In [9]:
df2 = pd.read_csv('data_zis_109_v20241014_csv.zip', compression='zip')

ValueError: Multiple files found in ZIP file. Only one file per ZIP: ['data_zis_109_v20241014.csv', 'description_zis_109_v20241014.pdf']

In [12]:
from zipfile import ZipFile

csv_filename = "data_zis_109_v20241014.csv"

# Открытие ZIP-архива и чтение конкретного CSV-файла
with ZipFile('data_zis_109_v20241014_csv.zip') as z:
    with z.open(csv_filename) as f:
        df = pd.read_csv(f, sep=';')

In [17]:
df.head(3)

,indicator_section,indicator_name,indicator_unit,indicator_code,object_name,object_level,object_oktmo,object_okato,year,indicator_value,comment,source,reason_na
0,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Российская Федерация,страна,0,0,2022,1168076,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,NaN
1,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Свердловская область,регион,65000000,65000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...
2,Масштаб,"Численность людей, живущих с ВИЧ (ЛЖВ)",человек,Y904000001,Москва,регион,45000000,45000000,2022,NaN,"Количество людей, живущих с установленным диаг...",Роспотребнадзор,отсутствовали данные в источнике или отдельно ...

In [18]:
df.shape

(26244, 13)

In [19]:
df['year'].unique()

array([2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014])

В CSV-файлах могут использоваться разные символы в качестве разделителей:

1. **Запятая (,)**
   
2. **Точка с запятой (;)** – удобно если в данных запятая служит десятичным разделителем.

3. **Табуляция (`\t`)** – используется в формате TSV (Tab-Separated Values). Применяется, если данные содержат запятые и точки с запятой.

4. **Пробел ( )** – редко используется, но может встретиться, если данные не содержат пробелов внутри значений.

5. **Вертикальная черта (|)** – также известная как "pipe". Удобен для данных, где запятые и точки с запятой часто встречаются внутри значений.

6. **Двоеточие (:)** – встречается реже, но иногда применяется для упрощенных форматов данных.

Выбор разделителя зависит от контекста данных и специфики среды, где файл будет использоваться.

In [20]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: "int | Sequence[int] | None | Literal['infer']" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: "Literal['high', 'legacy'] | None" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.
        - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
        - ``'skip'``, skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

        .. versionadded:: 1.4.0


### xlsx файлы

In [6]:
import re
from zipfile import ZipFile
import pandas as pd

# Список для хранения DataFrame из каждого файла
dataframes = []

# Открытие ZIP-архива и обработка файлов
with ZipFile('data_zis_109_v20241014_xlsx.zip') as z:
    # Перебор файлов в архиве
    for file_info in z.infolist():
        print(file_info)
        # Отбираем нужные файлы
        if re.search(r'20(22|23)\.xlsx$', file_info.filename):
            with z.open(file_info.filename) as f:
                # Чтение файла в DataFrame и добавление в список
                df = pd.read_excel(f)
                dataframes.append(df)

# Объединение всех DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

combined_df.head()

<ZipInfo filename='data_zis_109_v20241014_2003.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34186 compress_size=30095>
<ZipInfo filename='data_zis_109_v20241014_2004.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34250 compress_size=30181>
<ZipInfo filename='data_zis_109_v20241014_2005.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34288 compress_size=30119>
<ZipInfo filename='data_zis_109_v20241014_2006.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34278 compress_size=30256>
<ZipInfo filename='data_zis_109_v20241014_2007.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=4262039 compress_size=3436809>
<ZipInfo filename='data_zis_109_v20241014_2008.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=4912727 compress_size=4133564>
<ZipInfo filename='data_zis_109_v20241014_2009.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5030645 compress_size=4247072>
<ZipInfo filename='data_zis_109_v20241014_2010.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5032291 compress_size=4246334>
<ZipInfo filename='data_zis_109_v20241014_2011.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5271744 compress_size=4433617>
<ZipInfo filename='data_zis_109_v20241014_2012.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5270669 compress_size=4422378>
<ZipInfo filename='data_zis_109_v20241014_2013.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5271551 compress_size=4422628>
<ZipInfo filename='data_zis_109_v20241014_2014.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5329160 compress_size=4451246>
<ZipInfo filename='data_zis_109_v20241014_2015.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5380528 compress_size=4483330>
<ZipInfo filename='data_zis_109_v20241014_2016.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5442408 compress_size=4522647>
<ZipInfo filename='data_zis_109_v20241014_2017.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5444244 compress_size=4531479>
<ZipInfo filename='data_zis_109_v20241014_2018.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5444759 compress_size=4549377>
<ZipInfo filename='data_zis_109_v20241014_2019.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5444575 compress_size=4535222>
<ZipInfo filename='data_zis_109_v20241014_2020.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5441018 compress_size=4549562>
<ZipInfo filename='data_zis_109_v20241014_2021.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=5441019 compress_size=4522324>
<ZipInfo filename='data_zis_109_v20241014_2022.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=6061771 compress_size=5039632>
<ZipInfo filename='data_zis_109_v20241014_2023.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=6083649 compress_size=5056321>
<ZipInfo filename='data_zis_109_v20241014_country.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=8325882 compress_size=7074651>
<ZipInfo filename='description_zis_109_v20241014.pdf' compress_type=deflate filemode='-rw-rw-rw-' file_size=368528 compress_size=340841>
<ZipInfo filename='data_zis_109_v20241014_1997.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34183 compress_size=30115>
<ZipInfo filename='data_zis_109_v20241014_1998.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34337 compress_size=30322>
<ZipInfo filename='data_zis_109_v20241014_1999.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34353 compress_size=30377>
<ZipInfo filename='data_zis_109_v20241014_2000.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34178 compress_size=30092>
<ZipInfo filename='data_zis_109_v20241014_2001.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34258 compress_size=30341>
<ZipInfo filename='data_zis_109_v20241014_2002.xlsx' compress_type=deflate filemode='-rw-rw-rw-' file_size=34203 compress_size=30030>

,indicator_section,indicator_name,indicator_unit,indicator_code,nosology_name,nosology_code,age,sex,object_name,object_level,object_oktmo,object_okato,year,indicator_value
0,Заболеваемость по регионам и по локализации,Абсолютное число новых случаев заболевания,человек,Q310000001,Все злокачественные новообразования,C00-97,Всего,Оба пола,Российская Федерация,страна,0,0,2022,624835.0
1,Заболеваемость по регионам и по локализации,Абсолютное число новых случаев заболевания,человек,Q310000001,Все злокачественные новообразования,C00-97,Всего,Оба пола,Центральный федеральный округ,федеральный округ,0,0,2022,163636.0
2,Заболеваемость по регионам и по локализации,Абсолютное число новых случаев заболевания,человек,Q310000001,Все злокачественные новообразования,C00-97,Всего,Оба пола,Белгородская область,регион,14000000,14000000,2022,7120.0
3,Заболеваемость по регионам и по локализации,Абсолютное число новых случаев заболевания,человек,Q310000001,Все злокачественные новообразования,C00-97,Всего,Оба пола,Брянская область,регион,15000000,15000000,2022,6569.0
4,Заболеваемость по регионам и по локализации,Абсолютное число новых случаев заболевания,человек,Q310000001,Все злокачественные новообразования,C00-97,Всего,Оба пола,Владимирская область,регион,17000000,17000000,2022,6665.0

In [22]:
combined_df.shape

(205672, 14)

**Источник:**

[Данные Росстата по численности населения на начало года](https://rosstat.gov.ru/folder/12781)

In [1]:
import pandas as pd
df = pd.read_excel("Chisl_RF_01-01-2022-01-01-2024.xls", sheet_name="2024", skiprows=3, header=[0,1])

df.head()

                      Содержание      Все население                          \
              Unnamed: 0_level_1 мужчины\nи женщины     мужчины     женщины
0                            NaN                NaN         NaN         NaN
1           Российская Федерация        146150789.0  67917353.0  78233436.0
2  Центральный федеральный округ         40198659.0  18618593.0  21580066.0
3           Белгородская область          1500659.0    694674.0    805985.0
4               Брянская область          1142404.0    522823.0    619581.0

  Городское население                         Сельское население            \
   мужчины\nи женщины     мужчины     женщины мужчины\nи женщины   мужчины
0                 NaN         NaN         NaN                NaN       NaN
1         109526940.0  50213973.0  59312967.0           36623849  17703380
2          33031478.0  15177644.0  17853834.0            7167181   3440949
3            980243.0    443383.0    536860.0             520416    251291
4            796237.0    356646.0    439591.0             346167    166177


    женщины
0       NaN
1  18920469
2   3726232
3    269125
4    179990

In [2]:
df.columns

MultiIndex([(         'Содержание', 'Unnamed: 0_level_1'),
            (      'Все население', 'мужчины\nи женщины'),
            (      'Все население',            'мужчины'),
            (      'Все население',            'женщины'),
            ('Городское население', 'мужчины\nи женщины'),
            ('Городское население',            'мужчины'),
            ('Городское население',            'женщины'),
            ( 'Сельское население', 'мужчины\nи женщины'),
            ( 'Сельское население',            'мужчины'),
            ( 'Сельское население',            'женщины')],
           )

In [3]:
# удалим пустые строки
df.dropna(how='all', inplace=True)

In [4]:
df.head()

                      Содержание      Все население                          \
              Unnamed: 0_level_1 мужчины\nи женщины     мужчины     женщины
1           Российская Федерация        146150789.0  67917353.0  78233436.0
2  Центральный федеральный округ         40198659.0  18618593.0  21580066.0
3           Белгородская область          1500659.0    694674.0    805985.0
4               Брянская область          1142404.0    522823.0    619581.0
5           Владимирская область          1309942.0    594456.0    715486.0

  Городское население                         Сельское население            \
   мужчины\nи женщины     мужчины     женщины мужчины\nи женщины   мужчины
1         109526940.0  50213973.0  59312967.0           36623849  17703380
2          33031478.0  15177644.0  17853834.0            7167181   3440949
3            980243.0    443383.0    536860.0             520416    251291
4            796237.0    356646.0    439591.0             346167    166177
5           1016415.0    454917.0    561498.0             293527    139539


    женщины
1  18920469
2   3726232
3    269125
4    179990
5    153988

In [5]:
# что ещё можно сделать
df.reset_index(drop=True, inplace=True)
df.head(3)

                      Содержание      Все население                          \
              Unnamed: 0_level_1 мужчины\nи женщины     мужчины     женщины
0           Российская Федерация        146150789.0  67917353.0  78233436.0
1  Центральный федеральный округ         40198659.0  18618593.0  21580066.0
2           Белгородская область          1500659.0    694674.0    805985.0

  Городское население                         Сельское население            \
   мужчины\nи женщины     мужчины     женщины мужчины\nи женщины   мужчины
0         109526940.0  50213973.0  59312967.0           36623849  17703380
1          33031478.0  15177644.0  17853834.0            7167181   3440949
2            980243.0    443383.0    536860.0             520416    251291


    женщины
0  18920469
1   3726232
2    269125

***

**JSON** (JavaScript Object Notation) — это лёгкий текстовый формат обмена данными, который используется для передачи данных между сервером и клиентом. JSON позволяет структурировать данные в виде ключ-значение, что делает его удобным для хранения и обмена информацией в веб-приложениях и API.

### Структура JSON
JSON состоит из:
1. **Объектов** — это структуры данных, заключенные в фигурные скобки `{}`, где данные представлены в виде пар "ключ-значение". Например:

   ```json
   {
     "name": "Иван",
     "age": 30,
     "city": "Москва"
   }
   ```

2. **Массивов** — это списки значений, заключенные в квадратные скобки `[]`. Массивы могут содержать объекты, строки, числа и другие массивы. Например:

   ```json
   {
     "employees": [
       {"name": "Иван", "age": 30},
       {"name": "Анна", "age": 25},
       {"name": "Петр", "age": 35}
     ]
   }
   ```

3. **Простых значений** — это строки, числа, логические значения (`true` и `false`) и `null`.

### Применение JSON
JSON широко используется для:
- **Веб-API**: Передача данных между сервером и клиентом в формате JSON позволяет легко обмениваться структурированной информацией.
- **Хранение данных**: JSON-файлы часто используются для хранения настроек, конфигураций и других структурированных данных.

In [7]:
combined_df.to_csv('cancer_2022_2023.csv')

In [8]:
combined_df.to_json('cancer_2022_2023.json', orient='index')

**Источник:** [Соответствие заболеваний и диагнозов МКБ10](https://nsi.rosminzdrav.ru/dictionaries/1.2.643.5.1.13.13.99.2.820/passport/1.73)

In [9]:
df_mkb10 = pd.read_json('мкб10.json', orient='records')
df_mkb10.head()

                                             records
0  {'id': 1, 'disease_name': 'Спинальная мышечная...
1  {'id': 2, 'disease_name': 'Спинальная мышечная...
2  {'id': 3, 'disease_name': 'Спинальная мышечная...
3  {'id': 4, 'disease_name': 'Спинальная мышечная...
4  {'id': 5, 'disease_name': 'Спинальная мышечная...

In [10]:
import json

# Открытие и загрузка JSON файла
with open('мкб10.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
data

{'records': [{'id': 1,
   'disease_name': 'Спинальная мышечная атрофия',
   'disease_id': '1',
   'mkb_code': 'G12.0',
   'mkb_name': 'Детская спинальная мышечная атрофия, I тип [Верднига-Гоффмана]',
   'mkb_id': '2965',
   'inc_dt': '03.02.2021'},
  {'id': 2,
   'disease_name': 'Спинальная мышечная атрофия',
   'disease_id': '1',
   'mkb_code': 'G12.1',
   'mkb_name': 'Другие наследственные спинальные мышечные атрофии',
   'mkb_id': '2966',
   'inc_dt': '03.02.2021'},
  {'id': 3,
   'disease_name': 'Спинальная мышечная атрофия',
   'disease_id': '1',
   'mkb_code': 'G12.2',
   'mkb_name': 'Болезнь двигательного неврона',
   'mkb_id': '2967',
   'inc_dt': '03.02.2021'},
  {'id': 4,
   'disease_name': 'Спинальная мышечная атрофия',
   'disease_id': '1',
   'mkb_code': 'G12.8',
   'mkb_name': 'Другие спинальные мышечные атрофии и родственные синдромы',
   'mkb_id': '2968',
   'inc_dt': '03.02.2021'},
  {'id': 5,
   'disease_name': 'Спинальная мышечная атрофия',
   'disease_id': '1',
   'mkb_code': 'G12.9',
   'mkb_name': 'Спинальная мышечная атрофия неуточненная',
   'mkb_id': '2969',
   'inc_dt': '03.02.2021'},
  {'id': 6,
   'disease_name': 'Болезнь Помпе',
   'disease_id': '2',
   'mkb_code': 'E74.0',
   'mkb_name': 'Болезни накопления гликогена',
   'mkb_id': '2327',
   'inc_dt': '16.02.2021'},
  {'id': 7,
   'disease_name': 'Семейная средиземноморская лихорадка',
   'disease_id': '3',
   'mkb_code': 'E85.0',
   'mkb_name': 'Наследственный семейный амилоидоз без невропатии',
   'mkb_id': '2393',
   'inc_dt': '03.03.2021'},
  {'id': 10,
   'disease_name': 'Периодический синдром, ассоциированный с рецептором фактора некроза опухоли',
   'disease_id': '5',
   'mkb_code': 'E85.0',
   'mkb_name': 'Наследственный семейный амилоидоз без невропатии',
   'mkb_id': '2393',
   'inc_dt': '03.03.2021'},
  {'id': 12,
   'disease_name': 'Мукополисахаридоз IV A',
   'disease_id': '7',
   'mkb_code': 'E76.2',
   'mkb_name': 'Другие мукополисахаридозы',
   'mkb_id': '2345',
   'inc_dt': '01.04.2021'},
  {'id': 19,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C48.0',
   'mkb_name': 'Злокачественное новообразование забрюшинного пространства',
   'mkb_id': '1189',
   'inc_dt': '22.04.2021'},
  {'id': 20,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C74.1',
   'mkb_name': 'Злокачественное новообразование мозгового слоя надпочечника',
   'mkb_id': '1324',
   'inc_dt': '22.04.2021'},
  {'id': 21,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C74.9',
   'mkb_name': 'Злокачественное новообразование надпочечника неуточненной части',
   'mkb_id': '1325',
   'inc_dt': '22.04.2021'},
  {'id': 23,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C76.1',
   'mkb_name': 'Злокачественное новообразование грудной клетки',
   'mkb_id': '1338',
   'inc_dt': '22.04.2021'},
  {'id': 24,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C76.2',
   'mkb_name': 'Злокачественное новообразование живота',
   'mkb_id': '1339',
   'inc_dt': '22.04.2021'},
  {'id': 25,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C76.7',
   'mkb_name': 'Злокачественное новообразование других неточно обозначенных локализаций',
   'mkb_id': '1343',
   'inc_dt': '22.04.2021'},
  {'id': 27,
   'disease_name': 'Муковисцидоз',
   'disease_id': '10',
   'mkb_code': 'E84.0',
   'mkb_name': 'Кистозный фиброз с легочными проявлениями',
   'mkb_id': '2388',
   'inc_dt': '13.05.2021'},
  {'id': 30,
   'disease_name': 'Муковисцидоз',
   'disease_id': '10',
   'mkb_code': 'E84.9',
   'mkb_name': 'Кистозный фиброз неуточненный',
   'mkb_id': '2391',
   'inc_dt': '13.05.2021'},
  {'id': 31,
   'disease_name': 'Синдром короткой кишки',
   'disease_id': '11',
   'mkb_code': 'K91.1',
   'mkb_name': 'Синдромы оперированного желудка',
   'mkb_id': '4995',
   'inc_dt': '10.06.2021'},
  {'id': 32,
   'disease_name': 'Туберозный склероз',
   'disease_id': '12',
   'mkb_code': 'Q85.1',
   'mkb_name': 'Туберозный склероз',
   'mkb_id': '8083',
   'inc_dt': '11.06.2021'},
  {'id': 33,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.0',
   'mkb_name': 'Инсулинзависимый сахарный диабет с комой',
   'mkb_id': '2061',
   'inc_dt': '11.06.2021'},
  {'id': 43,
   'disease_name': 'Синдром короткой кишки',
   'disease_id': '11',
   'mkb_code': 'K90.8',
   'mkb_name': 'Другие нарушения всасывания в кишечнике',
   'mkb_id': '4991',
   'inc_dt': '10.06.2021'},
  {'id': 46,
   'disease_name': 'Нейрональный цероидный липофусциноз 2 типа',
   'disease_id': '14',
   'mkb_code': 'E75.4',
   'mkb_name': 'Липофусциноз нейронов',
   'mkb_id': '2339',
   'inc_dt': '24.06.2021'},
  {'id': 47,
   'disease_name': 'Первичная гипероксалурия I типа',
   'disease_id': '15',
   'mkb_code': 'N20.0',
   'mkb_name': 'Камни почки',
   'mkb_id': '6208',
   'inc_dt': '24.06.2021'},
  {'id': 48,
   'disease_name': 'Первичная гипероксалурия I типа',
   'disease_id': '15',
   'mkb_code': 'N20.1',
   'mkb_name': 'Камни мочеточника',
   'mkb_id': '6209',
   'inc_dt': '24.06.2021'},
  {'id': 49,
   'disease_name': 'Первичная гипероксалурия I типа',
   'disease_id': '15',
   'mkb_code': 'N20.2',
   'mkb_name': 'Камни почек с камнями мочеточника',
   'mkb_id': '6210',
   'inc_dt': '24.06.2021'},
  {'id': 50,
   'disease_name': 'Первичная гипероксалурия I типа',
   'disease_id': '15',
   'mkb_code': 'N20.9',
   'mkb_name': 'Мочевые камни неуточненные',
   'mkb_id': '6211',
   'inc_dt': '24.06.2021'},
  {'id': 51,
   'disease_name': 'Буллёзный эпидермолиз',
   'disease_id': '20',
   'mkb_code': 'Q81.1',
   'mkb_name': 'Эпидермолиз буллезный летальный',
   'mkb_id': '8051',
   'inc_dt': '22.07.2021'},
  {'id': 52,
   'disease_name': 'Буллёзный эпидермолиз',
   'disease_id': '20',
   'mkb_code': 'Q81.2',
   'mkb_name': 'Эпидермолиз буллезный дистрофический',
   'mkb_id': '8052',
   'inc_dt': '22.07.2021'},
  {'id': 53,
   'disease_name': 'Буллёзный эпидермолиз',
   'disease_id': '20',
   'mkb_code': 'Q81.8',
   'mkb_name': 'Другой буллезный эпидермолиз',
   'mkb_id': '8053',
   'inc_dt': '22.07.2021'},
  {'id': 54,
   'disease_name': 'Буллёзный эпидермолиз',
   'disease_id': '20',
   'mkb_code': 'Q81.9',
   'mkb_name': 'Буллезный эпидермолиз неуточненный',
   'mkb_id': '8054',
   'inc_dt': '22.07.2021'},
  {'id': 55,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C91.0',
   'mkb_name': 'Острый лимфобластный лейкоз [ОЛЛ]',
   'mkb_id': '1424',
   'inc_dt': '01.07.2021'},
  {'id': 56,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.0',
   'mkb_name': 'Нодулярная лимфома Ходжкина [Hodgkin] с лимфоидным преобладанием',
   'mkb_id': '1377',
   'inc_dt': '01.07.2021'},
  {'id': 57,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.1',
   'mkb_name': '(Классическая) лимфома Ходжкина [Hodgkin] с нодулярным склерозом',
   'mkb_id': '1378',
   'inc_dt': '01.07.2021'},
  {'id': 58,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.2',
   'mkb_name': 'Смешанно-клеточная (классическая) лимфома Ходжкина [Hodgkin]',
   'mkb_id': '1379',
   'inc_dt': '01.07.2021'},
  {'id': 59,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.3',
   'mkb_name': '(Классическая) лимфома Ходжкина [Hodgkin] с лимфоидным истощением',
   'mkb_id': '1380',
   'inc_dt': '01.07.2021'},
  {'id': 60,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.4',
   'mkb_name': 'Классическая лимфома Ходжкина богатая лимфоцитами',
   'mkb_id': '14800',
   'inc_dt': '01.07.2021'},
  {'id': 61,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.7',
   'mkb_name': 'Другая (классическая) лимфома Ходжкина [Hodgkin]',
   'mkb_id': '1381',
   'inc_dt': '01.07.2021'},
  {'id': 62,
   'disease_name': 'Острый лимфобластный лейкоз',
   'disease_id': '16',
   'mkb_code': 'C81.9',
   'mkb_name': 'Лимфома Ходжкина [Hodgkin] неуточненная',
   'mkb_id': '1382',
   'inc_dt': '01.07.2021'},
  {'id': 63,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'D46.6',
   'mkb_name': 'Миелодиспластический синдром с изолированной del (5q) хромосомной аномалией',
   'mkb_id': '14830',
   'inc_dt': '01.07.2021'},
  {'id': 64,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'D46.7',
   'mkb_name': 'Другие миелодиспластические синдромы',
   'mkb_id': '1787',
   'inc_dt': '01.07.2021'},
  {'id': 65,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'D46.9',
   'mkb_name': 'Миелодиспластический синдром неуточненный',
   'mkb_id': '1788',
   'inc_dt': '01.07.2021'},
  {'id': 66,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'C92.0',
   'mkb_name': 'Острый миелобластный лейкоз [ОМЛ]',
   'mkb_id': '1433',
   'inc_dt': '01.07.2021'},
  {'id': 67,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'C92.1',
   'mkb_name': 'Хронический миелоидный лейкоз [ХМЛ], BCR/ABL-положительный',
   'mkb_id': '1434',
   'inc_dt': '01.07.2021'},
  {'id': 68,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'C92.2',
   'mkb_name': 'Атипичный хронический миелоидный лейкоз, BCR/ABL-отрицательный',
   'mkb_id': '1435',
   'inc_dt': '01.07.2021'},
  {'id': 69,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'C92.7',
   'mkb_name': 'Другой миелоидный лейкоз',
   'mkb_id': '1439',
   'inc_dt': '01.07.2021'},
  {'id': 70,
   'disease_name': 'Острый миелобластный лейкоз',
   'disease_id': '17',
   'mkb_code': 'C92.9',
   'mkb_name': 'Миелоидный лейкоз неуточненный',
   'mkb_id': '1440',
   'inc_dt': '01.07.2021'},
  {'id': 71,
   'disease_name': 'Т-лимфобластная лимфома',
   'disease_id': '18',
   'mkb_code': 'C83.5',
   'mkb_name': 'Лимфобластная (диффузная) лимфома',
   'mkb_id': '1395',
   'inc_dt': '01.07.2021'},
  {'id': 72,
   'disease_name': 'Первичный иммунодефицит',
   'disease_id': '19',
   'mkb_code': 'D82.0',
   'mkb_name': 'Синдром Вискотта-Олдрича',
   'mkb_id': '1978',
   'inc_dt': '01.07.2021'},
  {'id': 73,
   'disease_name': 'Дефицит лизосомной кислой липазы',
   'disease_id': '21',
   'mkb_code': 'D56.1',
   'mkb_name': 'Бета-талассемия',
   'mkb_id': '1846',
   'inc_dt': '22.07.2021'},
  {'id': 74,
   'disease_name': 'Дефицит лизосомной кислой липазы',
   'disease_id': '21',
   'mkb_code': 'D61.3',
   'mkb_name': 'Идиопатическая апластическая анемия',
   'mkb_id': '1884',
   'inc_dt': '22.07.2021'},
  {'id': 75,
   'disease_name': 'Наследственная дистрофия сетчатки, вызванная биаллельными мутациями в гене RPE65',
   'disease_id': '22',
   'mkb_code': 'H35.5',
   'mkb_name': 'Наследственные ретинальные дистрофии',
   'mkb_id': '3504',
   'inc_dt': '29.07.2021'},
  {'id': 8,
   'disease_name': 'Криопирин-ассоциированный периодический синдром',
   'disease_id': '4',
   'mkb_code': 'M08.2',
   'mkb_name': 'Юношеский артрит с системным началом',
   'mkb_id': '5472',
   'inc_dt': '03.03.2021'},
  {'id': 11,
   'disease_name': 'Гипофосфатазия',
   'disease_id': '6',
   'mkb_code': 'E83.3',
   'mkb_name': 'Нарушения обмена фосфора и фосфатаз',
   'mkb_id': '2382',
   'inc_dt': '01.04.2021'},
  {'id': 13,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.3',
   'mkb_name': 'Злокачественное новообразование периферических нервов грудной клетки',
   'mkb_id': '1182',
   'inc_dt': '22.04.2021'},
  {'id': 14,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.4',
   'mkb_name': 'Злокачественное новообразование периферических нервов живота',
   'mkb_id': '1183',
   'inc_dt': '22.04.2021'},
  {'id': 15,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.5',
   'mkb_name': 'Злокачественное новообразование периферических нервов таза',
   'mkb_id': '1184',
   'inc_dt': '22.04.2021'},
  {'id': 16,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.6',
   'mkb_name': 'Злокачественное новообразование периферических нервов туловища неуточненное',
   'mkb_id': '1185',
   'inc_dt': '22.04.2021'},
  {'id': 17,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.8',
   'mkb_name': 'Злокачественное новообразование периферических нервов и вегетативной нервной системы, выходящее за пределы одной и более вышеуказанных локализаций',
   'mkb_id': '1186',
   'inc_dt': '22.04.2021'},
  {'id': 18,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C47.9',
   'mkb_name': 'Злокачественное новообразование периферических нервов и вегетативной нервной системы неуточненной локализации',
   'mkb_id': '1187',
   'inc_dt': '22.04.2021'},
  {'id': 29,
   'disease_name': 'Муковисцидоз',
   'disease_id': '10',
   'mkb_code': 'E84.8',
   'mkb_name': 'Кистозный фиброз с другими проявлениями',
   'mkb_id': '2390',
   'inc_dt': '13.05.2021'},
  {'id': 34,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.1',
   'mkb_name': 'Инсулинзависимый сахарный диабет с кетоацидозом',
   'mkb_id': '2062',
   'inc_dt': '11.06.2021'},
  {'id': 35,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.2',
   'mkb_name': 'Инсулинзависимый сахарный диабет с поражением почек',
   'mkb_id': '2063',
   'inc_dt': '11.06.2021'},
  {'id': 36,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.3',
   'mkb_name': 'Инсулинзависимый сахарный диабет с поражениями глаз',
   'mkb_id': '2064',
   'inc_dt': '11.06.2021'},
  {'id': 37,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.4',
   'mkb_name': 'Инсулинзависимый сахарный диабет с неврологическими осложнениями',
   'mkb_id': '2065',
   'inc_dt': '11.06.2021'},
  {'id': 38,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.5',
   'mkb_name': 'Инсулинзависимый сахарный диабет с нарушениями периферического кровообращения',
   'mkb_id': '2066',
   'inc_dt': '11.06.2021'},
  {'id': 39,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.6',
   'mkb_name': 'Инсулинзависимый сахарный диабет с другими уточненными осложнениями',
   'mkb_id': '2067',
   'inc_dt': '11.06.2021'},
  {'id': 40,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.7',
   'mkb_name': 'Инсулинзависимый сахарный диабет с множественными осложнениями',
   'mkb_id': '2068',
   'inc_dt': '11.06.2021'},
  {'id': 41,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.8',
   'mkb_name': 'Инсулинзависимый сахарный диабет с неуточненными осложнениями',
   'mkb_id': '2069',
   'inc_dt': '11.06.2021'},
  {'id': 42,
   'disease_name': 'Сахарный диабет 1 типа (дети от 0 до 4 лет)',
   'disease_id': '13',
   'mkb_code': 'E10.9',
   'mkb_name': 'Инсулинзависимый сахарный диабет без осложнений',
   'mkb_id': '2070',
   'inc_dt': '11.06.2021'},
  {'id': 76,
   'disease_name': 'Синдром короткой кишки',
   'disease_id': '11',
   'mkb_code': 'K91.2',
   'mkb_name': 'Нарушение всасывания после хирургического вмешательства, не классифицированное в других рубриках',
   'mkb_id': '4996',
   'inc_dt': '10.06.2021'},
  {'id': 77,
   'disease_name': 'Нарушение обмена цикла мочевины',
   'disease_id': '26',
   'mkb_code': 'E72.4',
   'mkb_name': 'Нарушения обмена орнитина',
   'mkb_id': '2317',
   'inc_dt': '02.09.2021'},
  {'id': 78,
   'disease_name': 'Нейрофиброматоз 1 типа',
   'disease_id': '24',
   'mkb_code': 'Q85.0',
   'mkb_name': 'Нейрофиброматоз (незлокачественный)',
   'mkb_id': '8082',
   'inc_dt': '02.09.2021'},
  {'id': 79,
   'disease_name': 'Нарушение обмена цикла мочевины',
   'disease_id': '26',
   'mkb_code': 'E72.2',
   'mkb_name': 'Нарушения обмена цикла мочевины',
   'mkb_id': '2315',
   'inc_dt': '02.09.2021'},
  {'id': 81,
   'disease_name': 'Липодистрофия',
   'disease_id': '27',
   'mkb_code': 'E88.1',
   'mkb_name': 'Липодистрофия, не классифицированная в других рубриках',
   'mkb_id': '2413',
   'inc_dt': '23.09.2021'},
  {'id': 82,
   'disease_name': 'Гомозиготная семейная гиперхолестеринемия',
   'disease_id': '28',
   'mkb_code': 'E78.0',
   'mkb_name': 'Чистая гиперхолестеринемия',
   'mkb_id': '2355',
   'inc_dt': '23.09.2021'},
  {'id': 83,
   'disease_name': 'Х-сцепленный доминантный гипофосфатемический рахит',
   'disease_id': '29',
   'mkb_code': 'E83.3',
   'mkb_name': 'Нарушения обмена фосфора и фосфатаз',
   'mkb_id': '2382',
   'inc_dt': '23.09.2021'},
  {'id': 84,
   'disease_name': 'Фенилкетонурия',
   'disease_id': '32',
   'mkb_code': 'E70.0',
   'mkb_name': 'Классическая фенилкетонурия',
   'mkb_id': '2301',
   'inc_dt': '30.09.2021'},
  {'id': 85,
   'disease_name': 'Фенилкетонурия',
   'disease_id': '32',
   'mkb_code': 'E70.1',
   'mkb_name': 'Другие виды гиперфенилаланинемии',
   'mkb_id': '2302',
   'inc_dt': '30.09.2021'},
  {'id': 86,
   'disease_name': 'Врожденные нарушения синтеза желчных кислот (НСЖК)',
   'disease_id': '23',
   'mkb_code': 'K76.8',
   'mkb_name': 'Другие уточненные болезни печени',
   'mkb_id': '4937',
   'inc_dt': '26.09.2021'},
  {'id': 87,
   'disease_name': 'Криопирин-ассоциированный периодический синдром',
   'disease_id': '4',
   'mkb_code': 'E85.0',
   'mkb_name': 'Наследственный семейный амилоидоз без невропатии',
   'mkb_id': '2393',
   'inc_dt': '03.03.2021'},
  {'id': 88,
   'disease_name': 'Мукополисахаридоз IV A',
   'disease_id': '7',
   'mkb_code': 'E76.0',
   'mkb_name': 'Мукополисахаридоз, тип I',
   'mkb_id': '2343',
   'inc_dt': '01.04.2021'},
  {'id': 89,
   'disease_name': 'Нейробластома',
   'disease_id': '8',
   'mkb_code': 'C74.0',
   'mkb_name': 'Злокачественное новообразование коры надпочечника',
   'mkb_id': '1323',
   'inc_dt': '22.04.2021'},
  {'id': 95,
   'disease_name': 'Синдром короткой кишки',
   'disease_id': '11',
   'mkb_code': 'K92.1',
   'mkb_name': 'Мелена',
   'mkb_id': '5004',
   'inc_dt': '10.06.2021'},
  {'id': 96,
   'disease_name': 'Первичная гипероксалурия I типа',
   'disease_id': '15',
   'mkb_code': 'E75.4',
   'mkb_name': 'Липофусциноз нейронов',
   'mkb_id': '2339',
   'inc_dt': '24.06.2021'},
  {'id': 97,
   'disease_name': 'Дефицит лизосомной кислой липазы',
   'disease_id': '21',
   'mkb_code': 'E75.5',
   'mkb_name': 'Другие нарушения накопления липидов',
   'mkb_id': '2340',
   'inc_dt': '22.07.2021'},
  {'id': 98,
   'disease_name': 'Наследственная дистрофия сетчатки, вызванная биаллельными мутациями в гене RPE65',
   'disease_id': '22',
   'mkb_code': 'H35.4',
   'mkb_name': 'Периферические ретинальные дегенерации',
   'mkb_id': '3503',
   'inc_dt': '29.07.2021'},
  {'id': 100,
   'disease_name': 'Цистиноз',
   'disease_id': '33',
   'mkb_code': 'E72.0',
   'mkb_name': 'Нарушения транспорта аминокислот',
   'mkb_id': '2313',
   'inc_dt': '30.09.2021'},
  {'id': 101,
   'disease_name': 'Пропионовая ацидемия',
   'disease_id': '34',
   'mkb_code': 'E71.1',
   'mkb_name': 'Другие виды нарушений обмена аминокислот с разветвленной цепью',
   'mkb_id': '2309',
   'inc_dt': '30.09.2021'},
  {'id': 102,
   'disease_name': 'Изовалериановая ацидемия',
   'disease_id': '35',
   'mkb_code': 'E71.1',
   'mkb_name': 'Другие виды нарушений обмена аминокислот с разветвленной цепью',
   'mkb_id': '2309',
   'inc_dt': '30.09.2021'},
  {'id': 103,
   'disease_name': 'Метилмалоновая ацидемия',
   'disease_id': '36',

In [11]:
type(data)

dict

In [12]:
# Преобразование вложенных данных в DataFrame
df_mkb10 = pd.json_normalize(data, "records")

df_mkb10.head()

,id,disease_name,disease_id,mkb_code,mkb_name,mkb_id,inc_dt
0,1,Спинальная мышечная атрофия,1,G12.0,"Детская спинальная мышечная атрофия, I тип [Ве...",2965,03.02.2021
1,2,Спинальная мышечная атрофия,1,G12.1,Другие наследственные спинальные мышечные атрофии,2966,03.02.2021
2,3,Спинальная мышечная атрофия,1,G12.2,Болезнь двигательного неврона,2967,03.02.2021
3,4,Спинальная мышечная атрофия,1,G12.8,Другие спинальные мышечные атрофии и родственн...,2968,03.02.2021
4,5,Спинальная мышечная атрофия,1,G12.9,Спинальная мышечная атрофия неуточненная,2969,03.02.2021

**XML** (Extensible Markup Language) — это язык разметки, предназначенный для хранения и передачи структурированных данных. XML-файлы широко используются для обмена информацией между различными системами, особенно в случаях, когда требуется передать сложные и иерархически организованные данные.

### Структура XML
XML-файл состоит из **тегов**, которые организуют данные в иерархическую структуру. Основные элементы XML:

1. **Теги** — элементы, заключённые в угловые скобки (`<tag>...</tag>`), которые обозначают начало и конец блока данных.
   
   ```xml
   <name>Иван</name>
   ```

2. **Атрибуты** — параметры внутри открывающего тега, которые добавляют свойства элементу.

   ```xml
   <employee id="123" department="HR">Иван</employee>
   ```

3. **Иерархия** — XML поддерживает вложенность, что позволяет создавать структуры данных с несколькими уровнями.

   ```xml
   <employees>
       <employee id="123" department="HR">
           <name>Иван</name>
           <age>30</age>
       </employee>
       <employee id="124" department="IT">
           <name>Анна</name>
           <age>25</age>
       </employee>
   </employees>
   ```

### Применение XML
XML часто используется для:

- **Обмена данными** между системами, так как легко читается и может быть проанализирован различными программами.
- **Конфигурационных файлов**: XML позволяет хранить настройки и параметры для приложений.
- **Хранения документов и данных** в иерархическом виде.
- **Веб-технологий**, например, в веб-сервисах (SOAP) и RSS-лентах.

**Источник:** [ФРВ. Лекарственные препараты](https://nsi.rosminzdrav.ru/dictionaries/1.2.643.5.1.13.13.99.2.630/passport/3.119)

In [13]:
df = pd.read_xml('лекарственные_препараты.xml')

In [14]:
df

   entry
0    NaN

Если при чтении XML-файла данные попали в один столбец entry с пустыми значениями (NaN), это может быть связано с особенностями структуры XML. Чтобы решить эту проблему, необходимо указать правильный xpath для извлечения данных.

In [15]:
df = pd.read_xml('лекарственные_препараты.xml', xpath=".//entry")
df

,name_trade,standard_inn,standard_form,standard_doze,ID
0,5-Фторурацил-Эбеве,ФТОРУРАЦИЛ,КОНЦЕНТРАТ ДЛЯ ПРИГОТОВЛЕНИЯ РАСТВОРА ДЛЯ ИНФУЗИЙ,50 мг/мл,179894
1,9 месяцев Калия йодид,КАЛИЯ ЙОДИД,ТАБЛЕТКИ,0.2 мг,1317
2,9 месяцев Фолиевая кислота,ФОЛИЕВАЯ КИСЛОТА,"ТАБЛЕТКИ, ПОКРЫТЫЕ ОБОЛОЧКОЙ",0.4 мг,188440
3,L-Малат изотонический,КАЛИЯ ХЛОРИД+КАЛЬЦИЯ ХЛОРИД+МАГНИЯ ХЛОРИД+НАТР...,РАСТВОР ДЛЯ ИНФУЗИЙ,0.2984 мг+0.3675 мг+0.2033 мг+3.266 мг+6.799 м...,353718
4,L-Тироксин,ЛЕВОТИРОКСИН НАТРИЯ,ТАБЛЕТКИ,0.05 мг,1599
...,...,...,...,...,...
18856,Телминорм,ТЕЛМИСАРТАН,ТАБЛЕТКИ,40 мг,601791
18857,Телминорм,ТЕЛМИСАРТАН,ТАБЛЕТКИ,80 мг,601799
18858,Тенрилтаб,РИЛПИВИРИН+ТЕНОФОВИР+ЭМТРИЦИТАБИН,"ТАБЛЕТКИ, ПОКРЫТЫЕ ОБОЛОЧКОЙ",25 мг+300 мг+200 мг,160646
18859,УЛЬТРАСОЛЮШН,РАСТВОРЫ ДЛЯ ПЕРИТОНЕАЛЬНОГО ДИАЛИЗА,РАСТВОР ДЛЯ ПЕРИТОНЕАЛЬНОГО ДИАЛИЗА,~,601837
18860,Энлигрия,ЛИРАГЛУТИД,РАСТВОР ДЛЯ ПОДКОЖНОГО ВВЕДЕНИЯ,6 мг/мл,557003

In [16]:
import xml.etree.ElementTree as ET
tree = ET.parse('лекарственные_препараты.xml')
root = tree.getroot()

In [17]:
root

In [18]:
root.tag

'book'

In [19]:
list(root)

In [20]:
list(root[0])

[<Element 'entry' at 0x7a6a66dec590>,
 <Element 'entry' at 0x7a6a66def790>,
 <Element 'entry' at 0x7a6a66ded7b0>,
 <Element 'entry' at 0x7a6a66dec4a0>,
 <Element 'entry' at 0x7a6a66decf90>,
 <Element 'entry' at 0x7a6a66dec9a0>,
 <Element 'entry' at 0x7a6a65298220>,
 <Element 'entry' at 0x7a6a65298450>,
 <Element 'entry' at 0x7a6a65298680>,
 <Element 'entry' at 0x7a6a652988b0>,
 <Element 'entry' at 0x7a6a65298ae0>,
 <Element 'entry' at 0x7a6a65298d10>,
 <Element 'entry' at 0x7a6a65298f40>,
 <Element 'entry' at 0x7a6a65299170>,
 <Element 'entry' at 0x7a6a652993a0>,
 <Element 'entry' at 0x7a6a65299580>,
 <Element 'entry' at 0x7a6a652997b0>,
 <Element 'entry' at 0x7a6a65299990>,
 <Element 'entry' at 0x7a6a65299bc0>,
 <Element 'entry' at 0x7a6a65299da0>,
 <Element 'entry' at 0x7a6a65299fd0>,
 <Element 'entry' at 0x7a6a6529a200>,
 <Element 'entry' at 0x7a6a6529a430>,
 <Element 'entry' at 0x7a6a6529a700>,
 <Element 'entry' at 0x7a6a6529a980>,
 <Element 'entry' at 0x7a6a6529ac00>,
 <Element 'entry' at 0x7a6a6529ae80>,
 <Element 'entry' at 0x7a6a6529b150>,
 <Element 'entry' at 0x7a6a6529b420>,
 <Element 'entry' at 0x7a6a6529b6f0>,
 <Element 'entry' at 0x7a6a6529b9c0>,
 <Element 'entry' at 0x7a6a6529bc90>,
 <Element 'entry' at 0x7a6a6529bf10>,
 <Element 'entry' at 0x7a6a652441d0>,
 <Element 'entry' at 0x7a6a65244450>,
 <Element 'entry' at 0x7a6a65244680>,
 <Element 'entry' at 0x7a6a652448b0>,
 <Element 'entry' at 0x7a6a65244b30>,
 <Element 'entry' at 0x7a6a65244d60>,
 <Element 'entry' at 0x7a6a65244f90>,
 <Element 'entry' at 0x7a6a65245210>,
 <Element 'entry' at 0x7a6a65245490>,
 <Element 'entry' at 0x7a6a65245710>,
 <Element 'entry' at 0x7a6a65245990>,
 <Element 'entry' at 0x7a6a65245c10>,
 <Element 'entry' at 0x7a6a65245e40>,
 <Element 'entry' at 0x7a6a65246070>,
 <Element 'entry' at 0x7a6a652462f0>,
 <Element 'entry' at 0x7a6a65246570>,
 <Element 'entry' at 0x7a6a652467a0>,
 <Element 'entry' at 0x7a6a652469d0>,
 <Element 'entry' at 0x7a6a65246bb0>,
 <Element 'entry' at 0x7a6a65246e30>,
 <Element 'entry' at 0x7a6a65247150>,
 <Element 'entry' at 0x7a6a65247420>,
 <Element 'entry' at 0x7a6a652476a0>,
 <Element 'entry' at 0x7a6a65247880>,
 <Element 'entry' at 0x7a6a65247a60>,
 <Element 'entry' at 0x7a6a65247c40>,
 <Element 'entry' at 0x7a6a65247e20>,
 <Element 'entry' at 0x7a6a6521c090>,
 <Element 'entry' at 0x7a6a6521c2c0>,
 <Element 'entry' at 0x7a6a6521c590>,
 <Element 'entry' at 0x7a6a6521c770>,
 <Element 'entry' at 0x7a6a6521ca40>,
 <Element 'entry' at 0x7a6a6521cc70>,
 <Element 'entry' at 0x7a6a6521cea0>,
 <Element 'entry' at 0x7a6a6521d080>,
 <Element 'entry' at 0x7a6a6521d260>,
 <Element 'entry' at 0x7a6a6521d4e0>,
 <Element 'entry' at 0x7a6a6521d710>,
 <Element 'entry' at 0x7a6a6521d940>,
 <Element 'entry' at 0x7a6a6521db20>,
 <Element 'entry' at 0x7a6a6521dda0>,
 <Element 'entry' at 0x7a6a6521e020>,
 <Element 'entry' at 0x7a6a6521e2a0>,
 <Element 'entry' at 0x7a6a6521e4d0>,
 <Element 'entry' at 0x7a6a6521e700>,
 <Element 'entry' at 0x7a6a6521e930>,
 <Element 'entry' at 0x7a6a6521ebb0>,
 <Element 'entry' at 0x7a6a6521ee30>,
 <Element 'entry' at 0x7a6a6521f060>,
 <Element 'entry' at 0x7a6a6521f290>,
 <Element 'entry' at 0x7a6a6521f510>,
 <Element 'entry' at 0x7a6a6521f790>,
 <Element 'entry' at 0x7a6a6521f970>,
 <Element 'entry' at 0x7a6a6521fc40>,
 <Element 'entry' at 0x7a6a6521ff10>,
 <Element 'entry' at 0x7a6a66eec220>,
 <Element 'entry' at 0x7a6a66eec4a0>,
 <Element 'entry' at 0x7a6a66eec720>,
 <Element 'entry' at 0x7a6a66eec9a0>,
 <Element 'entry' at 0x7a6a66eecbd0>,
 <Element 'entry' at 0x7a6a66eece00>,
 <Element 'entry' at 0x7a6a66eed030>,
 <Element 'entry' at 0x7a6a66eed260>,
 <Element 'entry' at 0x7a6a66eed490>,
 <Element 'entry' at 0x7a6a66eed6c0>,
 <Element 'entry' at 0x7a6a66eed8a0>,
 <Element 'entry' at 0x7a6a66eedb20>,
 <Element 'entry' at 0x7a6a66eedda0>,
 <Element 'entry' at 0x7a6a66eee020>,
 <Element 'entry' at 0x7a6a66eee2a0>,
 <Element 'entry' at 0x7a6a66eee480>,
 <Element 'entry' at 0x7a6a66eee660>,
 <Element 'entry' at 0x7a6a66eee840>,
 <Element 'entry' at 0x7a6a66eeea70>,
 <Element 'entry' at 0x7a6a66eeecf0>,
 <Element 'entry' at 0x7a6a66eeeed0>,
 <Element 'entry' at 0x7a6a66eef0b0>,
 <Element 'entry' at 0x7a6a66eef2e0>,
 <Element 'entry' at 0x7a6a66eef5b0>,
 <Element 'entry' at 0x7a6a66eef880>,
 <Element 'entry' at 0x7a6a66eefb00>,
 <Element 'entry' at 0x7a6a66eefd80>,
 <Element 'entry' at 0x7a6a66eeffb0>,
 <Element 'entry' at 0x7a6a66edc220>,
 <Element 'entry' at 0x7a6a66edc450>,
 <Element 'entry' at 0x7a6a66edc630>,
 <Element 'entry' at 0x7a6a66edc810>,
 <Element 'entry' at 0x7a6a66edcae0>,
 <Element 'entry' at 0x7a6a66edcdb0>,
 <Element 'entry' at 0x7a6a66edd030>,
 <Element 'entry' at 0x7a6a66edd260>,
 <Element 'entry' at 0x7a6a66edd490>,
 <Element 'entry' at 0x7a6a66edd6c0>,
 <Element 'entry' at 0x7a6a66edd8f0>,
 <Element 'entry' at 0x7a6a66eddb70>,
 <Element 'entry' at 0x7a6a66eddda0>,
 <Element 'entry' at 0x7a6a66ede0c0>,
 <Element 'entry' at 0x7a6a66ede390>,
 <Element 'entry' at 0x7a6a66ede5c0>,
 <Element 'entry' at 0x7a6a66ede7a0>,
 <Element 'entry' at 0x7a6a66edea20>,
 <Element 'entry' at 0x7a6a66eded40>,
 <Element 'entry' at 0x7a6a66edefc0>,
 <Element 'entry' at 0x7a6a66edf290>,
 <Element 'entry' at 0x7a6a66edf510>,
 <Element 'entry' at 0x7a6a66edf740>,
 <Element 'entry' at 0x7a6a66edf970>,
 <Element 'entry' at 0x7a6a66edfc90>,
 <Element 'entry' at 0x7a6a66edffb0>,
 <Element 'entry' at 0x7a6a66eac2c0>,
 <Element 'entry' at 0x7a6a66eac590>,
 <Element 'entry' at 0x7a6a66eac860>,
 <Element 'entry' at 0x7a6a66eacb30>,
 <Element 'entry' at 0x7a6a66eace00>,
 <Element 'entry' at 0x7a6a66ead0d0>,
 <Element 'entry' at 0x7a6a66ead3f0>,
 <Element 'entry' at 0x7a6a66ead6c0>,
 <Element 'entry' at 0x7a6a66ead990>,
 <Element 'entry' at 0x7a6a66eadc60>,
 <Element 'entry' at 0x7a6a66eadf30>,
 <Element 'entry' at 0x7a6a66eae200>,
 <Element 'entry' at 0x7a6a66eae480>,
 <Element 'entry' at 0x7a6a66eae700>,
 <Element 'entry' at 0x7a6a66eae9d0>,
 <Element 'entry' at 0x7a6a66eaeca0>,
 <Element 'entry' at 0x7a6a66eaef20>,
 <Element 'entry' at 0x7a6a66eaf1a0>,
 <Element 'entry' at 0x7a6a66eaf470>,
 <Element 'entry' at 0x7a6a66eaf6f0>,
 <Element 'entry' at 0x7a6a66eaf970>,
 <Element 'entry' at 0x7a6a66eafc40>,
 <Element 'entry' at 0x7a6a66eafec0>,
 <Element 'entry' at 0x7a6a66e98180>,
 <Element 'entry' at 0x7a6a66e98400>,
 <Element 'entry' at 0x7a6a66e98680>,
 <Element 'entry' at 0x7a6a66e98900>,
 <Element 'entry' at 0x7a6a66e98b80>,
 <Element 'entry' at 0x7a6a66e98e00>,
 <Element 'entry' at 0x7a6a66e99080>,
 <Element 'entry' at 0x7a6a66e99300>,
 <Element 'entry' at 0x7a6a66e995d0>,
 <Element 'entry' at 0x7a6a66e998a0>,
 <Element 'entry' at 0x7a6a66e99b20>,
 <Element 'entry' at 0x7a6a66e99da0>,
 <Element 'entry' at 0x7a6a66e9a020>,
 <Element 'entry' at 0x7a6a66e9a2f0>,
 <Element 'entry' at 0x7a6a66e9a5c0>,
 <Element 'entry' at 0x7a6a66e9a890>,
 <Element 'entry' at 0x7a6a66e9ab10>,
 <Element 'entry' at 0x7a6a66e9ad90>,
 <Element 'entry' at 0x7a6a66e9b010>,
 <Element 'entry' at 0x7a6a66e9b290>,
 <Element 'entry' at 0x7a6a66e9b5b0>,
 <Element 'entry' at 0x7a6a66e9b830>,
 <Element 'entry' at 0x7a6a66e9ba60>,
 <Element 'entry' at 0x7a6a66e9bce0>,
 <Element 'entry' at 0x7a6a66e9bf10>,
 <Element 'entry' at 0x7a6a66eb0180>,
 <Element 'entry' at 0x7a6a66eb03b0>,
 <Element 'entry' at 0x7a6a66eb05e0>,
 <Element 'entry' at 0x7a6a66eb0810>,
 <Element 'entry' at 0x7a6a66eb0ae0>,
 <Element 'entry' at 0x7a6a66eb0db0>,
 <Element 'entry' at 0x7a6a66eb0fe0>,
 <Element 'entry' at 0x7a6a66eb1210>,
 <Element 'entry' at 0x7a6a66eb13f0>,
 <Element 'entry' at 0x7a6a66eb15d0>,
 <Element 'entry' at 0x7a6a66eb17b0>,
 <Element 'entry' at 0x7a6a66eb19e0>,
 <Element 'entry' at 0x7a6a66eb1c10>,
 <Element 'entry' at 0x7a6a66eb1e40>,
 <Element 'entry' at 0x7a6a66eb2070>,
 <Element 'entry' at 0x7a6a66eb22a0>,
 <Element 'entry' at 0x7a6a66eb24d0>,
 <Element 'entry' at 0x7a6a66eb2700>,
 <Element 'entry' at 0x7a6a66eb28e0>,
 <Element 'entry' at 0x7a6a66eb2b10>,
 <Element 'entry' at 0x7a6a66eb2d90>,
 <Element 'entry' at 0x7a6a66eb3010>,
 <Element 'entry' at 0x7a6a66eb3290>,
 <Element 'entry' at 0x7a6a66eb34c0>,
 <Element 'entry' at 0x7a6a66eb36f0>,
 <Element 'entry' at 0x7a6a66eb38d0>,
 <Element 'entry' at 0x7a6a66eb3ab0>,
 <Element 'entry' at 0x7a6a66eb3c90>,
 <Element 'entry' at 0x7a6a66eb3e70>,
 <Element 'entry' at 0x7a6a66eb4090>,
 <Element 'entry' at 0x7a6a66eb42c0>,
 <Element 'entry' at 0x7a6a66eb44f0>,
 <Element 'entry' at 0x7a6a66eb46d0>,
 <Element 'entry' at 0x7a6a66eb4900>,
 <Element 'entry' at 0x7a6a66eb4ae0>,
 <Element 'entry' at 0x7a6a66eb4d10>,
 <Element 'entry' at 0x7a6a66eb4f40>,
 <Element 'entry' at 0x7a6a66eb5170>,
 <Element 'entry' at 0x7a6a66eb53a0>,
 <Element 'entry' at 0x7a6a66eb55d0>,
 <Element 'entry' at 0x7a6a66eb5800>,
 <Element 'entry' at 0x7a6a66eb5a80>,
 <Element 'entry' at 0x7a6a66eb5d00>,
 <Element 'entry' at 0x7a6a66eb5f80>,
 <Element 'entry' at 0x7a6a66eb6200>,
 <Element 'entry' at 0x7a6a66eb6430>,
 <Element 'entry' at 0x7a6a66eb66b0>,
 <Element 'entry' at 0x7a6a66eb6930>,
 <Element 'entry' at 0x7a6a66eb6bb0>,
 <Element 'entry' at 0x7a6a66eb6de0>,
 <Element 'entry' at 0x7a6a66eb6fc0>,
 <Element 'entry' at 0x7a6a66eb71f0>,
 <Element 'entry' at 0x7a6a66eb7420>,
 <Element 'entry' at 0x7a6a66eb76a0>,
 <Element 'entry' at 0x7a6a66eb7920>,
 <Element 'entry' at 0x7a6a66eb7ba0>,
 <Element 'entry' at 0x7a6a66eb7e20>,
 <Element 'entry' at 0x7a6a655fc040>,
 <Element 'entry' at 0x7a6a655fc220>,
 <Element 'entry' at 0x7a6a655fc450>,
 <Element 'entry' at 0x7a6a655fc680>,
 <Element 'entry' at 0x7a6a655fc8b0>,
 <Element 'entry' at 0x7a6a655fcae0>,
 <Element 'entry' at 0x7a6a655fcd60>,
 <Element 'entry' at 0x7a6a655fcfe0>,
 <Element 'entry' at 0x7a6a655fd260>,
 <Element 'entry' at 0x7a6a655fd440>,
 <Element 'entry' at 0x7a6a655fd620>,
 <Element 'entry' at 0x7a6a655fd850>,
 <Element 'entry' at 0x7a6a655fda80>,
 <Element 'entry' at 0x7a6a655fdd00>,
 <Element 'entry' at 0x7a6a655fdf80>,
 <Element 'entry' at 0x7a6a655fe250>,
 <Element 'entry' at 0x7a6a655fe520>,
 <Element 'entry' at 0x7a6a655fe7f0>,
 <Element 'entry' at 0x7a6a655feac0>,
 <Element 'entry' at 0x7a6a655fed90>,
 <Element 'entry' at 0x7a6a655fef70>,
 <Element 'entry' at 0x7a6a655ff240>,
 <Element 'entry' at 0x7a6a655ff510>,
 <Element 'entry' at 0x7a6a655ff7e0>,
 <Element 'entry' at 0x7a6a655ffab0>,
 <Element 'entry' at 0x7a6a655ffd30>,
 <Element 'entry' at 0x7a6a655fffb0>,
 <Element 'entry' at 0x7a6a655e8220>,
 <Element 'entry' at 0x7a6a655e8450>,
 <Element 'entry' at 0x7a6a655e8680>,
 <Element 'entry' at 0x7a6a655e8860>,
 <Element 'entry' at 0x7a6a655e8ae0>,
 <Element 'entry' at 0x7a6a655e8d60>,
 <Element 'entry' at 0x7a6a655e8f90>,
 <Element 'entry' at 0x7a6a655e9210>,
 <Element 'entry' at 0x7a6a655e9490>,
 <Element 'entry' at 0x7a6a655e96c0>,
 <Element 'entry' at 0x7a6a655e98a0>,
 <Element 'entry' at 0x7a6a655e9ad0>,
 <Element 'entry' at 0x7a6a655e9d00>,
 <Element 'entry' at 0x7a6a655e9f30>,
 <Element 'entry' at 0x7a6a655ea160>,
 <Element 'entry' at 0x7a6a655ea390>,
 <Element 'entry' at 0x7a6a655ea610>,
 <Element 'entry' at 0x7a6a655ea890>,
 <Element 'entry' at 0x7a6a655eab10>,
 <Element 'entry' at 0x7a6a655ead90>,
 <Element 'entry' at 0x7a6a655eafc0>,
 <Element 'entry' at 0x7a6a655eb240>,
 <Element 'entry' at 0x7a6a655eb510>,
 <Element 'entry' at 0x7a6a655eb7e0>,
 <Element 'entry' at 0x7a6a655ebab0>,
 <Element 'entry' at 0x7a6a655ebc90>,
 <Element 'entry' at 0x7a6a655ebec0>,
 <Element 'entry' at 0x7a6a655c8130>,
 <Element 'entry' at 0x7a6a655c8360>,
 <Element 'entry' at 0x7a6a655c8540>,
 <Element 'entry' at 0x7a6a655c8720>,
 <Element 'entry' at 0x7a6a655c8950>,
 <Element 'entry' at 0x7a6a655c8bd0>,
 <Element 'entry' at 0x7a6a655c8e50>,
 <Element 'entry' at 0x7a6a655c90d0>,
 <Element 'entry' at 0x7a6a655c9300>,
 <Element 'entry' at 0x7a6a655c9530>,
 <Element 'entry' at 0x7a6a655c9800>,
 <Element 'entry' at 0x7a6a655c9a80>,
 <Element 'entry' at 0x7a6a655c9d00>,
 <Element 'entry' at 0x7a6a655c9f30>,
 <Element 'entry' at 0x7a6a655ca160>,
 <Element 'entry' at 0x7a6a655ca390>,
 <Element 'entry' at 0x7a6a655ca5c0>,
 <Element 'entry' at 0x7a6a655ca840>,
 <Element 'entry' at 0x7a6a655caac0>,
 <Element 'entry' at 0x7a6a655cad40>,
 <Element 'entry' at 0x7a6a655cafc0>,
 <Element 'entry' at 0x7a6a655cb240>,
 <Element 'entry' at 0x7a6a655cb470>,
 <Element 'entry' at 0x7a6a655cb6a0>,
 <Element 'entry' at 0x7a6a655cb920>,
 <Element 'entry' at 0x7a6a655cbba0>,
 <Element 'entry' at 0x7a6a655cbdd0>,
 <Element 'entry' at 0x7a6a655bc040>,
 <Element 'entry' at 0x7a6a655bc310>,
 <Element 'entry' at 0x7a6a655bc5e0>,
 <Element 'entry' at 0x7a6a655bc810>,
 <Element 'entry' at 0x7a6a655bca90>,
 <Element 'entry' at 0x7a6a655bcc70>,
 <Element 'entry' at 0x7a6a655bce50>,
 <Element 'entry' at 0x7a6a655bd030>,
 <Element 'entry' at 0x7a6a655bd260>,
 <Element 'entry' at 0x7a6a655bd4e0>,
 <Element 'entry' at 0x7a6a655bd760>,
 <Element 'entry' at 0x7a6a655bd9e0>,
 <Element 'entry' at 0x7a6a655bdc10>,
 <Element 'entry' at 0x7a6a655bddf0>,
 <Element 'entry' at 0x7a6a655bdfd0>,
 <Element 'entry' at 0x7a6a655be1b0>,
 <Element 'entry' at 0x7a6a655be390>,
 <Element 'entry' at 0x7a6a655be570>,
 <Element 'entry' at 0x7a6a655be750>,
 <Element 'entry' at 0x7a6a655be930>,
 <Element 'entry' at 0x7a6a655beb10>,
 <Element 'entry' at 0x7a6a655becf0>,
 <Element 'entry' at 0x7a6a655beed0>,
 <Element 'entry' at 0x7a6a655bf0b0>,
 <Element 'entry' at 0x7a6a655bf290>,
 <Element 'entry' at 0x7a6a655bf470>,
 <Element 'entry' at 0x7a6a655bf6a0>,
 <Element 'entry' at 0x7a6a655bf8d0>,
 <Element 'entry' at 0x7a6a655bfab0>,
 <Element 'entry' at 0x7a6a655bfd80>,
 <Element 'entry' at 0x7a6a655b4090>,
 <Element 'entry' at 0x7a6a655b42c0>,
 <Element 'entry' at 0x7a6a655b44a0>,
 <Element 'entry' at 0x7a6a655b4680>,
 <Element 'entry' at 0x7a6a655b4950>,
 <Element 'entry' at 0x7a6a655b4c20>,
 <Element 'entry' at 0x7a6a655b4ea0>,
 <Element 'entry' at 0x7a6a655b50d0>,
 <Element 'entry' at 0x7a6a655b5300>,
 <Element 'entry' at 0x7a6a655b55d0>,
 <Element 'entry' at 0x7a6a655b58a0>,
 <Element 'entry' at 0x7a6a655b5b20>,
 <Element 'entry' at 0x7a6a655b5da0>,
 <Element 'entry' at 0x7a6a655b6020>,
 <Element 'entry' at 0x7a6a655b62a0>,
 <Element 'entry' at 0x7a6a655b64d0>,
 <Element 'entry' at 0x7a6a655b66b0>,
 <Element 'entry' at 0x7a6a655b68e0>,
 <Element 'entry' at 0x7a6a655b6ac0>,
 <Element 'entry' at 0x7a6a655b6ca0>,
 <Element 'entry' at 0x7a6a655b6ed0>,
 <Element 'entry' at 0x7a6a655b7100>,
 <Element 'entry' at 0x7a6a655b72e0>,
 <Element 'entry' at 0x7a6a655b7510>,
 <Element 'entry' at 0x7a6a655b7740>,
 <Element 'entry' at 0x7a6a655b7920>,
 <Element 'entry' at 0x7a6a655b7b50>,
 <Element 'entry' at 0x7a6a655b7d80>,
 <Element 'entry' at 0x7a6a655b7fb0>,
 <Element 'entry' at 0x7a6a6559c2c0>,
 <Element 'entry' at 0x7a6a6559c590>,
 <Element 'entry' at 0x7a6a6559c860>,
 <Element 'entry' at 0x7a6a6559cb30>,
 <Element 'entry' at 0x7a6a6559cd60>,
 <Element 'entry' at 0x7a6a6559cf90>,
 <Element 'entry' at 0x7a6a6559d170>,
 <Element 'entry' at 0x7a6a6559d440>,
 <Element 'entry' at 0x7a6a6559d670>,
 <Element 'entry' at 0x7a6a6559d8a0>,
 <Element 'entry' at 0x7a6a6559db70>,
 <Element 'entry' at 0x7a6a6559dda0>,
 <Element 'entry' at 0x7a6a6559df80>,
 <Element 'entry' at 0x7a6a6559e1b0>,
 <Element 'entry' at 0x7a6a6559e3e0>,
 <Element 'entry' at 0x7a6a6559e660>,
 <Element 'entry' at 0x7a6a6559e930>,
 <Element 'entry' at 0x7a6a6559eb10>,
 <Element 'entry' at 0x7a6a6559ed40>,
 <Element 'entry' at 0x7a6a6559ef70>,
 <Element 'entry' at 0x7a6a6559f1a0>,
 <Element 'entry' at 0x7a6a6559f380>,
 <Element 'entry' at 0x7a6a6559f560>,
 <Element 'entry' at 0x7a6a6559f740>,
 <Element 'entry' at 0x7a6a6559f920>,
 <Element 'entry' at 0x7a6a6559fb00>,
 <Element 'entry' at 0x7a6a6559fce0>,
 <Element 'entry' at 0x7a6a6559fec0>,
 <Element 'entry' at 0x7a6a655900e0>,
 <Element 'entry' at 0x7a6a655902c0>,
 <Element 'entry' at 0x7a6a655904a0>,
 <Element 'entry' at 0x7a6a65590680>,
 <Element 'entry' at 0x7a6a65590860>,
 <Element 'entry' at 0x7a6a65590a40>,
 <Element 'entry' at 0x7a6a65590c20>,
 <Element 'entry' at 0x7a6a65590e00>,
 <Element 'entry' at 0x7a6a65590fe0>,
 <Element 'entry' at 0x7a6a655911c0>,
 <Element 'entry' at 0x7a6a655913a0>,
 <Element 'entry' at 0x7a6a65591580>,
 <Element 'entry' at 0x7a6a65591760>,
 <Element 'entry' at 0x7a6a655919e0>,
 <Element 'entry' at 0x7a6a65591c10>,
 <Element 'entry' at 0x7a6a65591e40>,
 <Element 'entry' at 0x7a6a65592070>,
 <Element 'entry' at 0x7a6a655922a0>,
 <Element 'entry' at 0x7a6a655924d0>,
 <Element 'entry' at 0x7a6a65592750>,
 <Element 'entry' at 0x7a6a655929d0>,
 <Element 'entry' at 0x7a6a65592c00>,
 <Element 'entry' at 0x7a6a65592e80>,
 <Element 'entry' at 0x7a6a65593100>,
 <Element 'entry' at 0x7a6a65593330>,
 <Element 'entry' at 0x7a6a655935b0>,
 <Element 'entry' at 0x7a6a65593830>,
 <Element 'entry' at 0x7a6a65593a10>,
 <Element 'entry' at 0x7a6a65593c40>,
 <Element 'entry' at 0x7a6a65593ec0>,
 <Element 'entry' at 0x7a6a65574180>,
 <Element 'entry' at 0x7a6a655743b0>,
 <Element 'entry' at 0x7a6a655745e0>,
 <Element 'entry' at 0x7a6a65574860>,
 <Element 'entry' at 0x7a6a65574ae0>,
 <Element 'entry' at 0x7a6a65574d60>,
 <Element 'entry' at 0x7a6a65574f90>,
 <Element 'entry' at 0x7a6a65575170>,
 <Element 'entry' at 0x7a6a65575350>,
 <Element 'entry' at 0x7a6a65575530>,
 <Element 'entry' at 0x7a6a65575760>,
 <Element 'entry' at 0x7a6a655759e0>,
 <Element 'entry' at 0x7a6a65575c60>,
 <Element 'entry' at 0x7a6a65575ee0>,
 <Element 'entry' at 0x7a6a655760c0>,
 <Element 'entry' at 0x7a6a655762a0>,
 <Element 'entry' at 0x7a6a65576480>,
 <Element 'entry' at 0x7a6a65576660>,
 <Element 'entry' at 0x7a6a65576840>,
 <Element 'entry' at 0x7a6a65576ac0>,
 <Element 'entry' at 0x7a6a65576ca0>,
 <Element 'entry' at 0x7a6a65576ed0>,
 <Element 'entry' at 0x7a6a65577150>,
 <Element 'entry' at 0x7a6a65577330>,
 <Element 'entry' at 0x7a6a655775b0>,
 <Element 'entry' at 0x7a6a65577790>,
 <Element 'entry' at 0x7a6a65577970>,
 <Element 'entry' at 0x7a6a65577b50>,
 <Element 'entry' at 0x7a6a65577d30>,
 <Element 'entry' at 0x7a6a65577f60>,
 <Element 'entry' at 0x7a6a65528180>,
 <Element 'entry' at 0x7a6a65528360>,
 <Element 'entry' at 0x7a6a65528540>,
 <Element 'entry' at 0x7a6a655287c0>,
 <Element 'entry' at 0x7a6a655289a0>,
 <Element 'entry' at 0x7a6a65528c70>,
 <Element 'entry' at 0x7a6a65528f40>,
 <Element 'entry' at 0x7a6a65529210>,
 <Element 'entry' at 0x7a6a655294e0>,
 <Element 'entry' at 0x7a6a655296c0>,
 <Element 'entry' at 0x7a6a655298a0>,
 <Element 'entry' at 0x7a6a65529a80>,
 <Element 'entry' at 0x7a6a65529c60>,
 <Element 'entry' at 0x7a6a65529f30>,
 <Element 'entry' at 0x7a6a6552a160>,
 <Element 'entry' at 0x7a6a6552a340>,
 <Element 'entry' at 0x7a6a6552a570>,
 <Element 'entry' at 0x7a6a6552a7f0>,
 <Element 'entry' at 0x7a6a6552aa70>,
 <Element 'entry' at 0x7a6a6552ac50>,
 <Element 'entry' at 0x7a6a6552ae80>,
 <Element 'entry' at 0x7a6a6552b100>,
 <Element 'entry' at 0x7a6a6552b3d0>,
 <Element 'entry' at 0x7a6a6552b6a0>,
 <Element 'entry' at 0x7a6a6552b920>,
 <Element 'entry' at 0x7a6a6552bba0>,
 <Element 'entry' at 0x7a6a6552bdd0>,
 <Element 'entry' at 0x7a6a6552bfb0>,
 <Element 'entry' at 0x7a6a6554c1d0>,
 <Element 'entry' at 0x7a6a6554c450>,
 <Element 'entry' at 0x7a6a6554c680>,
 <Element 'entry' at 0x7a6a6554c860>,
 <Element 'entry' at 0x7a6a6554ca40>,
 <Element 'entry' at 0x7a6a6554ccc0>,
 <Element 'entry' at 0x7a6a6554cf90>,
 <Element 'entry' at 0x7a6a6554d260>,
 <Element 'entry' at 0x7a6a6554d4e0>,
 <Element 'entry' at 0x7a6a6554d710>,
 <Element 'entry' at 0x7a6a6554d940>,
 <Element 'entry' at 0x7a6a6554db20>,
 <Element 'entry' at 0x7a6a6554dda0>,
 <Element 'entry' at 0x7a6a6554e020>,
 <Element 'entry' at 0x7a6a6554e250>,
 <Element 'entry' at 0x7a6a6554e4d0>,
 <Element 'entry' at 0x7a6a6554e750>,
 <Element 'entry' at 0x7a6a6554e980>,
 <Element 'entry' at 0x7a6a6554ebb0>,
 <Element 'entry' at 0x7a6a6554ede0>,
 <Element 'entry' at 0x7a6a6554f010>,
 <Element 'entry' at 0x7a6a6554f240>,
 <Element 'entry' at 0x7a6a6554f470>,

In [21]:
list(root[0][0])

[<Element 'name_trade' at 0x7a6a66ded030>,
 <Element 'standard_inn' at 0x7a6a66dec130>,
 <Element 'standard_form' at 0x7a6a66defdd0>,
 <Element 'standard_doze' at 0x7a6a66deeb60>,
 <Element 'ID' at 0x7a6a66def420>]

### API

**Источник:** [API ВОЗ](https://www.who.int/data/gho/info/gho-odata-api)

In [22]:
import requests
import pandas as pd

In [23]:
# Посмотрим на список всех возможнх данных
url = "https://ghoapi.azureedge.net/api/Indicator"

# Отправка запроса
response = requests.get(url)

In [24]:
response.status_code

200

In [26]:
ind = pd.DataFrame(response.json()['value'])
ind

,IndicatorCode,IndicatorName,Language
0,EMFLIMITELECTRIC900,Electric field limit at 900 MHz (V/m),EN
1,EMFLIMITELECTRICLF,Electric field (kV/m),EN
2,EMFLIMITPOWERDENSITY1800,Power density limit at 1800 MHz (W/m^2),EN
3,EMFSTANDARD,Existence of standards,EN
4,FINPROTECTION_IMP_NP190_POP,Population pushed below the $1.90 a day pove...,EN
...,...,...,...
3034,ORALHEALTH_DENOMINATOR_TTLPOP,Total population in thousands (oral health),EN
3035,STI_TRICHOMONIASIS_INCIDENCE_PER1000,Incident cases of trichomoniasis in individual...,EN
3036,FINPROTECTION_IMP_NP_365_LEVEL_SH,Total population pushed below the $3.65 a day ...,EN
3037,HEPATITIS_HCV_TESTING_PWID_PERCENT,"People living with HIV who inject drugs, diagn...",EN
3038,IHRSPAR_CAPACITY04,Food Safety (SPAR),EN

In [27]:
ind[ind['IndicatorCode'] == 'LIFE_0000000035']

       IndicatorCode                      IndicatorName Language
492  LIFE_0000000035  ex - expectation of life at age x       EN

In [39]:
# URL API для получения данных о продолжительности жизни
url = "https://ghoapi.azureedge.net/api/LIFE_0000000035"

# Параметры запроса (например, фильтрация по году)
params = {
    "$filter": "TimeDim ge 2020",  # "TimeDim" — год
    "$format": "json"
}

# Отправка запроса
response = requests.get(url, params=params)

In [40]:
response.json()

{'@odata.context': 'https://ghoapi.azureedge.net/api/$metadata#LIFE_0000000035',
 'value': [{'Id': 6574216,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'QAT',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EMR',
   'ParentLocation': 'Eastern Mediterranean',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS85PLUS',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '4.68670',
   'NumericValue': 4.686697656,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 348,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'SVK',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS10-14',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '70.66564',
   'NumericValue': 70.665639238,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 630,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'ALB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS15-19',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '62.41226',
   'NumericValue': 62.412257199,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 710,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'SEN',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS05-09',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '66.35091',
   'NumericValue': 66.350910394,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 738,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'BDI',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS01-04',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '64.31065',
   'NumericValue': 64.310648619,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 874,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'GNQ',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS25-29',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '42.21393',
   'NumericValue': 42.213926274,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 2034,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'DNK',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS01-04',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '80.44328',
   'NumericValue': 80.443283148,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 2497,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'GAB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS15-19',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '51.28642',
   'NumericValue': 51.286418711,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 2900,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'NOR',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS85PLUS',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '6.14899',
   'NumericValue': 6.148993369,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 3405,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'UZB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS25-29',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '50.58500',
   'NumericValue': 50.584999647,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 3498,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'COD',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS30-34',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '37.34705',
   'NumericValue': 37.347049342,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 3790,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'QAT',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EMR',
   'ParentLocation': 'Eastern Mediterranean',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS60-64',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '19.65978',
   'NumericValue': 19.65977516,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 3977,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'SWE',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS50-54',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '32.52118',
   'NumericValue': 32.521183974,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 3988,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'GNB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS05-09',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '58.32894',
   'NumericValue': 58.328941821,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 4543,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'SRB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS10-14',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '67.74583',
   'NumericValue': 67.745830955,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 5003,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'KEN',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS85PLUS',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '5.74162',
   'NumericValue': 5.741615899,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 7159,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'IDN',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'SEAR',
   'ParentLocation': 'South-East Asia',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS05-09',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '68.35925',
   'NumericValue': 68.359252373,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 7566,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'LKA',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'SEAR',
   'ParentLocation': 'South-East Asia',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS20-24',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '60.78121',
   'NumericValue': 60.781211726,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 7623,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'SUR',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AMR',
   'ParentLocation': 'Americas',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS45-49',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '29.59641',
   'NumericValue': 29.59641444,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 7853,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'PSE',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EMR',
   'ParentLocation': 'Eastern Mediterranean',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS35-39',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '40.39142',
   'NumericValue': 40.391422712,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 7935,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'ARM',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS15-19',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '55.24026',
   'NumericValue': 55.24025742,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 8992,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'KWT',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EMR',
   'ParentLocation': 'Eastern Mediterranean',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS60-64',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '22.32045',
   'NumericValue': 22.320449247,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 10188,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'MDA',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS01-04',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '72.05121',
   'NumericValue': 72.051207538,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 10211,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'LKA',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'SEAR',
   'ParentLocation': 'South-East Asia',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_FMLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS55-59',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '30.17277',
   'NumericValue': 30.172770658,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 10486,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'ALB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'EUR',
   'ParentLocation': 'Europe',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS00-01',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '74.36082',
   'NumericValue': 74.360823536,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 10508,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'GAB',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS85PLUS',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '3.79027',
   'NumericValue': 3.790273403,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2021',
   'TimeDimensionBegin': '2021-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2021-12-31T00:00:00+01:00'},
  {'Id': 11097,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'LSO',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'AFR',
   'ParentLocation': 'Africa',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_MLE',
   'TimeDim': 2020,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS00-01',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '48.94162',
   'NumericValue': 48.941619404,
   'Low': None,
   'High': None,
   'Comments': None,
   'Date': '2024-09-09T15:51:28.783+02:00',
   'TimeDimensionValue': '2020',
   'TimeDimensionBegin': '2020-01-01T00:00:00+01:00',
   'TimeDimensionEnd': '2020-12-31T00:00:00+01:00'},
  {'Id': 11230,
   'IndicatorCode': 'LIFE_0000000035',
   'SpatialDimType': 'COUNTRY',
   'SpatialDim': 'TLS',
   'TimeDimType': 'YEAR',
   'ParentLocationCode': 'SEAR',
   'ParentLocation': 'South-East Asia',
   'Dim1Type': 'SEX',
   'Dim1': 'SEX_BTSX',
   'TimeDim': 2021,
   'Dim2Type': 'AGEGROUP',
   'Dim2': 'AGEGROUP_YEARS01-04',
   'Dim3Type': None,
   'Dim3': None,
   'DataSourceDimType': None,
   'DataSourceDim': None,
   'Value': '70.02975',
   'NumericValue': 70.029747413,
   'Low': None,
   'High': None,
   'Comments': None,

In [41]:
pd.DataFrame(response.json()['value'])

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,ParentLocationCode,ParentLocation,Dim1Type,Dim1,TimeDim,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,6574216,LIFE_0000000035,COUNTRY,QAT,YEAR,EMR,Eastern Mediterranean,SEX,SEX_FMLE,2021,...,None,4.68670,4.686698,None,None,None,2024-09-09T15:51:28.783+02:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00
1,348,LIFE_0000000035,COUNTRY,SVK,YEAR,EUR,Europe,SEX,SEX_FMLE,2020,...,None,70.66564,70.665639,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
2,630,LIFE_0000000035,COUNTRY,ALB,YEAR,EUR,Europe,SEX,SEX_BTSX,2020,...,None,62.41226,62.412257,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
3,710,LIFE_0000000035,COUNTRY,SEN,YEAR,AFR,Africa,SEX,SEX_BTSX,2020,...,None,66.35091,66.350910,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
4,738,LIFE_0000000035,COUNTRY,BDI,YEAR,AFR,Africa,SEX,SEX_MLE,2020,...,None,64.31065,64.310649,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22339,10176393,LIFE_0000000035,COUNTRY,GMB,YEAR,AFR,Africa,SEX,SEX_BTSX,2021,...,None,9.93805,9.938050,None,None,None,2024-09-09T15:51:28.783+02:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00
22340,10177354,LIFE_0000000035,COUNTRY,BGD,YEAR,SEAR,South-East Asia,SEX,SEX_MLE,2020,...,None,31.04191,31.041913,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
22341,10177582,LIFE_0000000035,COUNTRY,GMB,YEAR,AFR,Africa,SEX,SEX_MLE,2020,...,None,18.10754,18.107541,None,None,None,2024-09-09T15:51:28.783+02:00,2020,2020-01-01T00:00:00+01:00,2020-12-31T00:00:00+01:00
22342,10178609,LIFE_0000000035,COUNTRY,TJK,YEAR,EUR,Europe,SEX,SEX_MLE,2021,...,None,21.58514,21.585144,None,None,None,2024-09-09T15:51:28.783+02:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00
22343,10180048,LIFE_0000000035,COUNTRY,DNK,YEAR,EUR,Europe,SEX,SEX_MLE,2021,...,None,40.39516,40.395161,None,None,None,2024-09-09T15:51:28.783+02:00,2021,2021-01-01T00:00:00+01:00,2021-12-31T00:00:00+01:00

***

**Источник:** [Описание API nobelprize](https://www.nobelprize.org/organization/developer-zone-2/)

In [42]:
# URL API для получения данных о лауреатах
url = "https://api.nobelprize.org/2.1/laureates"

# Отправка запроса
response = requests.get(url)
data = response.json()
data

{'laureates': [{'id': '745',
   'knownName': {'en': 'A. Michael Spence', 'se': 'A. Michael Spence'},
   'givenName': {'en': 'A. Michael', 'se': 'A. Michael'},
   'familyName': {'en': 'Spence', 'se': 'Spence'},
   'fullName': {'en': 'A. Michael Spence', 'se': 'A. Michael Spence'},
   'fileName': 'spence',
   'gender': 'male',
   'birth': {'date': '1943-00-00',
    'place': {'city': {'en': 'Montclair, NJ',
      'no': 'Montclair, NJ',
      'se': 'Montclair, NJ'},
     'country': {'en': 'USA', 'no': 'USA', 'se': 'USA'},
     'cityNow': {'en': 'Montclair, NJ',
      'no': 'Montclair, NJ',
      'se': 'Montclair, NJ',
      'sameAs': ['https://www.wikidata.org/wiki/Q678437',
       'https://www.wikipedia.org/wiki/Montclair,_New_Jersey'],
      'latitude': '40.825930',
      'longitude': '-74.209030'},
     'countryNow': {'en': 'USA',
      'no': 'USA',
      'se': 'USA',
      'sameAs': ['https://www.wikidata.org/wiki/Q30'],
      'latitude': '39.828175',
      'longitude': '-98.579500'},
     'continent': {'en': 'North America',
      'no': 'Nord-Amerika',
      'se': 'Nordamerika'},
     'locationString': {'en': 'Montclair, NJ, USA',
      'no': 'Montclair, NJ, USA',
      'se': 'Montclair, NJ, USA'}}},
   'wikipedia': {'slug': 'Michael_Spence',
    'english': 'https://en.wikipedia.org/wiki/Michael_Spence'},
   'wikidata': {'id': 'Q157245',
    'url': 'https://www.wikidata.org/wiki/Q157245'},
   'sameAs': ['https://www.wikidata.org/wiki/Q157245',
    'https://en.wikipedia.org/wiki/Michael_Spence'],
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/745',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/laureate/745',
     'title': 'A. Michael Spence - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']}],
   'nobelPrizes': [{'awardYear': '2001',
     'category': {'en': 'Economic Sciences', 'no': 'Økonomi', 'se': 'Ekonomi'},
     'categoryFullName': {'en': 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel',
      'no': 'Sveriges Riksbanks pris i økonomisk vitenskap til minne om Alfred Nobel',
      'se': 'Sveriges Riksbanks pris i ekonomisk vetenskap till Alfred Nobels minne'},
     'sortOrder': '2',
     'portion': '1/3',
     'dateAwarded': '2001-10-10',
     'prizeStatus': 'received',
     'motivation': {'en': 'for their analyses of markets with asymmetric information',
      'se': 'för deras analys av marknader med assymetrisk informations'},
     'prizeAmount': 10000000,
     'prizeAmountAdjusted': 15547541,
     'affiliations': [{'name': {'en': 'Stanford University',
        'no': 'Stanford University',
        'se': 'Stanford University'},
       'nameNow': {'en': 'Stanford University'},
       'city': {'en': 'Stanford, CA',
        'no': 'Stanford, CA',
        'se': 'Stanford, CA'},
       'country': {'en': 'USA', 'no': 'USA', 'se': 'USA'},
       'cityNow': {'en': 'Stanford, CA',
        'no': 'Stanford, CA',
        'se': 'Stanford, CA',
        'sameAs': ['https://www.wikidata.org/wiki/Q173813',
         'https://www.wikipedia.org/wiki/Stanford,_California'],
        'latitude': '37.424734',
        'longitude': '-122.163858'},
       'countryNow': {'en': 'USA',
        'no': 'USA',
        'se': 'USA',
        'sameAs': ['https://www.wikidata.org/wiki/Q30'],
        'latitude': '39.828175',
        'longitude': '-98.579500'},
       'continent': {'en': 'North America'},
       'locationString': {'en': 'Stanford, CA, USA',
        'no': 'Stanford, CA, USA',
        'se': 'Stanford, CA, USA'}}],
     'links': [{'rel': 'nobelPrize',
       'href': 'https://api.nobelprize.org/2/nobelPrize/eco/2001',
       'action': 'GET',
       'types': 'application/json'},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/economic-sciences/2001/spence/facts/',
       'title': 'A. Michael Spence - Facts',
       'action': 'GET',
       'types': 'text/html',
       'class': ['laureate facts']},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/economic-sciences/2001/summary/',
       'title': 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2001',
       'action': 'GET',
       'types': 'text/html',
       'class': ['prize summary']}]}]},
  {'id': '102',
   'knownName': {'en': 'Aage N. Bohr', 'se': 'Aage N. Bohr'},
   'givenName': {'en': 'Aage N.', 'se': 'Aage N.'},
   'familyName': {'en': 'Bohr', 'se': 'Bohr'},
   'fullName': {'en': 'Aage Niels Bohr', 'se': 'Aage Niels Bohr'},
   'fileName': 'bohr',
   'gender': 'male',
   'birth': {'date': '1922-06-19',
    'place': {'city': {'en': 'Copenhagen',
      'no': 'København',
      'se': 'Köpenhamn'},
     'country': {'en': 'Denmark', 'no': 'Danmark', 'se': 'Danmark'},
     'cityNow': {'en': 'Copenhagen',
      'no': 'København',
      'se': 'Köpenhamn',
      'sameAs': ['https://www.wikidata.org/wiki/Q1748',
       'https://www.wikipedia.org/wiki/Copenhagen'],
      'latitude': '55.678127',
      'longitude': '12.572532'},
     'countryNow': {'en': 'Denmark',
      'no': 'Danmark',
      'se': 'Danmark',
      'sameAs': ['https://www.wikidata.org/wiki/Q35'],
      'latitude': '56.000000',
      'longitude': '10.000000'},
     'continent': {'en': 'Europe', 'no': 'Europa', 'se': 'Europa'},
     'locationString': {'en': 'Copenhagen, Denmark',
      'no': 'København, Danmark',
      'se': 'Köpenhamn, Danmark'}}},
   'death': {'date': '2009-09-08',
    'place': {'city': {'en': 'Copenhagen',
      'no': 'København',
      'se': 'Köpenhamn'},
     'country': {'en': 'Denmark',
      'no': 'Danmark',
      'se': 'Danmark',
      'sameAs': 'https://www.wikidata.org/wiki/Q35'},
     'cityNow': {'en': 'Copenhagen',
      'no': 'København',
      'se': 'Köpenhamn',
      'sameAs': ['https://www.wikidata.org/wiki/Q1748',
       'https://www.wikipedia.org/wiki/Copenhagen'],
      'latitude': '55.678127',
      'longitude': '12.572532'},
     'countryNow': {'en': 'Denmark',
      'no': 'Danmark',
      'se': 'Danmark',
      'sameAs': ['https://www.wikidata.org/wiki/Q35'],
      'latitude': '56.000000',
      'longitude': '10.000000'},
     'continent': {'en': 'Europe', 'no': 'Europa', 'se': 'Europa'},
     'locationString': {'en': 'Copenhagen, Denmark',
      'no': 'København, Danmark',
      'se': 'Köpenhamn, Danmark'}}},
   'wikipedia': {'slug': 'Aage_Bohr',
    'english': 'https://en.wikipedia.org/wiki/Aage_Bohr'},
   'wikidata': {'id': 'Q103854',
    'url': 'https://www.wikidata.org/wiki/Q103854'},
   'sameAs': ['https://www.wikidata.org/wiki/Q103854',
    'https://en.wikipedia.org/wiki/Aage_Bohr'],
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/102',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/laureate/102',
     'title': 'Aage N. Bohr - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']}],
   'nobelPrizes': [{'awardYear': '1975',
     'category': {'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'},
     'categoryFullName': {'en': 'The Nobel Prize in Physics',
      'no': 'Nobelprisen i fysikk',
      'se': 'Nobelpriset i fysik'},
     'sortOrder': '1',
     'portion': '1/3',
     'dateAwarded': '1975-10-17',
     'prizeStatus': 'received',
     'motivation': {'en': 'for the discovery of the connection between collective motion and particle motion in atomic nuclei and the development of the theory of the structure of the atomic nucleus based on this connection',
      'se': 'för upptäckten av sambandet mellan kollektiva rörelser och partikelrörelser i atomkärnor, samt den därpå baserade utvecklingen av teorien för atomkärnans struktur'},
     'prizeAmount': 630000,
     'prizeAmountAdjusted': 4304697,
     'affiliations': [{'name': {'en': 'Niels Bohr Institute',
        'no': 'Niels Bohr Institute',
        'se': 'Niels Bohr Institute'},
       'nameNow': {'en': 'Niels Bohr Institute'},
       'city': {'en': 'Copenhagen', 'no': 'København', 'se': 'Köpenhamn'},
       'country': {'en': 'Denmark', 'no': 'Danmark', 'se': 'Danmark'},
       'cityNow': {'en': 'Copenhagen',
        'no': 'København',
        'se': 'Köpenhamn',
        'sameAs': ['https://www.wikidata.org/wiki/Q1748',
         'https://www.wikipedia.org/wiki/Copenhagen'],
        'latitude': '55.678127',
        'longitude': '12.572532'},
       'countryNow': {'en': 'Denmark',
        'no': 'Danmark',
        'se': 'Danmark',
        'sameAs': ['https://www.wikidata.org/wiki/Q35'],
        'latitude': '56.000000',
        'longitude': '10.000000'},
       'continent': {'en': 'Europe'},
       'locationString': {'en': 'Copenhagen, Denmark',
        'no': 'København, Danmark',
        'se': 'Köpenhamn, Danmark'}}],
     'links': [{'rel': 'nobelPrize',
       'href': 'https://api.nobelprize.org/2/nobelPrize/phy/1975',
       'action': 'GET',
       'types': 'application/json'},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/physics/1975/bohr/facts/',
       'title': 'Aage N. Bohr - Facts',
       'action': 'GET',
       'types': 'text/html',
       'class': ['laureate facts']},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/physics/1975/summary/',
       'title': 'The Nobel Prize in Physics 1975',
       'action': 'GET',
       'types': 'text/html',
       'class': ['prize summary']}]}]},
  {'id': '779',
   'knownName': {'en': 'Aaron Ciechanover', 'se': 'Aaron Ciechanover'},
   'givenName': {'en': 'Aaron', 'se': 'Aaron'},
   'familyName': {'en': 'Ciechanover', 'se': 'Ciechanover'},
   'fullName': {'en': 'Aaron Ciechanover', 'se': 'Aaron Ciechanover'},
   'fileName': 'ciechanover',
   'gender': 'male',
   'birth': {'date': '1947-10-01',
    'place': {'city': {'en': 'Haifa', 'no': 'Haifa', 'se': 'Haifa'},
     'country': {'en': 'British Protectorate of Palestine',
      'no': 'British i Palestina',
      'se': 'British Protectorate of Palestine'},
     'cityNow': {'en': 'Haifa',
      'no': 'Haifa',
      'se': 'Haifa',
      'sameAs': ['https://www.wikidata.org/wiki/Q41621',
       'https://www.wikipedia.org/wiki/Haifa'],
      'latitude': '32.794421',
      'longitude': '34.990340'},
     'countryNow': {'en': 'Israel',
      'no': 'Israel',
      'se': 'Israel',
      'sameAs': ['https://www.wikidata.org/wiki/Q801'],
      'latitude': '31.000000',
      'longitude': '35.000000'},
     'continent': {'en': 'Asia', 'no': 'Asia', 'se': 'Asien'},
     'locationString': {'en': 'Haifa, British Protectorate of Palestine (now Israel)',
      'no': 'Haifa, British i Palestina (nå Israel)',
      'se': 'Haifa, British Protectorate of Palestine (nu Israel)'}}},
   'wikipedia': {'slug': 'Aaron_Ciechanover',
    'english': 'https://en.wikipedia.org/wiki/Aaron_Ciechanover'},
   'wikidata': {'id': 'Q233205',
    'url': 'https://www.wikidata.org/wiki/Q233205'},
   'sameAs': ['https://www.wikidata.org/wiki/Q233205',
    'https://en.wikipedia.org/wiki/Aaron_Ciechanover'],
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/779',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/laureate/779',
     'title': 'Aaron Ciechanover - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']}],
   'nobelPrizes': [{'awardYear': '2004',
     'category': {'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'},
     'categoryFullName': {'en': 'The Nobel Prize in Chemistry',
      'no': 'Nobelprisen i kjemi',
      'se': 'Nobelpriset i kemi'},
     'sortOrder': '1',
     'portion': '1/3',
     'dateAwarded': '2004-10-06',
     'prizeStatus': 'received',
     'motivation': {'en': 'for the discovery of ubiquitin-mediated protein degradation',
      'se': 'för upptäckten av ubiquitinmedierad proteinnedbrytning'},
     'prizeAmount': 10000000,
     'prizeAmountAdjusted': 14874529,
     'affiliations': [{'name': {'en': 'Technion - Israel Institute of Technology',
        'no': 'Technion - Israel Institute of Technology',
        'se': 'Technion - Israel Institute of Technology'},
       'nameNow': {'en': 'Technion - Israel Institute of Technology'},
       'city': {'en': 'Haifa', 'no': 'Haifa', 'se': 'Haifa'},
       'country': {'en': 'Israel', 'no': 'Israel', 'se': 'Israel'},
       'cityNow': {'en': 'Haifa',
        'no': 'Haifa',
        'se': 'Haifa',
        'sameAs': ['https://www.wikidata.org/wiki/Q41621',
         'https://www.wikipedia.org/wiki/Haifa'],
        'latitude': '32.794421',
        'longitude': '34.990340'},
       'countryNow': {'en': 'Israel',
        'no': 'Israel',
        'se': 'Israel',
        'sameAs': ['https://www.wikidata.org/wiki/Q801'],
        'latitude': '31.000000',
        'longitude': '35.000000'},
       'continent': {'en': 'Asia'},
       'locationString': {'en': 'Haifa, Israel',
        'no': 'Haifa, Israel',
        'se': 'Haifa, Israel'}}],
     'links': [{'rel': 'nobelPrize',
       'href': 'https://api.nobelprize.org/2/nobelPrize/che/2004',
       'action': 'GET',
       'types': 'application/json'},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/chemistry/2004/ciechanover/facts/',
       'title': 'Aaron Ciechanover - Facts',
       'action': 'GET',
       'types': 'text/html',
       'class': ['laureate facts']},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/chemistry/2004/summary/',
       'title': 'The Nobel Prize in Chemistry 2004',
       'action': 'GET',
       'types': 'text/html',
       'class': ['prize summary']}]}]},
  {'id': '259',
   'knownName': {'en': 'Aaron Klug', 'se': 'Aaron Klug'},
   'givenName': {'en': 'Aaron', 'se': 'Aaron'},
   'familyName': {'en': 'Klug', 'se': 'Klug'},
   'fullName': {'en': 'Aaron Klug', 'se': 'Aaron Klug'},
   'fileName': 'klug',
   'gender': 'male',
   'birth': {'date': '1926-08-11',
    'place': {'city': {'en': 'Zelvas', 'no': 'Zelvas', 'se': 'Zelvas'},
     'country': {'en': 'Lithuania', 'no': 'Litauen', 'se': 'Litauen'},
     'cityNow': {'en': 'Zelvas',
      'no': 'Zelvas',
      'se': 'Zelvas',
      'sameAs': ['https://www.wikidata.org/wiki/Q691679',
       'https://www.wikipedia.org/wiki/%C5%BDelva'],
      'latitude': '53.148256',
      'longitude': '24.816515'},
     'countryNow': {'en': 'Lithuania',
      'no': 'Litauen',
      'se': 'Litauen',
      'sameAs': ['https://www.wikidata.org/wiki/Q37'],
      'latitude': '55.200000',
      'longitude': '24.000000'},
     'continent': {'en': 'Europe', 'no': 'Europa', 'se': 'Europa'},
     'locationString': {'en': 'Zelvas, Lithuania',
      'no': 'Zelvas, Litauen',
      'se': 'Zelvas, Litauen'}}},
   'death': {'date': '2018-11-20',
    'place': {'locationString': {'en': '', 'no': '', 'se': ''}}},
   'wikipedia': {'slug': 'Aaron_Klug',
    'english': 'https://en.wikipedia.org/wiki/Aaron_Klug'},
   'wikidata': {'id': 'Q190626',
    'url': 'https://www.wikidata.org/wiki/Q190626'},
   'sameAs': ['https://www.wikidata.org/wiki/Q190626',
    'https://en.wikipedia.org/wiki/Aaron_Klug'],
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/259',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/laureate/259',
     'title': 'Aaron Klug - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']}],
   'nobelPrizes': [{'awardYear': '1982',
     'category': {'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'},
     'categoryFullName': {'en': 'The Nobel Prize in Chemistry',
      'no': 'Nobelprisen i kjemi',
      'se': 'Nobelpriset i kemi'},
     'sortOrder': '1',
     'portion': '1',
     'dateAwarded': '1982-10-18',
     'prizeStatus': 'received',
     'motivation': {'en': 'for his development of crystallographic electron microscopy and his structural elucidation of biologically important nucleic acid-protein complexes',
      'se': 'för hans utveckling av kristallografisk elektronmikroskopi och hans klarläggande av strukturen hos biologiskt viktiga nukleinsyra-proteinkomplex'},
     'prizeAmount': 1150000,
     'prizeAmountAdjusted': 3923237,
     'affiliations': [{'name': {'en': 'MRC Laboratory of Molecular Biology',
        'no': 'MRC Laboratory of Molecular Biology',
        'se': 'MRC Laboratory of Molecular Biology'},
       'nameNow': {'en': 'MRC Laboratory of Molecular Biology'},
       'city': {'en': 'Cambridge', 'no': 'Cambridge', 'se': 'Cambridge'},
       'country': {'en': 'United Kingdom',
        'no': 'Storbritannia',
        'se': 'Storbritannien'},
       'cityNow': {'en': 'Cambridge',
        'no': 'Cambridge',
        'se': 'Cambridge',
        'sameAs': ['https://www.wikidata.org/wiki/Q350',
         'https://www.wikipedia.org/wiki/Cambridge'],
        'latitude': '52.194605',
        'longitude': '0.135092'},
       'countryNow': {'en': 'United Kingdom',
        'no': 'Storbritannia',
        'se': 'Storbritannien',
        'sameAs': ['https://www.wikidata.org/wiki/Q145'],
        'latitude': '54.600000',
        'longitude': '-2.000000'},
       'continent': {'en': 'Europe'},
       'locationString': {'en': 'Cambridge, United Kingdom',
        'no': 'Cambridge, Storbritannia',
        'se': 'Cambridge, Storbritannien'}}],
     'links': [{'rel': 'nobelPrize',
       'href': 'https://api.nobelprize.org/2/nobelPrize/che/1982',
       'action': 'GET',
       'types': 'application/json'},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/chemistry/1982/klug/facts/',
       'title': 'Aaron Klug - Facts',
       'action': 'GET',
       'types': 'text/html',
       'class': ['laureate facts']},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/chemistry/1982/summary/',
       'title': 'The Nobel Prize in Chemistry 1982',
       'action': 'GET',
       'types': 'text/html',
       'class': ['prize summary']}]}]},
  {'id': '1004',
   'knownName': {'en': 'Abdulrazak Gurnah', 'se': 'Abdulrazak Gurnah'},
   'givenName': {'en': 'Abdulrazak', 'se': 'Abdulrazak'},
   'familyName': {'en': 'Gurnah', 'se': 'Gurnah'},
   'fullName': {'en': 'Abdulrazak Gurnah', 'se': 'Abdulrazak Gurnah'},
   'fileName': 'gurnah',
   'gender': 'male',
   'birth': {'date': '1948-00-00'},
   'wikipedia': {'slug': 'Abdulrazak_Gurnah',
    'english': 'https://en.wikipedia.org/wiki/Abdulrazak_Gurnah'},
   'wikidata': {'id': 'Q317877',
    'url': 'https://www.wikidata.org/wiki/Q317877'},
   'sameAs': ['https://www.wikidata.org/wiki/Q317877',
    'https://en.wikipedia.org/wiki/Abdulrazak_Gurnah'],
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/1004',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/laureate/1004',
     'title': 'Abdulrazak Gurnah - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']}],
   'nobelPrizes': [{'awardYear': '2021',
     'category': {'en': 'Literature', 'no': 'Litteratur', 'se': 'Litteratur'},
     'categoryFullName': {'en': 'The Nobel Prize in Literature',
      'no': 'Nobelprisen i litteratur',
      'se': 'Nobelpriset i litteratur'},
     'sortOrder': '1',
     'portion': '1',
     'dateAwarded': '2021-10-07',
     'prizeStatus': 'received',
     'motivation': {'en': 'for his uncompromising and compassionate penetration of the effects of colonialism and the fate of the refugee in the gulf between cultures and continents'},
     'prizeAmount': 10000000,
     'prizeAmountAdjusted': 12096939,
     'links': [{'rel': 'nobelPrize',
       'href': 'https://api.nobelprize.org/2/nobelPrize/lit/2021',
       'action': 'GET',
       'types': 'application/json'},
      {'rel': 'external',
       'href': 'https://www.nobelprize.org/prizes/literature/2021/gurnah/facts/',

In [43]:
data['laureates'][0]

{'id': '745',
 'knownName': {'en': 'A. Michael Spence', 'se': 'A. Michael Spence'},
 'givenName': {'en': 'A. Michael', 'se': 'A. Michael'},
 'familyName': {'en': 'Spence', 'se': 'Spence'},
 'fullName': {'en': 'A. Michael Spence', 'se': 'A. Michael Spence'},
 'fileName': 'spence',
 'gender': 'male',
 'birth': {'date': '1943-00-00',
  'place': {'city': {'en': 'Montclair, NJ',
    'no': 'Montclair, NJ',
    'se': 'Montclair, NJ'},
   'country': {'en': 'USA', 'no': 'USA', 'se': 'USA'},
   'cityNow': {'en': 'Montclair, NJ',
    'no': 'Montclair, NJ',
    'se': 'Montclair, NJ',
    'sameAs': ['https://www.wikidata.org/wiki/Q678437',
     'https://www.wikipedia.org/wiki/Montclair,_New_Jersey'],
    'latitude': '40.825930',
    'longitude': '-74.209030'},
   'countryNow': {'en': 'USA',
    'no': 'USA',
    'se': 'USA',
    'sameAs': ['https://www.wikidata.org/wiki/Q30'],
    'latitude': '39.828175',
    'longitude': '-98.579500'},
   'continent': {'en': 'North America',
    'no': 'Nord-Amerika',
    'se': 'Nordamerika'},
   'locationString': {'en': 'Montclair, NJ, USA',
    'no': 'Montclair, NJ, USA',
    'se': 'Montclair, NJ, USA'}}},
 'wikipedia': {'slug': 'Michael_Spence',
  'english': 'https://en.wikipedia.org/wiki/Michael_Spence'},
 'wikidata': {'id': 'Q157245', 'url': 'https://www.wikidata.org/wiki/Q157245'},
 'sameAs': ['https://www.wikidata.org/wiki/Q157245',
  'https://en.wikipedia.org/wiki/Michael_Spence'],
 'links': [{'rel': 'laureate',
   'href': 'https://api.nobelprize.org/2/laureate/745',
   'action': 'GET',
   'types': 'application/json'},
  {'rel': 'external',
   'href': 'https://www.nobelprize.org/laureate/745',
   'title': 'A. Michael Spence - Facts',
   'action': 'GET',
   'types': 'text/html',
   'class': ['laureate facts']}],
 'nobelPrizes': [{'awardYear': '2001',
   'category': {'en': 'Economic Sciences', 'no': 'Økonomi', 'se': 'Ekonomi'},
   'categoryFullName': {'en': 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel',
    'no': 'Sveriges Riksbanks pris i økonomisk vitenskap til minne om Alfred Nobel',
    'se': 'Sveriges Riksbanks pris i ekonomisk vetenskap till Alfred Nobels minne'},
   'sortOrder': '2',
   'portion': '1/3',
   'dateAwarded': '2001-10-10',
   'prizeStatus': 'received',
   'motivation': {'en': 'for their analyses of markets with asymmetric information',
    'se': 'för deras analys av marknader med assymetrisk informations'},
   'prizeAmount': 10000000,
   'prizeAmountAdjusted': 15547541,
   'affiliations': [{'name': {'en': 'Stanford University',
      'no': 'Stanford University',
      'se': 'Stanford University'},
     'nameNow': {'en': 'Stanford University'},
     'city': {'en': 'Stanford, CA',
      'no': 'Stanford, CA',
      'se': 'Stanford, CA'},
     'country': {'en': 'USA', 'no': 'USA', 'se': 'USA'},
     'cityNow': {'en': 'Stanford, CA',
      'no': 'Stanford, CA',
      'se': 'Stanford, CA',
      'sameAs': ['https://www.wikidata.org/wiki/Q173813',
       'https://www.wikipedia.org/wiki/Stanford,_California'],
      'latitude': '37.424734',
      'longitude': '-122.163858'},
     'countryNow': {'en': 'USA',
      'no': 'USA',
      'se': 'USA',
      'sameAs': ['https://www.wikidata.org/wiki/Q30'],
      'latitude': '39.828175',
      'longitude': '-98.579500'},
     'continent': {'en': 'North America'},
     'locationString': {'en': 'Stanford, CA, USA',
      'no': 'Stanford, CA, USA',
      'se': 'Stanford, CA, USA'}}],
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/eco/2001',
     'action': 'GET',
     'types': 'application/json'},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/prizes/economic-sciences/2001/spence/facts/',
     'title': 'A. Michael Spence - Facts',
     'action': 'GET',
     'types': 'text/html',
     'class': ['laureate facts']},
    {'rel': 'external',
     'href': 'https://www.nobelprize.org/prizes/economic-sciences/2001/summary/',
     'title': 'The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel 2001',
     'action': 'GET',
     'types': 'text/html',
     'class': ['prize summary']}]}]}

In [44]:
# URL API для получения данных о Нобелевских премиях
url = "https://api.nobelprize.org/2.1/nobelPrizes"

# Параметры запроса (можно указать год или категорию)
params = {
    "format": "json"
}

# Отправка запроса
response = requests.get(url, params=params)
data = response.json()
data

{'nobelPrizes': [{'awardYear': '1901',
   'category': {'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'},
   'categoryFullName': {'en': 'The Nobel Prize in Chemistry',
    'no': 'Nobelprisen i kjemi',
    'se': 'Nobelpriset i kemi'},
   'dateAwarded': '1901-11-12',
   'prizeAmount': 150782,
   'prizeAmountAdjusted': 10833458,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/che/1901',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '160',
     'knownName': {'en': "Jacobus H. van 't Hoff"},
     'fullName': {'en': "Jacobus Henricus van 't Hoff"},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary services he has rendered by the discovery of the laws of chemical dynamics and osmotic pressure in solutions',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst han inlagt genom upptäckten av lagarna för den kemiska dynamiken och för det osmotiska trycket i lösningar'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/160',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1901',
   'category': {'en': 'Literature', 'no': 'Litteratur', 'se': 'Litteratur'},
   'categoryFullName': {'en': 'The Nobel Prize in Literature',
    'no': 'Nobelprisen i litteratur',
    'se': 'Nobelpriset i litteratur'},
   'dateAwarded': '1901-11-14',
   'prizeAmount': 150782,
   'prizeAmountAdjusted': 10833458,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/lit/1901',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '569',
     'knownName': {'en': 'Sully Prudhomme'},
     'fullName': {'en': 'Sully Prudhomme'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'in special recognition of his poetic composition, which gives evidence of lofty idealism, artistic perfection and a rare combination of the qualities of both heart and intellect',
      'se': 'såsom ett erkännande av hans utmärkta, jämväl under senare år ådagalagda förtjänster som författare och särskilt av hans om hög idealitet, konstnärlig fulländning samt sällspord förening av hjärtats och snillets egenskaper vittnande diktning'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/569',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1901',
   'category': {'en': 'Peace', 'no': 'Fred', 'se': 'Fred'},
   'categoryFullName': {'en': 'The Nobel Peace Prize',
    'no': 'Nobels fredspris',
    'se': 'Nobels fredspris'},
   'dateAwarded': '1901-12-10',
   'prizeAmount': 150782,
   'prizeAmountAdjusted': 10833458,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/pea/1901',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '462',
     'knownName': {'en': 'Henry Dunant'},
     'fullName': {'en': 'Jean Henry Dunant'},
     'portion': '1/2',
     'sortOrder': '1',
     'motivation': {'en': 'for his humanitarian efforts to help wounded soldiers and create international understanding',
      'no': 'for sin humanitære innsats for å hjelpe sårede soldater og skape internasjonal forståelse'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/462',
       'action': 'GET',
       'types': 'application/json'}]},
    {'id': '463',
     'knownName': {'en': 'Frédéric Passy'},
     'fullName': {'en': 'Frédéric Passy'},
     'portion': '1/2',
     'sortOrder': '2',
     'motivation': {'en': 'for his lifelong work for international peace conferences, diplomacy and arbitration',
      'no': 'for sin  livslange innsats for internasjonale fredskonferanser, diplomati og voldgift'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/463',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1901',
   'category': {'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'},
   'categoryFullName': {'en': 'The Nobel Prize in Physics',
    'no': 'Nobelprisen i fysikk',
    'se': 'Nobelpriset i fysik'},
   'dateAwarded': '1901-11-12',
   'prizeAmount': 150782,
   'prizeAmountAdjusted': 10833458,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/phy/1901',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '1',
     'knownName': {'en': 'Wilhelm Conrad Röntgen'},
     'fullName': {'en': 'Wilhelm Conrad Röntgen'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary services he has rendered by the discovery of the remarkable rays subsequently named after him',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst han inlagt genom upptäckten av de egendomliga strålar, som sedermera uppkallats efter honom'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/1',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1901',
   'category': {'en': 'Physiology or Medicine',
    'no': 'Fysiologi eller medisin',
    'se': 'Fysiologi eller medicin'},
   'categoryFullName': {'en': 'The Nobel Prize in Physiology or Medicine',
    'no': 'Nobelprisen i fysiologi eller medisin',
    'se': 'Nobelpriset i fysiologi eller medicin'},
   'dateAwarded': '1901-10-30',
   'prizeAmount': 150782,
   'prizeAmountAdjusted': 10833458,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/med/1901',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '293',
     'knownName': {'en': 'Emil von Behring'},
     'fullName': {'en': 'Emil Adolf von Behring'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'for his work on serum therapy, especially its application against diphtheria, by which he has opened a new road in the domain of medical science and thereby placed in the hands of the physician a victorious weapon against illness and deaths',
      'se': 'för hans arbete rörande serumterapien och särskilt dess användning mot difteri, varigenom han brutit en ny väg inom den medicinska vetenskapens område och givit läkaren ett segerrikt vapen i kampen mot sjukdom och död'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/293',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1902',
   'category': {'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'},
   'categoryFullName': {'en': 'The Nobel Prize in Chemistry',
    'no': 'Nobelprisen i kjemi',
    'se': 'Nobelpriset i kemi'},
   'dateAwarded': '1902-11-11',
   'prizeAmount': 141847,
   'prizeAmountAdjusted': 10191492,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/che/1902',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '161',
     'knownName': {'en': 'Emil Fischer'},
     'fullName': {'en': 'Hermann Emil Fischer'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary services he has rendered by his work on sugar and purine syntheses',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst han inlagt genom sina syntetiska arbeten inom socker - och purin-grupperna'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/161',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1902',
   'category': {'en': 'Literature', 'no': 'Litteratur', 'se': 'Litteratur'},
   'categoryFullName': {'en': 'The Nobel Prize in Literature',
    'no': 'Nobelprisen i litteratur',
    'se': 'Nobelpriset i litteratur'},
   'dateAwarded': '1902-11-13',
   'prizeAmount': 141847,
   'prizeAmountAdjusted': 10191492,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/lit/1902',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '571',
     'knownName': {'en': 'Theodor Mommsen'},
     'fullName': {'en': 'Christian Matthias Theodor Mommsen'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'the greatest living master of the art of historical writing, with special reference to his monumental work, <I>A history of Rome</I>',
      'se': 'nutidens störste levande mästare i den historiska framställningens konst, med särskilt fäst avseende å hans monumentala verk Römische Geschichte'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/571',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1902',
   'category': {'en': 'Peace', 'no': 'Fred', 'se': 'Fred'},
   'categoryFullName': {'en': 'The Nobel Peace Prize',
    'no': 'Nobels fredspris',
    'se': 'Nobels fredspris'},
   'dateAwarded': '1902-12-10',
   'prizeAmount': 141847,
   'prizeAmountAdjusted': 10191492,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/pea/1902',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '464',
     'knownName': {'en': 'Élie Ducommun'},
     'fullName': {'en': 'Élie Ducommun'},
     'portion': '1/2',
     'sortOrder': '1',
     'motivation': {'en': 'for his untiring and skilful directorship of the Bern Peace Bureau',
      'no': 'for sin utrettelige og dyktige ledelse av Det internasjonale fredsbyrået i Bern'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/464',
       'action': 'GET',
       'types': 'application/json'}]},
    {'id': '465',
     'knownName': {'en': 'Albert Gobat'},
     'fullName': {'en': 'Charles Albert Gobat'},
     'portion': '1/2',
     'sortOrder': '2',
     'motivation': {'en': 'for his eminently practical administration of the Inter-Parliamentary Union',
      'no': 'for sin fremragende praktiske administrering av Den interparlamentariske union'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/465',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1902',
   'category': {'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'},
   'categoryFullName': {'en': 'The Nobel Prize in Physics',
    'no': 'Nobelprisen i fysikk',
    'se': 'Nobelpriset i fysik'},
   'dateAwarded': '1902-11-11',
   'prizeAmount': 141847,
   'prizeAmountAdjusted': 10191492,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/phy/1902',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '2',
     'knownName': {'en': 'Hendrik A. Lorentz'},
     'fullName': {'en': 'Hendrik Antoon Lorentz'},
     'portion': '1/2',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary service they rendered by their researches into the influence of magnetism upon radiation phenomena',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst de inlagt genom sina undersökningar över magnetismens inflytande på strålningsfenomenen'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/2',
       'action': 'GET',
       'types': 'application/json'}]},
    {'id': '3',
     'knownName': {'en': 'Pieter Zeeman'},
     'fullName': {'en': 'Pieter Zeeman'},
     'portion': '1/2',
     'sortOrder': '2',
     'motivation': {'en': 'in recognition of the extraordinary service they rendered by their researches into the influence of magnetism upon radiation phenomena',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst de inlagt genom sina undersökningar över magnetismens inflytande på strålningsfenomenen'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/3',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1902',
   'category': {'en': 'Physiology or Medicine',
    'no': 'Fysiologi eller medisin',
    'se': 'Fysiologi eller medicin'},
   'categoryFullName': {'en': 'The Nobel Prize in Physiology or Medicine',
    'no': 'Nobelprisen i fysiologi eller medisin',
    'se': 'Nobelpriset i fysiologi eller medicin'},
   'dateAwarded': '1902-10-30',
   'prizeAmount': 141847,
   'prizeAmountAdjusted': 10191492,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/med/1902',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '294',
     'knownName': {'en': 'Ronald Ross'},
     'fullName': {'en': 'Ronald Ross'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'for his work on malaria, by which he has shown how it enters the organism and thereby has laid the foundation for successful research on this disease and methods of combating it',
      'se': 'för hans arbete rörande malarian, varigenom han uppdagat det sätt, varpå densamma vinner insteg i organismen, och därmed lagt grunden för betydelsefulla forskningar angående denna sjukdom och dess bekämpande'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/294',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1903',
   'category': {'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'},
   'categoryFullName': {'en': 'The Nobel Prize in Chemistry',
    'no': 'Nobelprisen i kjemi',
    'se': 'Nobelpriset i kemi'},
   'dateAwarded': '1903-11-12',
   'prizeAmount': 141358,
   'prizeAmountAdjusted': 9857642,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/che/1903',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '162',
     'knownName': {'en': 'Svante Arrhenius'},
     'fullName': {'en': 'Svante August Arrhenius'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary services he has rendered to the advancement of chemistry by his electrolytic theory of dissociation',
      'se': 'såsom ett erkännande för den utomordentliga förtjänst han genom sin elektrolytiska dissociations-teori inlagt om kemiens utveckling'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/162',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1903',
   'category': {'en': 'Literature', 'no': 'Litteratur', 'se': 'Litteratur'},
   'categoryFullName': {'en': 'The Nobel Prize in Literature',
    'no': 'Nobelprisen i litteratur',
    'se': 'Nobelpriset i litteratur'},
   'dateAwarded': '1903-11-19',
   'prizeAmount': 141358,
   'prizeAmountAdjusted': 9857642,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/lit/1903',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '572',
     'knownName': {'en': 'Bjørnstjerne Bjørnson'},
     'fullName': {'en': 'Bjørnstjerne Martinus Bjørnson'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'as a tribute to his noble, magnificent and versatile poetry, which has always been distinguished by both the freshness of its inspiration and the rare purity of its spirit',
      'se': 'såsom en gärd av erkännande åt hans ädla, storartade och mångsidiga skaldeverksamhet, som alltid varit utmärkt på en gång av ingivelsens friskhet och av en sällsynt själsrenhet'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/572',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1903',
   'category': {'en': 'Peace', 'no': 'Fred', 'se': 'Fred'},
   'categoryFullName': {'en': 'The Nobel Peace Prize',
    'no': 'Nobels fredspris',
    'se': 'Nobels fredspris'},
   'dateAwarded': '1903-12-10',
   'prizeAmount': 141358,
   'prizeAmountAdjusted': 9857642,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/pea/1903',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '466',
     'knownName': {'en': 'Randal Cremer'},
     'fullName': {'en': 'William Randal Cremer'},
     'portion': '1',
     'sortOrder': '1',
     'motivation': {'en': 'for his longstanding and devoted effort in favour of the ideas of peace and arbitration',
      'no': 'for sin lange og oppofrende innsats for å fremme ideen om fred og voldgift'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/466',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1903',
   'category': {'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'},
   'categoryFullName': {'en': 'The Nobel Prize in Physics',
    'no': 'Nobelprisen i fysikk',
    'se': 'Nobelpriset i fysik'},
   'dateAwarded': '1903-11-12',
   'prizeAmount': 141358,
   'prizeAmountAdjusted': 9857642,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/phy/1903',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '4',
     'knownName': {'en': 'Henri Becquerel'},
     'fullName': {'en': 'Antoine Henri Becquerel'},
     'portion': '1/2',
     'sortOrder': '1',
     'motivation': {'en': 'in recognition of the extraordinary services he has rendered by his discovery of spontaneous radioactivity',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst han inlagt genom upptäckten av den spontana radioaktiviteten'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/4',
       'action': 'GET',
       'types': 'application/json'}]},
    {'id': '5',
     'knownName': {'en': 'Pierre Curie'},
     'fullName': {'en': 'Pierre Curie'},
     'portion': '1/4',
     'sortOrder': '2',
     'motivation': {'en': 'in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst de inlagt genom sina gemensamt utförda arbeten rörande de av Professor Henri Becquerel upptäckta strålningsfenomenen'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/5',
       'action': 'GET',
       'types': 'application/json'}]},
    {'id': '6',
     'knownName': {'en': 'Marie Curie'},
     'fullName': {'en': 'Marie Curie, née Skłodowska'},
     'portion': '1/4',
     'sortOrder': '3',
     'motivation': {'en': 'in recognition of the extraordinary services they have rendered by their joint researches on the radiation phenomena discovered by Professor Henri Becquerel',
      'se': 'såsom ett erkännande av den utomordentliga förtjänst de inlagt genom sina gemensamt utförda arbeten rörande de av Professor Henri Becquerel upptäckta strålningsfenomenen'},
     'links': [{'rel': 'laureate',
       'href': 'https://api.nobelprize.org/2/laureate/6',
       'action': 'GET',
       'types': 'application/json'}]}]},
  {'awardYear': '1903',
   'category': {'en': 'Physiology or Medicine',
    'no': 'Fysiologi eller medisin',
    'se': 'Fysiologi eller medicin'},
   'categoryFullName': {'en': 'The Nobel Prize in Physiology or Medicine',
    'no': 'Nobelprisen i fysiologi eller medisin',
    'se': 'Nobelpriset i fysiologi eller medicin'},
   'dateAwarded': '1903-10-15',
   'prizeAmount': 141358,
   'prizeAmountAdjusted': 9857642,
   'links': [{'rel': 'nobelPrize',
     'href': 'https://api.nobelprize.org/2/nobelPrize/med/1903',
     'action': 'GET',
     'types': 'application/json'}],
   'laureates': [{'id': '295',
     'knownName': {'en': 'Niels Ryberg Finsen'},
     'fullName': {'en': 'Niels Ryberg Finsen'},
     'portion': '1',
     'sortOrder': '1',

In [45]:
data.keys()

dict_keys(['nobelPrizes', 'meta', 'links'])

In [46]:
pd.DataFrame(data['nobelPrizes'])

,awardYear,category,categoryFullName,dateAwarded,prizeAmount,prizeAmountAdjusted,links,laureates
0,1901,"{'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'}","{'en': 'The Nobel Prize in Chemistry', 'no': '...",1901-11-12,150782,10833458,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '160', 'knownName': {'en': 'Jacobus H...."
1,1901,"{'en': 'Literature', 'no': 'Litteratur', 'se':...","{'en': 'The Nobel Prize in Literature', 'no': ...",1901-11-14,150782,10833458,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '569', 'knownName': {'en': 'Sully Prud..."
2,1901,"{'en': 'Peace', 'no': 'Fred', 'se': 'Fred'}","{'en': 'The Nobel Peace Prize', 'no': 'Nobels ...",1901-12-10,150782,10833458,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '462', 'knownName': {'en': 'Henry Duna..."
3,1901,"{'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'}","{'en': 'The Nobel Prize in Physics', 'no': 'No...",1901-11-12,150782,10833458,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '1', 'knownName': {'en': 'Wilhelm Conr..."
4,1901,"{'en': 'Physiology or Medicine', 'no': 'Fysiol...",{'en': 'The Nobel Prize in Physiology or Medic...,1901-10-30,150782,10833458,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '293', 'knownName': {'en': 'Emil von B..."
5,1902,"{'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'}","{'en': 'The Nobel Prize in Chemistry', 'no': '...",1902-11-11,141847,10191492,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '161', 'knownName': {'en': 'Emil Fisch..."
6,1902,"{'en': 'Literature', 'no': 'Litteratur', 'se':...","{'en': 'The Nobel Prize in Literature', 'no': ...",1902-11-13,141847,10191492,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '571', 'knownName': {'en': 'Theodor Mo..."
7,1902,"{'en': 'Peace', 'no': 'Fred', 'se': 'Fred'}","{'en': 'The Nobel Peace Prize', 'no': 'Nobels ...",1902-12-10,141847,10191492,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '464', 'knownName': {'en': 'Élie Ducom..."
8,1902,"{'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'}","{'en': 'The Nobel Prize in Physics', 'no': 'No...",1902-11-11,141847,10191492,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '2', 'knownName': {'en': 'Hendrik A. L..."
9,1902,"{'en': 'Physiology or Medicine', 'no': 'Fysiol...",{'en': 'The Nobel Prize in Physiology or Medic...,1902-10-30,141847,10191492,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '294', 'knownName': {'en': 'Ronald Ros..."
10,1903,"{'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'}","{'en': 'The Nobel Prize in Chemistry', 'no': '...",1903-11-12,141358,9857642,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '162', 'knownName': {'en': 'Svante Arr..."
11,1903,"{'en': 'Literature', 'no': 'Litteratur', 'se':...","{'en': 'The Nobel Prize in Literature', 'no': ...",1903-11-19,141358,9857642,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '572', 'knownName': {'en': 'Bjørnstjer..."
12,1903,"{'en': 'Peace', 'no': 'Fred', 'se': 'Fred'}","{'en': 'The Nobel Peace Prize', 'no': 'Nobels ...",1903-12-10,141358,9857642,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '466', 'knownName': {'en': 'Randal Cre..."
13,1903,"{'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'}","{'en': 'The Nobel Prize in Physics', 'no': 'No...",1903-11-12,141358,9857642,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '4', 'knownName': {'en': 'Henri Becque..."
14,1903,"{'en': 'Physiology or Medicine', 'no': 'Fysiol...",{'en': 'The Nobel Prize in Physiology or Medic...,1903-10-15,141358,9857642,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '295', 'knownName': {'en': 'Niels Rybe..."
15,1904,"{'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'}","{'en': 'The Nobel Prize in Chemistry', 'no': '...",1904-11-08,140859,9822844,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '163', 'knownName': {'en': 'Sir Willia..."
16,1904,"{'en': 'Literature', 'no': 'Litteratur', 'se':...","{'en': 'The Nobel Prize in Literature', 'no': ...",1904-11-17,140859,9822844,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '573', 'knownName': {'en': 'Frédéric M..."
17,1904,"{'en': 'Peace', 'no': 'Fred', 'se': 'Fred'}","{'en': 'The Nobel Peace Prize', 'no': 'Nobels ...",1904-12-10,140859,9822844,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '467', 'orgName': {'en': 'Institute of..."
18,1904,"{'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'}","{'en': 'The Nobel Prize in Physics', 'no': 'No...",1904-11-08,140859,9822844,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '8', 'knownName': {'en': 'Lord Rayleig..."
19,1904,"{'en': 'Physiology or Medicine', 'no': 'Fysiol...",{'en': 'The Nobel Prize in Physiology or Medic...,1904-10-20,140859,9822844,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '296', 'knownName': {'en': 'Ivan Pavlo..."
20,1905,"{'en': 'Chemistry', 'no': 'Kjemi', 'se': 'Kemi'}","{'en': 'The Nobel Prize in Chemistry', 'no': '...",1905-11-09,138089,9629677,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '164', 'knownName': {'en': 'Adolf von ..."
21,1905,"{'en': 'Literature', 'no': 'Litteratur', 'se':...","{'en': 'The Nobel Prize in Literature', 'no': ...",1905-11-09,138089,9629677,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '575', 'knownName': {'en': 'Henryk Sie..."
22,1905,"{'en': 'Peace', 'no': 'Fred', 'se': 'Fred'}","{'en': 'The Nobel Peace Prize', 'no': 'Nobels ...",1905-12-10,138089,9629677,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '468', 'knownName': {'en': 'Bertha von..."
23,1905,"{'en': 'Physics', 'no': 'Fysikk', 'se': 'Fysik'}","{'en': 'The Nobel Prize in Physics', 'no': 'No...",1905-11-09,138089,9629677,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '9', 'knownName': {'en': 'Philipp Lena..."
24,1905,"{'en': 'Physiology or Medicine', 'no': 'Fysiol...",{'en': 'The Nobel Prize in Physiology or Medic...,1905-10-12,138089,9629677,"[{'rel': 'nobelPrize', 'href': 'https://api.no...","[{'id': '297', 'knownName': {'en': 'Robert Koc..."

In [47]:
data['nobelPrizes'][2]

{'awardYear': '1901',
 'category': {'en': 'Peace', 'no': 'Fred', 'se': 'Fred'},
 'categoryFullName': {'en': 'The Nobel Peace Prize',
  'no': 'Nobels fredspris',
  'se': 'Nobels fredspris'},
 'dateAwarded': '1901-12-10',
 'prizeAmount': 150782,
 'prizeAmountAdjusted': 10833458,
 'links': [{'rel': 'nobelPrize',
   'href': 'https://api.nobelprize.org/2/nobelPrize/pea/1901',
   'action': 'GET',
   'types': 'application/json'}],
 'laureates': [{'id': '462',
   'knownName': {'en': 'Henry Dunant'},
   'fullName': {'en': 'Jean Henry Dunant'},
   'portion': '1/2',
   'sortOrder': '1',
   'motivation': {'en': 'for his humanitarian efforts to help wounded soldiers and create international understanding',
    'no': 'for sin humanitære innsats for å hjelpe sårede soldater og skape internasjonal forståelse'},
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/462',
     'action': 'GET',
     'types': 'application/json'}]},
  {'id': '463',
   'knownName': {'en': 'Frédéric Passy'},
   'fullName': {'en': 'Frédéric Passy'},
   'portion': '1/2',
   'sortOrder': '2',
   'motivation': {'en': 'for his lifelong work for international peace conferences, diplomacy and arbitration',
    'no': 'for sin  livslange innsats for internasjonale fredskonferanser, diplomati og voldgift'},
   'links': [{'rel': 'laureate',
     'href': 'https://api.nobelprize.org/2/laureate/463',
     'action': 'GET',
     'types': 'application/json'}]}]}

In [48]:
prizes = []
for prize in data['nobelPrizes']:
    for laureate in prize.get('laureates', []):
        prizes.append({
            "year": prize['awardYear'],
            "category": prize['category']['en'],
            "laureate_name": laureate.get('knownName', {}).get('en', 'N/A'),  # обработка отсутствующего 'knownName'
            "motivation": laureate.get('motivation', {}).get('en', 'N/A')
        })
        
df = pd.DataFrame(prizes)

df.head()

,year,category,laureate_name,motivation
0,1901,Chemistry,Jacobus H. van 't Hoff,in recognition of the extraordinary services h...
1,1901,Literature,Sully Prudhomme,in special recognition of his poetic compositi...
2,1901,Peace,Henry Dunant,for his humanitarian efforts to help wounded s...
3,1901,Peace,Frédéric Passy,for his lifelong work for international peace ...
4,1901,Physics,Wilhelm Conrad Röntgen,in recognition of the extraordinary services h...

### Скрапинг

In [49]:
from bs4 import BeautifulSoup
import requests
# Загружаем страницу
url = "https://en.wikipedia.org/wiki/Life_expectancy"
response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})

soup = BeautifulSoup(response.text, 'html.parser')

# Находим таблицу после заголовка "Variation over time"
variation_header = soup.find(id="Variation_over_time")
table = variation_header.find_next("table")

table

<table class="wikitable sortable" style="margin-left: auto; margin-right: auto; border: none; font-size:95%">
<tbody><tr>
<th>Era</th>
<th>Life expectancy at birth in years</th>
<th>Notes
</th></tr>
<tr>
<td><a href="/wiki/Paleolithic" title="Paleolithic">Paleolithic</a></td>
<td style="text-align:center;">22–33<sup class="reference" id="cite_ref-Kotre1997_20-0"><a href="#cite_note-Kotre1997-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup></td>
<td>With modern hunter-gatherer populations' estimated average life expectancy at birth of 33 years, life expectancy for the 60% reaching age 15 averages 39 remaining years.<sup class="reference" id="cite_ref-kaplanetal2000_21-0"><a href="#cite_note-kaplanetal2000-21"><span class="cite-bracket">[</span>20<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Neolithic" title="Neolithic">Neolithic</a></td>
<td style="text-align:center;">20<sup class="reference" id="cite_ref-Galor&amp;Moav2007_22-0"><a href="#cite_note-Galor&amp;Moav2007-22"><span class="cite-bracket">[</span>21<span class="cite-bracket">]</span></a></sup>–33<sup class="reference" id="cite_ref-Lawrence1984_23-0"><a href="#cite_note-Lawrence1984-23"><span class="cite-bracket">[</span>22<span class="cite-bracket">]</span></a></sup></td>
<td>Based on Early Neolithic data, life expectancy at age 15 would be 28–33 years.<sup class="reference" id="cite_ref-Angel_1969_24-0"><a href="#cite_note-Angel_1969-24"><span class="cite-bracket">[</span>23<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Bronze_Age" title="Bronze Age">Bronze Age</a> and <a href="/wiki/Iron_Age" title="Iron Age">Iron Age</a><sup class="reference" id="cite_ref-sticerd.lse.ac.uk_25-0"><a href="#cite_note-sticerd.lse.ac.uk-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">26</td>
<td>Based on Early and Middle Bronze Age data, life expectancy at age 15 would be 28–36 years.<sup class="reference" id="cite_ref-Angel_1969_24-1"><a href="#cite_note-Angel_1969-24"><span class="cite-bracket">[</span>23<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Classical_Greece" title="Classical Greece">Classical Greece</a><sup class="reference" id="cite_ref-26"><a href="#cite_note-26"><span class="cite-bracket">[</span>25<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">25<sup class="reference" id="cite_ref-27"><a href="#cite_note-27"><span class="cite-bracket">[</span>26<span class="cite-bracket">]</span></a></sup>–28<sup class="reference" id="cite_ref-britannica_28-0"><a href="#cite_note-britannica-28"><span class="cite-bracket">[</span>27<span class="cite-bracket">]</span></a></sup></td>
<td>Based on Athens Agora and Corinth data, life expectancy at age 15 would be 37–41 years.<sup class="reference" id="cite_ref-Angel_1969_24-2"><a href="#cite_note-Angel_1969-24"><span class="cite-bracket">[</span>23<span class="cite-bracket">]</span></a></sup> Most Greeks and Romans died young. About half of all children died before adolescence. Those who survived to the age of 30 had a reasonable chance of reaching 50 or 60. The truly elderly, however, were rare. Because so many died in childhood, life expectancy at birth was probably between 20 and 30 years.<sup class="reference" id="cite_ref-Ryan2021_29-0"><a href="#cite_note-Ryan2021-29"><span class="cite-bracket">[</span>28<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Ancient_Rome" title="Ancient Rome">Ancient Rome</a></td>
<td style="text-align:center;">20–33
<p><sup class="reference" id="cite_ref-Boatwright2021_30-0"><a href="#cite_note-Boatwright2021-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-31"><a href="#cite_note-31"><span class="cite-bracket">[</span>30<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Saller1997_32-0"><a href="#cite_note-Saller1997-32"><span class="cite-bracket">[</span>31<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Ryan2021_29-1"><a href="#cite_note-Ryan2021-29"><span class="cite-bracket">[</span>28<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Kotre1997_20-1"><a href="#cite_note-Kotre1997-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Carrieri2005_33-0"><a href="#cite_note-Carrieri2005-33"><span class="cite-bracket">[</span>32<span class="cite-bracket">]</span></a></sup>
</p>
</td>
<td>Data is lacking, but computer models provide the estimate. If a person survived to age 20, they could expect to live around 30 years more. Life expectancy was probably slightly longer for women than men.<sup class="reference" id="cite_ref-Frier2008_34-0"><a href="#cite_note-Frier2008-34"><span class="cite-bracket">[</span>33<span class="cite-bracket">]</span></a></sup>
<p>Life expectancy at age 1 reached 34–41 remaining years for the 67<sup class="reference" id="cite_ref-Boatwright2021_30-1"><a href="#cite_note-Boatwright2021-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup>–75% surviving the first year. For the 55–65% surviving to age 5, remaining life expectancy reached around 40–45,<sup class="reference" id="cite_ref-Saller1997_32-1"><a href="#cite_note-Saller1997-32"><span class="cite-bracket">[</span>31<span class="cite-bracket">]</span></a></sup> while the ~50% reaching age 10 could expect another 40 years of life.<sup class="reference" id="cite_ref-Boatwright2021_30-2"><a href="#cite_note-Boatwright2021-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup> Average remaining years fell to 33–39 at age 15; ~20 at age 40;<sup class="reference" id="cite_ref-Boatwright2021_30-3"><a href="#cite_note-Boatwright2021-30"><span class="cite-bracket">[</span>29<span class="cite-bracket">]</span></a></sup> 14–18 at age 50; ~10–12 at age 60; and ~6–7 at age 70.<sup class="reference" id="cite_ref-Saller1997_32-2"><a href="#cite_note-Saller1997-32"><span class="cite-bracket">[</span>31<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Frier2008_34-1"><a href="#cite_note-Frier2008-34"><span class="cite-bracket">[</span>33<span class="cite-bracket">]</span></a></sup>
</p>
</td></tr>
<tr>
<td>Wang clan of China, 1st century AD – 1749</td>
<td style="text-align:center;">35</td>
<td>Life expectancy at age 1 reached 47 years for the 72% surviving the first year.<sup class="reference" id="cite_ref-Maher2021_35-0"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Bagchi2008_36-0"><a href="#cite_note-Bagchi2008-36"><span class="cite-bracket">[</span>35<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Early_Middle_Ages" title="Early Middle Ages">Early Middle Ages</a> (Europe, from the late 5th or early 6th century to the 10th century)</td>
<td style="text-align:center;">30–35</td>
<td>A Gaulish boy surviving to age 20 might expect to live 25 more years, while a woman at age 20 could normally expect about 17 more years. Anyone who survived until 40 had a good chance of another 15 to 20 years.<sup class="reference" id="cite_ref-37"><a href="#cite_note-37"><span class="cite-bracket">[</span>36<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Mesoamerica" title="Mesoamerica">Pre-Columbian Mesoamerica</a></td>
<td style="text-align:center;">20–40</td>
<td>Expectation of life at birth 13–36 years for various Pre-Columbian Mesoamerican cultures, most of the results lying in the range 24–32 years.<sup class="reference" id="cite_ref-38"><a href="#cite_note-38"><span class="cite-bracket">[</span>37<span class="cite-bracket">]</span></a></sup> Aztec life expectancy 41.2 years for men and 42.1 for women.<sup class="reference" id="cite_ref-39"><a href="#cite_note-39"><span class="cite-bracket">[</span>38<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/England_in_the_Middle_Ages" title="England in the Middle Ages">Late medieval English peerage</a><sup class="reference" id="cite_ref-40"><a href="#cite_note-40"><span class="cite-bracket">[</span>39<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-41"><a href="#cite_note-41"><span class="cite-bracket">[</span>40<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">30–33<sup class="reference" id="cite_ref-Carrieri2005_33-1"><a href="#cite_note-Carrieri2005-33"><span class="cite-bracket">[</span>32<span class="cite-bracket">]</span></a></sup></td>
<td>Around a third of infants died in their first year.<sup class="reference" id="cite_ref-Kotre1997_20-2"><a href="#cite_note-Kotre1997-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup> Life expectancy at age 10 reached 32.2 remaining years, and for those who survived to 25, the remaining life expectancy was 23.3 years. Such estimates reflected the life expectancy of adult males from the higher ranks of English society in the Middle Ages, and were similar to that computed for monks of the Christ Church in Canterbury during the 15th century.<sup class="reference" id="cite_ref-Carrieri2005_33-2"><a href="#cite_note-Carrieri2005-33"><span class="cite-bracket">[</span>32<span class="cite-bracket">]</span></a></sup> At age 21, life expectancy of an aristocrat was an additional 43 years.<sup class="reference" id="cite_ref-Expectations_of_Life_42-0"><a href="#cite_note-Expectations_of_Life-42"><span class="cite-bracket">[</span>41<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td><a href="/wiki/Early_modern_Britain" title="Early modern Britain">Early modern Britain</a> (16th – 18th century)<sup class="reference" id="cite_ref-sticerd.lse.ac.uk_25-1"><a href="#cite_note-sticerd.lse.ac.uk-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">33–40</td>
<td>18th-century male life expectancy at birth was 34 years.<sup class="reference" id="cite_ref-pomeranz_43-0"><a href="#cite_note-pomeranz-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup> Female expectation of remaining years at age 15 rose from ~33 years around the 15th-16th centuries to ~42 in the 18th century.<sup class="reference" id="cite_ref-Griffin2008_44-0"><a href="#cite_note-Griffin2008-44"><span class="cite-bracket">[</span>43<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18th-century <a href="/wiki/England" title="England">England</a><sup class="reference" id="cite_ref-OurWorldInData_45-0"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Kotre1997_20-3"><a href="#cite_note-Kotre1997-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">25–40</td>
<td>For most of the century it ranged from 35 to 40; but in the 1720s it dipped as low as 25.<sup class="reference" id="cite_ref-OurWorldInData_45-1"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> During the second half of the century it averaged 37,<sup class="reference" id="cite_ref-Li2021_46-0"><a href="#cite_note-Li2021-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup> while for the elite it passed 40 and approached 50.<sup class="reference" id="cite_ref-Maher2021_35-1"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>Pre-Champlain <a class="mw-redirect" href="/wiki/Canadian_Maritimes" title="Canadian Maritimes">Canadian Maritimes</a><sup class="reference" id="cite_ref-47"><a href="#cite_note-47"><span class="cite-bracket">[</span>46<span class="cite-bracket">]</span></a></sup>
</td>
<td style="text-align:center;">60
</td>
<td><a href="/wiki/Samuel_de_Champlain" title="Samuel de Champlain">Samuel de Champlain</a> wrote that in his visits to <a href="/wiki/Mi%27kmaq" title="Mi'kmaq">Mi'kmaq</a> and Huron communities, he met people over 100 years old. <a href="/wiki/Daniel_N._Paul" title="Daniel N. Paul">Daniel Paul</a> attributes the incredible lifespan in the region to low stress and a healthy diet of lean meats, diverse vegetables, and legumes.<sup class="reference" id="cite_ref-48"><a href="#cite_note-48"><span class="cite-bracket">[</span>47<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18th-century <a href="/wiki/Prussia" title="Prussia">Prussia</a><sup class="reference" id="cite_ref-pomeranz_43-1"><a href="#cite_note-pomeranz-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">24.7</td>
<td>For males.<sup class="reference" id="cite_ref-pomeranz_43-2"><a href="#cite_note-pomeranz-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18th-century <a href="/wiki/France" title="France">France</a><sup class="reference" id="cite_ref-pomeranz_43-3"><a href="#cite_note-pomeranz-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">27.5–30</td>
<td>For males:<sup class="reference" id="cite_ref-pomeranz_43-4"><a href="#cite_note-pomeranz-43"><span class="cite-bracket">[</span>42<span class="cite-bracket">]</span></a></sup> 24.8 years in 1740–1749, 27.9 years in 1750–1759, 33.9 years in 1800–1809.<sup class="reference" id="cite_ref-Bagchi2008_36-1"><a href="#cite_note-Bagchi2008-36"><span class="cite-bracket">[</span>35<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18th-century American colonies<sup class="reference" id="cite_ref-Kotre1997_20-4"><a href="#cite_note-Kotre1997-20"><span class="cite-bracket">[</span>19<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">28</td>
<td>Massachusetts colonists who reached the age of 50 could expect to live until 71, and those who were still alive at 60 could expect to reach 75.
</td></tr>
<tr>
<td>Beginning of the 19th century<sup class="reference" id="cite_ref-OurWorldInData_45-2"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">~29</td>
<td>At the beginning of the 19th century, no country in the world had a life expectancy at birth longer than 40 years, England, Belgium and the Netherlands came closest, each reaching 40 years by the 1840s (by which time they had been surpassed by Norway, Sweden and Denmark). India's life expectancy is estimated at ~25 years,<sup class="reference" id="cite_ref-OurWorldInData_45-3"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> while Europe averaged ~33 years.<sup class="reference" id="cite_ref-Li2021_46-1"><a href="#cite_note-Li2021-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>Early 19th-century <a href="/wiki/England" title="England">England</a><sup class="reference" id="cite_ref-sticerd.lse.ac.uk_25-2"><a href="#cite_note-sticerd.lse.ac.uk-25"><span class="cite-bracket">[</span>24<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-OurWorldInData_45-4"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup><sup class="reference" id="cite_ref-Maher2021_35-2"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">40</td>
<td>Remaining years of life averaged ~45<sup class="reference" id="cite_ref-Maher2021_35-3"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup>–47 for the 84% who survived the first year. Life expectancy fell to ~40 years at age 20, then ~20 years at age 50 and ~10 years at age 70.<sup class="reference" id="cite_ref-OurWorldInData_45-5"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> For a 15-year-old girl it was ~40–45.<sup class="reference" id="cite_ref-Griffin2008_44-1"><a href="#cite_note-Griffin2008-44"><span class="cite-bracket">[</span>43<span class="cite-bracket">]</span></a></sup> For the upper-class, LEB rose from ~45 to 50.<sup class="reference" id="cite_ref-Maher2021_35-4"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup>
<p>Only half of the people born in the early 19th century made it past their 50th birthday. In contrast, 97% of the people born in 21st century England and Wales can expect to live longer than 50 years.<sup class="reference" id="cite_ref-OurWorldInData_45-6"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup>
</p>
</td></tr>
<tr>
<td>19th-century <a href="/wiki/British_Raj" title="British Raj">British India</a><sup class="reference" id="cite_ref-49"><a href="#cite_note-49"><span class="cite-bracket">[</span>48<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">25.4</td>
<td>
</td></tr>
<tr>
<td>19th-century world average<sup class="reference" id="cite_ref-OurWorldInData_45-7"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">28.5–32</td>
<td>Over the course of the century: Europe rose from ~33 to 43, the Americas from ~35 to 41, Oceania ~35 to 48, Asia ~28, Africa 26.<sup class="reference" id="cite_ref-OurWorldInData_45-8"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup> In 1820s France, LEB was ~38, and for the 80% that survived, it rose to ~47. For Moscow serfs, LEB was ~34, and for the 66% that survived, it rose to ~36.<sup class="reference" id="cite_ref-Maher2021_35-5"><a href="#cite_note-Maher2021-35"><span class="cite-bracket">[</span>34<span class="cite-bracket">]</span></a></sup> Western Europe in 1830 was ~33 years, while for the people of Hau-Lou in China, it was ~40.<sup class="reference" id="cite_ref-Li2021_46-2"><a href="#cite_note-Li2021-46"><span class="cite-bracket">[</span>45<span class="cite-bracket">]</span></a></sup> The LEB for a 10-year-old in Sweden rose from ~44 to ~54.<sup class="reference" id="cite_ref-OurWorldInData_45-9"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>1900 world average<sup class="reference" id="cite_ref-WHO_Consultant_2006_50-0"><a href="#cite_note-WHO_Consultant_2006-50"><span class="cite-bracket">[</span>49<span class="cite-bracket">]</span></a></sup></td>
<td style="text-align:center;">31–32<sup class="reference" id="cite_ref-OurWorldInData_45-10"><a href="#cite_note-OurWorldInData-45"><span class="cite-bracket">[</span>44<span class="cite-bracket">]</span></a></sup></td>

In [50]:
# Преобразуем таблицу в DataFrame
from io import StringIO
pd.read_html(StringIO(str(table)))[0]

,Era,Life expectancy at birth in years,Notes
0,Paleolithic,22–33[19],With modern hunter-gatherer populations' estim...
1,Neolithic,20[21]–33[22],"Based on Early Neolithic data, life expectancy..."
2,Bronze Age and Iron Age[24],26,"Based on Early and Middle Bronze Age data, lif..."
3,Classical Greece[25],25[26]–28[27],"Based on Athens Agora and Corinth data, life e..."
4,Ancient Rome,20–33 [29][30][31][28][19][32],"Data is lacking, but computer models provide t..."
5,"Wang clan of China, 1st century AD – 1749",35,Life expectancy at age 1 reached 47 years for ...
6,"Early Middle Ages (Europe, from the late 5th o...",30–35,A Gaulish boy surviving to age 20 might expect...
7,Pre-Columbian Mesoamerica,20–40,Expectation of life at birth 13–36 years for v...
8,Late medieval English peerage[39][40],30–33[32],Around a third of infants died in their first ...
9,Early modern Britain (16th – 18th century)[24],33–40,18th-century male life expectancy at birth was...
10,18th-century England[44][19],25–40,For most of the century it ranged from 35 to 4...
11,Pre-Champlain Canadian Maritimes[46],60,Samuel de Champlain wrote that in his visits t...
12,18th-century Prussia[42],24.7,For males.[42]
13,18th-century France[42],27.5–30,"For males:[42] 24.8 years in 1740–1749, 27.9 y..."
14,18th-century American colonies[19],28,Massachusetts colonists who reached the age of...
15,Beginning of the 19th century[44],~29,"At the beginning of the 19th century, no count..."
16,Early 19th-century England[24][44][34],40,Remaining years of life averaged ~45[34]–47 fo...
17,19th-century British India[48],25.4,NaN
18,19th-century world average[44],28.5–32,Over the course of the century: Europe rose fr...
19,1900 world average[49],31–32[44],"Around 48 years in Oceania, 43 in Europe, and ..."
20,1950 world average[49],45.7–48[44],"Around 60 years in Europe, North America, Ocea..."
21,2019–2020 world average,72.6–73.2 [44][50][51],Females: 75.6 years Males: 70.8 years Range: ~...

### Чтение из БД

In [53]:
import psycopg2
# !pip install psycopg2-binary

In [52]:
!pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 22.3 MB/s eta 0:00:00m eta 0:00:010:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [56]:
DBNAME = 'postgres'
USER = 'postgres'
HOST = 'localhost'
PASSWORD = 'postgres'
PORT = 5432

In [57]:
# создаем соединение с необходимыми параметрами
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

In [58]:
n = 10
query = f'''select * 
            from mifidev.clients
            limit {n}
         '''

In [62]:
df = pd.read_sql_query(query, connection)
df

/tmp/ipykernel_7356/137330334.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

InterfaceError: connection already closed

In [60]:
connection.close()

In [63]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.44-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/marina/learning/.venv/lib/python3.12/site-packages (from sqlalchemy) (4.12.2)
Downloading sqlalchemy-2.0.44-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 21.5 MB/s eta 0:00:00m eta 0:00:010:0101
Downloading greenlet-3.2.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (607 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 607.6/607.6 kB 23.1 MB/s eta 0:00:00
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.2.4 sqlalchemy-2.0.44

In [71]:
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData, select, text
# pip install sqlalchemy

In [65]:
conn_str = f"postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DBNAME}"

# создание объекта Engine для подключения к базе данных
engine = create_engine(conn_str)

df = pd.read_sql_query(query, engine)
df

   id                            name        phone                email
0   1                           А А А  89992274444          aaa@mail.ru
1   2            Иванов Иван Иванович  89992332244  ivanov.ivan@mail.ru
2   3            Бук Василий Петрович  89992334444    vasya_buk@mail.ru
3   4          Петрова Мария Петровна  89992334678    masha_111@mail.ru
4   5  Давыдова  Екатерина Викторовна  88753334444     davidova@mail.ru
5   6               Юров Юрий Юрьевич  89992334428         yura@mail.ru
6   7         Мартынова Нина Павловна  89998763444           np@mail.ru
7   8                    Цой Виктор И  85792334444         tsoi@mail.ru
8  10                       test test  89992274444          aaa@mail.ru

In [72]:
with engine.connect() as conn:
    result = conn.execute(text('select * from mifidev.clients        limit 10'))
    for row in result:
        print(row)

(1, 'А А А', '89992274444', 'aaa@mail.ru')
(2, 'Иванов Иван Иванович', '89992332244', 'ivanov.ivan@mail.ru')
(3, 'Бук Василий Петрович', '89992334444', 'vasya_buk@mail.ru')
(4, 'Петрова Мария Петровна', '89992334678', 'masha_111@mail.ru')
(5, 'Давыдова  Екатерина Викторовна', '88753334444', 'davidova@mail.ru')
(6, 'Юров Юрий Юрьевич', '89992334428', 'yura@mail.ru')
(7, 'Мартынова Нина Павловна', '89998763444', 'np@mail.ru')
(8, 'Цой Виктор И', '85792334444', 'tsoi@mail.ru')
(10, 'test test', '89992274444', 'aaa@mail.ru')