# melb begin 6/12   Знакомимся с данными: недвижимость

In [1]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [2]:
melb_data.describe()

,index,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000
mean,6789.500000,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.611856,558.416127,139.633972,1966.788218,-37.809203,144.995216,7454.417378
std,3920.352663,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.960793,3990.669241,392.217403,29.088642,0.079260,0.103916,4378.581772
min,0.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,3394.750000,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,122.000000,1960.000000,-37.856822,144.929600,4380.000000
50%,6789.500000,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,10184.250000,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,129.940000,1975.000000,-37.756400,145.058305,10331.000000
max,13579.000000,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [3]:
melb_data

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,"-37.8072, 144.9941"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,652.0,126.0,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,"-37.90562, 145.16761"
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0,"-37.85927, 144.87904"
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4.0,436.0,126.0,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0,"-37.85274, 144.88738"
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,"-37.81188, 144.88449"

In [4]:
melb_data.loc[3552, 'Landsize'] / melb_data.loc[1690, 'Landsize']

2.511904761904762

In [5]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  object
dtypes: float64(11), int64(3), object(9)
memory usage: 2.4+ MB

In [6]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [7]:
melb_data.describe().loc[:, ['Distance', 'BuildingArea', 'Price']]

           Distance  BuildingArea         Price
count  13580.000000  13580.000000  1.358000e+04
mean      10.137776    139.633972  1.075684e+06
std        5.868725    392.217403  6.393107e+05
min        0.000000      0.000000  8.500000e+04
25%        6.100000    122.000000  6.500000e+05
50%        9.200000    126.000000  9.030000e+05
75%       13.000000    129.940000  1.330000e+06
max       48.100000  44515.000000  9.000000e+06

In [8]:
melb_data.describe(include=['object'] ).loc[:, ['Type']]

         Type
count   13580
unique      3
top         h
freq     9449

In [9]:
melb_data['Type'].value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [10]:
1114 / 13580 * 100

8.203240058910161

In [11]:
melb_data.isnull().sum()

index               0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom             0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
Coordinates         0
dtype: int64

In [12]:
melb_data['Bedroom'].mode()

0    3
Name: Bedroom, dtype: int64

In [13]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [14]:
melb_data.describe().loc[:, 'Propertycount']

count    13580.000000
mean      7454.417378
std       4378.581772
min        249.000000
25%       4380.000000
50%       6555.000000
75%      10331.000000
max      21650.000000
Name: Propertycount, dtype: float64

In [15]:
melb_data.head().loc[:, 'Propertycount']

0    4019
1    4019
2    4019
3    4019
4    4019
Name: Propertycount, dtype: int64

In [16]:
landsize_median = melb_data['Landsize'].median() 
landsize_mean =  melb_data['Landsize'].mean()
print(abs(landsize_median - landsize_mean)/landsize_mean)
# 0.21205713983546193

0.21205713983546193

In [17]:
b_median = melb_data['BuildingArea'].median() 
b_mean =  melb_data['BuildingArea'].mean()
print(abs(b_median - b_mean)/b_mean)
# 0.21205713983546193

0.09764079662364533

In [18]:
melb_data['BuildingArea'].median()

126.0

In [19]:
melb_data['BuildingArea'].mean()

139.63397229013256

# begin 9/12   Фильтрация данных в DataFrame

In [20]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [21]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [22]:
melb_data[melb_data['Bathroom'] == 0].shape[0]

34

In [23]:
melb_data['Type'].describe()

count     13580
unique        3
top           h
freq       9449
Name: Type, dtype: object

In [24]:
melb_data[melb_data['SellerG'] == 'Nelson'].shape[0]

1565

In [25]:
melb_data[melb_data['Price'] > 3_000_000].shape[0]

221

In [26]:
melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3_000_000)].shape[0]

5

In [27]:
melb_data[melb_data['BuildingArea'] == 0]['Price'].min()

412500.0

Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, в которых либо количество комнат больше пяти, либо здание моложе 2015 года?

In [28]:
price = melb_data['Price'] < 1_000_000
room = melb_data['Rooms'] > 5
year = melb_data['YearBuilt'] > 2015
mask = price & (room | year)
melb_data[mask]['Price'].mean()

769238.6363636364

В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?

In [29]:
price = melb_data['Price'] < 3_000_000
type = melb_data['Type'] == 'h'
mask = price & type

In [30]:
melb_data[mask]['Regionname'].value_counts()

Regionname
Northern Metropolitan         2737
Southern Metropolitan         2520
Western Metropolitan          2286
Eastern Metropolitan          1167
South-Eastern Metropolitan     387
Eastern Victoria                50
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [31]:
melb_data[mask].describe(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname,Coordinates
count,9220,9220,9220,9220,9220,9220,7999,9220,9220
unique,313,9075,1,5,232,58,33,8,9160
top,Reservoir,2 Bruce St,h,S,Nelson,27/05/2017,Moreland,Northern Metropolitan,"-37.74635, 144.9229"
freq,253,3,9220,6367,1154,334,842,2737,2

In [32]:
melb_data[mask].groupby('Regionname').count()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Propertycount,Coordinates
Regionname,,,,,,,,,,,,,,,,,,,,,
Eastern Metropolitan,1167,1167,1167,1167,1167,1167,1167,1167,1167,1167,...,1167,1167,1167,1167,1167,943,1167,1167,1167,1167
Eastern Victoria,50,50,50,50,50,50,50,50,50,50,...,50,50,50,50,50,41,50,50,50,50
Northern Metropolitan,2737,2737,2737,2737,2737,2737,2737,2737,2737,2737,...,2737,2737,2737,2737,2737,2436,2737,2737,2737,2737
Northern Victoria,41,41,41,41,41,41,41,41,41,41,...,41,41,41,41,41,26,41,41,41,41
South-Eastern Metropolitan,387,387,387,387,387,387,387,387,387,387,...,387,387,387,387,387,272,387,387,387,387
Southern Metropolitan,2520,2520,2520,2520,2520,2520,2520,2520,2520,2520,...,2520,2520,2520,2520,2520,2233,2520,2520,2520,2520
Western Metropolitan,2286,2286,2286,2286,2286,2286,2286,2286,2286,2286,...,2286,2286,2286,2286,2286,2023,2286,2286,2286,2286
Western Victoria,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,25,32,32,32,32

# melb_data

In [33]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
melb_data.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [34]:
melb_data.shape

(13580, 23)

In [35]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [36]:
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

За удаление строк и столбцов в таблице отвечает метод drop().

Кликните на плашку, чтобы увидеть информацию ↓

Основные параметры метода drop()

labels — порядковые номера или имена столбцов, которые подлежат удалению; если их несколько, то передаётся список;
axis — ось совершения операции, axis=0 — удаляются строки, axis=1 — удаляются столбцы;
inplace — если параметр выставлен на True, происходит замена изначального DataFrame на новый, при этом метод ничего не возвращает; если на False — возвращается копия DataFrame, из которой удалены указанные строки (столбцы), при этом первоначальный DataFrame не изменяется; по умолчанию парамр раве


н False.
Удалим столбцы index и Coordinates из таблицы с помощью метода drop(). Выведем первые пять строк таблицы и убедимся, что всё прошло успешно.

In [37]:
melb_df = melb_df.drop(['index', 'Coordinates'], axis=1)
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067,...,1,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067,...,1,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067,...,2,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067,...,2,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067,...,1,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

In [38]:
total_rooms = melb_df['Rooms'] + melb_df['Bedroom'] + melb_df['Bathroom']
display(total_rooms)

0         5
1         5
2         8
3         8
4         8
         ..
13575    10
13576     8
13577     8
13578     9
13579     9
Length: 13580, dtype: int64

А теперь введём признак MeanRoomsArea, который соответствует средней площади одной комнаты для каждого объекта. Для этого разделим площадь здания на полученное ранее общее количество комнат:

In [39]:
melb_df['MeanRoomsArea'] = melb_df['BuildingArea'] / total_rooms
display(melb_df['MeanRoomsArea'])

0        25.200000
1        15.800000
2        18.750000
3        15.750000
4        17.750000
           ...
13575    12.600000
13576    16.625000
13577    15.750000
13578    17.444444
13579    12.444444
Name: MeanRoomsArea, Length: 13580, dtype: float64

Можно ввести ещё один интересный признак — AreaRatio, коэффициент соотношения площади здания (BuildingArea) и площади участка (Landsize). Для этого разницу двух площадей поделим на их сумму:

In [40]:
diff_area = melb_df['BuildingArea'] - melb_df['Landsize']
sum_area = melb_df['BuildingArea'] + melb_df['Landsize']
melb_df['AreaRatio'] = diff_area/sum_area
display(melb_df['AreaRatio'])

0       -0.231707
1       -0.327660
2        0.056338
3        0.145455
4        0.083969
           ...
13575   -0.676093
13576   -0.429185
13577   -0.551601
13578   -0.693060
13579   -0.527426
Name: AreaRatio, Length: 13580, dtype: float64

Что показывает такой коэффициент? Если присмотреться, можно увидеть, что AreaRatio лежит в интервале от -1 до 1.

Рассмотрим три случая, чтобы понять его значение:

Если рассматриваемые площади равны, то числитель дроби зануляется и коэффициент тоже равен 0.
Если одна из площадей начинает доминировать над другой, то коэффициент начинает расти в отрицательную сторону, если площадь участка больше площади здания, и в положительную сторону, если наоборот.
Наконец, в предельном случае, если площадь здания равна 0, то числитель дроби равен знаменателю со знаком минус, а коэффициент равен -1, а если площадь участка равна 0, то числитель дроби равен знаменателю со знаком плюс, а коэффициент равен 1.
Таким образом, значение в столбце AreaRatio служит своеобразным указателем соотношения площадей объекта недвижимости. Для пустырей — участков без строений — он будет равен -1, для домов без территории — 1, во всех остальных случаях мы можем увидеть, какая площадь больше — здания или участка.

### 4/10   Работа с датами в DataFrame

In [41]:
display(melb_df['Date'])

0         3/12/2016
1         4/02/2016
2         4/03/2017
3         4/03/2017
4         4/06/2016
            ...
13575    26/08/2017
13576    26/08/2017
13577    26/08/2017
13578    26/08/2017
13579    26/08/2017
Name: Date, Length: 13580, dtype: object

In [42]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)
display(melb_df['Date'])

0       2016-12-03
1       2016-02-04
2       2017-03-04
3       2017-03-04
4       2016-06-04
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [43]:
years_sold = melb_df['Date'].dt.year
print(years_sold)
print('Min year sold:', years_sold.min())
print('Max year sold:', years_sold.max())
print('Mode year sold:', years_sold.mode()[0])

0        2016
1        2016
2        2017
3        2017
4        2016
         ...
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int32
Min year sold: 2016
Max year sold: 2017
Mode year sold: 2017

In [44]:
melb_df['MonthSale'] = melb_df['Date'].dt.month
melb_df['MonthSale'].value_counts(normalize=True)

MonthSale
5     0.149411
7     0.145950
9     0.135862
6     0.134757
8     0.114138
11    0.082032
4     0.069882
3     0.049926
12    0.044698
10    0.040574
2     0.032622
1     0.000147
Name: proportion, dtype: float64

In [45]:
melb_df['AgeBuilding'] = melb_df['Date'].dt.year - melb_df['YearBuilt']
display(melb_df['AgeBuilding'])

0         46
1        116
2        117
3         47
4          2
        ...
13575     36
13576     22
13577     20
13578     97
13579     97
Name: AgeBuilding, Length: 13580, dtype: int64

На самом деле столбец AgeBuilding дублирует информацию столбца YearBuilt, так как, зная год постройки здания, мы автоматически знаем его возраст. Такие признаки не стоит оставлять вместе, поэтому оставим возраст здания, так как он является более наглядным, а год постройки удалим из таблицы:

In [46]:
melb_df = melb_df.drop('YearBuilt', axis=1)

Создайте в таблице melb_df признак WeekdaySale (день недели). Найдите, сколько объектов недвижимости было продано в выходные (суббота и воскресенье), результат занесите в переменную weekend_count. В качестве ответа введите результат вывода переменной weekend_count.

In [47]:
melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
melb_df['WeekdaySale'].value_counts()

WeekdaySale
5    11759
6     1063
0      597
1      133
3       28
Name: count, dtype: int64

In [48]:
weekend_count = melb_df[(melb_df['WeekdaySale'] == 6) | (melb_df['WeekdaySale'] == 5)].shape[0]
weekend_count

12822

## 5/10   Создание и преобразование столбцов с помощью функций

In [49]:
print(melb_df['Address'].nunique())
# 13378

13378

In [50]:
print(melb_df['Address'].loc[177])
print(melb_df['Address'].loc[1812])
print(melb_df['Address'].loc[9001])
# 2/119 Railway St N
# 9/400 Dandenong Rd
# 172 Danks St

2/119 Railway St N
9/400 Dandenong Rd
172 Danks St

In [51]:
# На вход данной функции поступает строка с адресом.
def get_street_type(address):
# Создаём список географических пометок exclude_list.
    exclude_list = ['N', 'S', 'W', 'E']
# Метод split() разбивает строку на слова по пробелу.
# В результате получаем список слов в строке и заносим его в переменную address_list.
    address_list = address.split(' ')
# Обрезаем список, оставляя в нём только последний элемент,
# потенциальный подтип улицы, и заносим в переменную street_type.
    street_type = address_list[-1]
# Делаем проверку на то, что полученный подтип является географической пометкой.
# Для этого проверяем его на наличие в списке exclude_list.
    if street_type in exclude_list:
# Если переменная street_type является географической пометкой,
# переопределяем её на второй элемент с конца списка address_list.
        street_type = address_list[-2]
# Возвращаем переменную street_type, в которой хранится подтип улицы.
    return street_type

In [52]:
street_types = melb_df['Address'].apply(get_street_type)
display(street_types)

0        St
1        St
2        St
3        La
4        St
         ..
13575    Cr
13576    Dr
13577    St
13578    St
13579    St
Name: Address, Length: 13580, dtype: object

In [53]:
street_types.nunique()

56

In [54]:
display(street_types.value_counts())

Address
St           8012
Rd           2825
Ct            612
Dr            447
Av            321
Gr            311
Pde           211
Pl            169
Cr            152
Cl            100
La             67
Bvd            53
Tce            47
Wy             40
Avenue         40
Cct            25
Hwy            24
Parade         15
Boulevard      13
Sq             11
Crescent        9
Cir             7
Strand          7
Esplanade       6
Grove           5
Gdns            4
Grn             4
Fairway         4
Mews            4
Crossway        3
Righi           3
Victoria        2
Ridge           2
Crofts          2
Esp             2
Glade           1
Gra             1
Ave             1
Woodland        1
Outlook         1
Hts             1
Highway         1
Athol           1
Summit          1
Grand           1
Res             1
Nook            1
Eyrie           1
Dell            1
East            1
Loop            1
Grange          1
Terrace         1
Cove            1
Qy              1
Corso           1
Name: count, dtype: int64

In [55]:
street_types.value_counts().nlargest(10).index

Index(['St', 'Rd', 'Ct', 'Dr', 'Av', 'Gr', 'Pde', 'Pl', 'Cr', 'Cl'], dtype='object', name='Address')

In [56]:
popular_stypes = street_types.value_counts().nlargest(10).index

In [67]:
melb_df.columns

Index(['Suburb', 'Rooms', 'Type', 'Price', 'Method', 'SellerG', 'Date',
       'Distance', 'Postcode', 'Bedroom', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'CouncilArea', 'Lattitude', 'Longtitude', 'Regionname',
       'Propertycount', 'MeanRoomsArea', 'AreaRatio', 'MonthSale',
       'AgeBuilding', 'WeekdaySale', 'StreeType'],
      dtype='object')

In [63]:
melb_df['StreeType'] = street_types.apply(lambda x: x if x in popular_stypes else 'other')
display(melb_df['StreeType'])

0           St
1           St
2           St
3        other
4           St
         ...
13575       Cr
13576       Dr
13577       St
13578       St
13579       St
Name: StreeType, Length: 13580, dtype: object

In [64]:
melb_df['StreeType'].nunique()

11

In [66]:
melb_df.drop('Address', axis=1, inplace=True)

#### tasks

Ранее, в задании 3.3, мы создали признак WeekdaySale в таблице melb_df — день недели продажи. Из полученных в задании результатов можно сделать вывод, что объекты недвижимости в Мельбурне продаются преимущественно по выходным (суббота и воскресенье).
Напишите функцию get_weekend(weekday), которая принимает на вход элемент столбца WeekdaySale и возвращает 1, если день является выходным, и 0 — в противном случае, и создайте столбец Weekend в таблице melb_df с помощью неё.

Примените эту функцию к столбцу и вычислите среднюю цену объекта недвижимости, проданного в выходные дни. Результат округлите до целых.

In [71]:
melb_df['WeekdaySale'].value_counts()

WeekdaySale
5    11759
6     1063
0      597
1      133
3       28
Name: count, dtype: int64

In [72]:
def get_weekend(weekday):
    if weekday == 5 or weekday == 6:
        return 1
    else:
        return 0

In [75]:
melb_df['Weekend'] = melb_df['WeekdaySale'].apply(get_weekend)
melb_df['Weekend'].value_counts()

Weekend
1    12822
0      758
Name: count, dtype: int64

In [80]:
mask = melb_df['Weekend'] == 1
melb_data[mask]['Price'].mean()

1081198.6406956792

Преобразуйте столбец SellerG с наименованиями риелторских компаний в таблице melb_df следующим образом: оставьте в столбце только 49 самых популярных компаний, а остальные обозначьте как 'other'.
Найдите, во сколько раз минимальная цена объектов недвижимости, проданных компанией 'Nelson', больше минимальной цены объектов, проданных компаниями, обозначенными как 'other'. Ответ округлите до десятых.

In [86]:
largest_sellers = melb_df['SellerG'].value_counts().nlargest(49).index

In [88]:
melb_df['SellerG'] = melb_df['SellerG'].apply(lambda x: x if x in largest_sellers else 'other')

In [91]:
melb_df['SellerG'].value_counts().nlargest(7)

SellerG
Nelson           1565
Jellis           1316
other            1199
hockingstuart    1167
Barry            1011
Ray               701
Marshall          659
Name: count, dtype: int64

In [93]:
melb_data[melb_df['SellerG'] =='Nelson']['Price'].min()

170000.0

In [94]:
melb_data[melb_df['SellerG'] =='other']['Price'].min()

131000.0

In [97]:
melb_data[melb_df['SellerG'] =='Nelson']['Price'].min() / melb_data[melb_df['SellerG'] =='other']['Price'].min()

1.297709923664122

### Категории в данных о недвижимости

In [98]:
# создаём пустой список
unique_list = []
# пробегаемся по именам столбцов в таблице
for col in melb_df.columns:
    # создаём кортеж (имя столбца, число уникальных значений)
    item = (col, melb_df[col].nunique(),melb_df[col].dtypes) 
    # добавляем кортеж в список
    unique_list.append(item) 
# создаём вспомогательную таблицу и сортируем её
unique_counts = pd.DataFrame(
    unique_list,
    columns=['Column_Name', 'Num_Unique', 'Type']
).sort_values(by='Num_Unique',  ignore_index=True)
# выводим её на экран
display(unique_counts)

      Column_Name  Num_Unique            Type
0         Weekend           2           int64
1            Type           3          object
2          Method           5          object
3     WeekdaySale           5           int32
4      Regionname           8          object
5        Bathroom           9           int64
6           Rooms           9           int64
7             Car          11           int64
8       StreeType          11          object
9         Bedroom          12           int64
10      MonthSale          12           int32
11    CouncilArea          33          object
12        SellerG          50          object
13           Date          58  datetime64[ns]
14    AgeBuilding         152           int64
15       Postcode         198           int64
16       Distance         202         float64
17  Propertycount         311           int64
18         Suburb         314          object
19   BuildingArea         602         float64
20  MeanRoomsArea        1277         float64
21       Landsize        1448         float64
22          Price        2204         float64
23      Lattitude        6503         float64
24      AreaRatio        6521         float64
25     Longtitude        7063         float64

In [99]:
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Rooms          13580 non-null  int64
 2   Type           13580 non-null  object
 3   Price          13580 non-null  float64
 4   Method         13580 non-null  object
 5   SellerG        13580 non-null  object
 6   Date           13580 non-null  datetime64[ns]
 7   Distance       13580 non-null  float64
 8   Postcode       13580 non-null  int64
 9   Bedroom        13580 non-null  int64
 10  Bathroom       13580 non-null  int64
 11  Car            13580 non-null  int64
 12  Landsize       13580 non-null  float64
 13  BuildingArea   13580 non-null  float64
 14  CouncilArea    12211 non-null  object
 15  Lattitude      13580 non-null  float64
 16  Longtitude     13580 non-null  float64
 17  Regionname     13580 non-null  object
 18  Propertycount  13580 non-null  int64
 19  MeanRoomsArea  13580 non-null  float64
 20  AreaRatio      13580 non-null  float64
 21  MonthSale      13580 non-null  int32
 22  AgeBuilding    13580 non-null  int64
 23  WeekdaySale    13580 non-null  int32
 24  StreeType      13580 non-null  object
 25  Weekend        13580 non-null  int64
dtypes: datetime64[ns](1), float64(8), int32(2), int64(8), object(7)
memory usage: 2.6+ MB

None

In [100]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Rooms          13580 non-null  int64
 2   Type           13580 non-null  category
 3   Price          13580 non-null  float64
 4   Method         13580 non-null  category
 5   SellerG        13580 non-null  category
 6   Date           13580 non-null  datetime64[ns]
 7   Distance       13580 non-null  float64
 8   Postcode       13580 non-null  int64
 9   Bedroom        13580 non-null  int64
 10  Bathroom       13580 non-null  int64
 11  Car            13580 non-null  int64
 12  Landsize       13580 non-null  float64
 13  BuildingArea   13580 non-null  float64
 14  CouncilArea    12211 non-null  category
 15  Lattitude      13580 non-null  float64
 16  Longtitude     13580 non-null  float64
 17  Regionname     13580 non-null  category
 18  Propertycount  13580 non-null  int64
 19  MeanRoomsArea  13580 non-null  float64
 20  AreaRatio      13580 non-null  float64
 21  MonthSale      13580 non-null  category
 22  AgeBuilding    13580 non-null  int64
 23  WeekdaySale    13580 non-null  category
 24  StreeType      13580 non-null  category
 25  Weekend        13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(7), object(1)
memory usage: 1.9+ MB

None

In [101]:
2.6 / 1.9

1.368421052631579

In [102]:
melb_df['Regionname'].cat.categories

Index(['Eastern Metropolitan', 'Eastern Victoria', 'Northern Metropolitan',
       'Northern Victoria', 'South-Eastern Metropolitan',
       'Southern Metropolitan', 'Western Metropolitan', 'Western Victoria'],
      dtype='object')

In [103]:
display(melb_df['Regionname'].cat.codes)

0        2
1        2
2        2
3        2
4        2
        ..
13575    4
13576    6
13577    6
13578    6
13579    6
Length: 13580, dtype: int8

In [104]:
display(melb_df['Type'])

0        h
1        h
2        h
3        h
4        h
        ..
13575    h
13576    h
13577    h
13578    h
13579    h
Name: Type, Length: 13580, dtype: category
Categories (3, object): ['h', 't', 'u']

In [106]:
melb_df['Type'] = melb_df['Type'].cat.rename_categories({
    'u': 'unit',
    't': 'townhouse',
    'h': 'house'
})
display(melb_df['Type'])

0        house
1        house
2        house
3        house
4        house
         ...
13575    house
13576    house
13577    house
13578    house
13579    house
Name: Type, Length: 13580, dtype: category
Categories (3, object): ['house', 'townhouse', 'unit']

In [109]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Rooms          13580 non-null  int64
 2   Type           13580 non-null  category
 3   Price          13580 non-null  float64
 4   Method         13580 non-null  category
 5   SellerG        13580 non-null  category
 6   Date           13580 non-null  datetime64[ns]
 7   Distance       13580 non-null  float64
 8   Postcode       13580 non-null  int64
 9   Bedroom        13580 non-null  int64
 10  Bathroom       13580 non-null  int64
 11  Car            13580 non-null  int64
 12  Landsize       13580 non-null  float64
 13  BuildingArea   13580 non-null  float64
 14  CouncilArea    12211 non-null  category
 15  Lattitude      13580 non-null  float64
 16  Longtitude     13580 non-null  float64
 17  Regionname     13580 non-null  category
 18  Propertycount  13580 non-null  int64
 19  MeanRoomsArea  13580 non-null  float64
 20  AreaRatio      13580 non-null  float64
 21  MonthSale      13580 non-null  category
 22  AgeBuilding    13580 non-null  int64
 23  WeekdaySale    13580 non-null  category
 24  StreeType      13580 non-null  category
 25  Weekend        13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(7), object(1)
memory usage: 1.9+ MB

### Задание 5.2 преобразование в категории

При преобразовании столбцов таблицы о недвижимости к типу category мы оставили без внимания столбец Suburb (пригород). Давайте исправим это.
С помощью метода info() узнайте, сколько памяти занимает таблица melb_df.
Преобразуйте признак Suburb следующим образом: оставьте в столбце только 119 наиболее популярных пригородов, остальные замените на 'other'.
Приведите данные в столбце Suburb к категориальному типу.
В качестве ответа запишите разницу между объёмом занимаемой памяти до преобразования (который мы получили ранее в модуле) и после него в Мб. Ответ округлите до десятых.

In [116]:
melb_df.memory_usage().sum()

1974736

In [131]:
popular_suburb = melb_df['Suburb'].value_counts().nlargest(119).index

melb_df['Suburb'] = melb_df['Suburb'].apply(lambda x: x if x in popular_suburb else 'other')
melb_df['Suburb'] = melb_df['Suburb'].astype('category')

In [132]:
melb_df.memory_usage().sum()

1884796

In [133]:
1974736 / 1884796

1.0477186921024875

In [135]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  category
 1   Rooms          13580 non-null  int64
 2   Type           13580 non-null  category
 3   Price          13580 non-null  float64
 4   Method         13580 non-null  category
 5   SellerG        13580 non-null  category
 6   Date           13580 non-null  datetime64[ns]
 7   Distance       13580 non-null  float64
 8   Postcode       13580 non-null  int64
 9   Bedroom        13580 non-null  int64
 10  Bathroom       13580 non-null  int64
 11  Car            13580 non-null  int64
 12  Landsize       13580 non-null  float64
 13  BuildingArea   13580 non-null  float64
 14  CouncilArea    12211 non-null  category
 15  Lattitude      13580 non-null  float64
 16  Longtitude     13580 non-null  float64
 17  Regionname     13580 non-null  category
 18  Propertycount  13580 non-null  int64
 19  MeanRoomsArea  13580 non-null  float64
 20  AreaRatio      13580 non-null  float64
 21  MonthSale      13580 non-null  category
 22  AgeBuilding    13580 non-null  int64
 23  WeekdaySale    13580 non-null  category
 24  StreeType      13580 non-null  category
 25  Weekend        13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

In [137]:
1.9 - 1.8

0.09999999999999987

# Модуль 5. Продвинутые методы работы с данными в Pandas

## read data

In [103]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data_fe.csv')
display(melb_data.head())

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,4,2,2,St,0

In [2]:
melb_df = melb_data.copy()

In [3]:
melb_df.columns

Index(['Suburb', 'Rooms', 'Type', 'Price', 'Method', 'SellerG', 'Date',
       'Distance', 'Postcode', 'Bedroom', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'CouncilArea', 'Lattitude', 'Longtitude', 'Regionname',
       'Propertycount', 'MeanRoomsSquare', 'AreaRatio', 'MonthSale',
       'AgeBuilding', 'WeekdaySale', 'StreetType', 'Weekend'],
      dtype='object')

In [4]:
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

None

## convert data

Преобразуйте столбец Date в формат datetime и выделите квартал (quarter) продажи объектов недвижимости. Найдите второй по популярности квартал продажи. В качестве ответа запишите число объектов, проданных в этом квартале.

In [5]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'])

In [6]:
display(melb_df['Date'])

0       2016-03-12
1       2016-04-02
2       2017-04-03
3       2017-04-03
4       2016-04-06
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [7]:
melb_df['quarter'] = melb_df['Date'].dt.quarter
melb_df['quarter']

0        1
1        2
2        2
3        2
4        2
        ..
13575    3
13576    3
13577    3
13578    3
13579    3
Name: quarter, Length: 13580, dtype: int32

In [8]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
 26  quarter          13580 non-null  int32
dtypes: datetime64[ns](1), float64(8), int32(1), int64(10), object(7)
memory usage: 2.7+ MB

In [9]:
melb_df['quarter'].value_counts()

quarter
3    4873
2    4359
4    2329
1    2019
Name: count, dtype: int64

Преобразуйте все столбцы, в которых меньше 150 уникальных значений, в тип данных category, исключив из преобразования столбцы Date, Rooms, Bedroom, Bathroom, Car.
В качестве ответа запишите результирующее количество столбцов, которые имеют тип данных category.

In [10]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца

In [11]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
 26  quarter          13580 non-null  category
dtypes: category(11), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

## Метод sort_values()

by — имя или список имён столбцов, по значениям которых производится сортировка.
axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка производится по строкам.
ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и сохраняет индексы изначальной таблицы.
inplace — производится ли замена исходной таблицы на отсортированную. По умолчанию параметр выставлен на False, то есть замены не производится. Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

### Сортировка по значениям одного столбца

In [104]:
melb_df.sort_values(by='Price').head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend,quarter
2652,Footscray,1,unit,85000.0,PI,Burnham,2016-03-09,6.4,3011,1,...,Western Metropolitan,7570,42.000000,1.000000,3,9,2,St,0,1
1805,other,4,house,131000.0,PI,other,2017-02-25,8.9,3162,4,...,Southern Metropolitan,2379,17.222222,-0.525994,2,97,5,St,1,1
7303,Albion,1,unit,145000.0,PI,Biggin,2016-05-28,13.9,3020,2,...,Western Metropolitan,2185,31.500000,0.555556,5,46,5,St,1,2
1927,Coburg,4,house,145000.0,PI,Jellis,2016-04-06,7.8,3058,3,...,Northern Metropolitan,11204,20.500000,-0.531429,4,106,2,Rd,0,2
7940,Hawthorn,1,unit,160000.0,VB,HAR,2017-08-04,4.6,3122,1,...,Southern Metropolitan,11308,42.000000,-0.437500,8,8,4,St,0,3

In [105]:
melb_df.sort_values(by='Date', ascending=False)

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend,quarter
11144,Northcote,4,house,1955000.0,SP,McGrath,2017-12-08,5.3,3070,4,...,Northern Metropolitan,11364,12.600000,0.923664,12,47,4,St,0,4
11217,Surrey Hills,3,house,1775000.0,PI,Jellis,2017-12-08,10.2,3127,3,...,Southern Metropolitan,5457,15.750000,-0.721854,12,47,4,Rd,0,4
11206,St Kilda,4,house,1600000.0,VB,Gary,2017-12-08,5.0,3182,4,...,Southern Metropolitan,13240,16.000000,-0.586028,12,107,4,St,0,4
11207,Strathmore,7,house,2000000.0,SP,Nelson,2017-12-08,8.2,3041,7,...,Western Metropolitan,3284,20.882353,-0.262721,12,18,4,Rd,0,4
11208,Strathmore,4,house,1610000.0,S,other,2017-12-08,8.2,3041,4,...,Western Metropolitan,3284,24.909091,-0.517181,12,62,4,St,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1555,Camberwell,4,house,2650000.0,S,Jellis,2016-03-09,7.8,3124,4,...,Southern Metropolitan,8920,18.900000,-0.550535,3,126,2,Rd,0,1
4510,Oak Park,3,house,892000.0,S,Nelson,2016-03-09,11.5,3046,3,...,Northern Metropolitan,2651,18.000000,-0.714609,3,46,2,St,0,1
4388,Northcote,3,house,1200000.0,S,Nelson,2016-03-09,5.5,3070,3,...,Northern Metropolitan,11364,17.857143,-0.264706,3,96,2,St,0,1
6184,Surrey Hills,3,house,1205000.0,S,Fletchers,2016-01-28,11.2,3127,3,...,Southern Metropolitan,5457,18.000000,-0.590909,1,46,3,Rd,0,1
6183,Surrey Hills,2,unit,813000.0,S,Fletchers,2016-01-28,11.2,3127,2,...,Southern Metropolitan,5457,25.200000,0.076923,1,46,3,Rd,0,1

### Сортировка по значениям нескольких столбцов

In [107]:
melb_df.sort_values(by=['Price', 'Distance',]).loc[::10, ['Distance', 'Price']]

       Distance      Price
2652        6.4    85000.0
7116        7.8   200000.0
5206       11.2   220000.0
7240        8.2   241000.0
2898       13.0   250000.0
...         ...        ...
13341       6.3  4060000.0
8591        1.5  4275000.0
1094       11.2  4700000.0
5801        6.1  5046000.0
251         6.3  5525000.0

[1358 rows x 2 columns]

### Комбинирование сортировки с фильтрацией

Предположим, компания McGrath поручила нам восстановить хронологию продаж таунхаусов, у которых площадь участка существенно больше площади здания, чтобы понять, как часто компания справляется с таким сложным видом объектов. Объекты, проданные в один и тот же день, мы бы хотели сортировать по значению коэффициента соотношения площадей. 

Найдём информацию о таунхаусах (Type), проданных компанией (SellerG) McGrath, у которых коэффициент соотношения площадей здания и участка (AreaRatio) меньше -0.8. Результат отсортируем по дате продажи (Date) в порядке возрастания, а после проведём сортировку по убыванию коэффициента соотношения площадей. Также обновим старые индексы на новые, установив параметр ignore_index на True. Для наглядности результата выберем из таблицы только столбцы Data и AreaRatio:

In [108]:
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

#### tasks

Произведите сортировку столбца AreaRatio по убыванию. После сортировки замените индексы таблицы на новые. Какое значение площади здания находится в строке 1558? Ответ округлите до целого числа.

In [111]:
melb_df.sort_values(by='AreaRatio', ascending=False, ignore_index=True).iloc[1558]

Suburb                       Elsternwick
Rooms                                  2
Type                               house
Price                           716000.0
Method                                 S
SellerG                    hockingstuart
Date                 2017-03-06 00:00:00
Distance                             7.2
Postcode                            3185
Bedroom                                2
Bathroom                               1
Car                                    1
Landsize                             0.0
BuildingArea                       126.0
CouncilArea                    Glen Eira
Lattitude                      -37.89438
Longtitude                     145.00851
Regionname         Southern Metropolitan
Propertycount                       4898
MeanRoomsSquare                     25.2
AreaRatio                            1.0
MonthSale                              3
AgeBuilding                           47
WeekdaySale                            0
StreetType                            St
Weekend                                0
quarter                                1
Name: 1558, dtype: object

Найдите таунхаусы (Type) с количеством жилых комнат (Rooms) больше 2. Отсортируйте полученную таблицу сначала по возрастанию числа комнат, а затем по убыванию средней площади комнат (MeanRoomsSquare). Индексы таблицы замените на новые. Какая цена будет у объекта в строке 18? Ответ запишите в виде целого числа.

In [114]:
mask1 = melb_df['Rooms'] > 2
mask2 = melb_df['Type'] == 'townhouse'
melb_df[mask1 & mask2].sort_values(
    by=['Rooms', 'MeanRoomsSquare'],
    ascending=[True, False],
    ignore_index=True
).iloc[18]

Suburb                     Brighton East
Rooms                                  3
Type                           townhouse
Price                          1300000.0
Method                                PI
SellerG                           Buxton
Date                 2016-09-17 00:00:00
Distance                            10.7
Postcode                            3187
Bedroom                                3
Bathroom                               2
Car                                    2
Landsize                           337.0
BuildingArea                       222.0
CouncilArea                      Bayside
Lattitude                       -37.9196
Longtitude                      145.0205
Regionname         Southern Metropolitan
Propertycount                       6938
MeanRoomsSquare                    27.75
AreaRatio                      -0.205725
MonthSale                              9
AgeBuilding                           16
WeekdaySale                            5
StreetType                            St
Weekend                                1
quarter                                3
Name: 18, dtype: object

## Метод groupby()

by — имя или список имён столбцов, по которым производится группировка.
axis — ось, по которой производится группировка (0 — строки, 1 — столбцы). По умолчанию группировка производится по строкам.
as_index — добавляется ли дополнительный индекс к таблице. По умолчанию установлен на True.

### Группировка данных по одному критерию с одной агрегацией

In [33]:
melb_df

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend,quarter
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,Northern Metropolitan,4019,25.200000,-0.231707,3,46,5,St,1,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,Northern Metropolitan,4019,15.800000,-0.327660,4,116,5,St,1,2
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,Northern Metropolitan,4019,18.750000,0.056338,4,117,0,St,0,2
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,Northern Metropolitan,4019,15.750000,0.145455,4,47,0,other,0,2
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,Northern Metropolitan,4019,17.750000,0.083969,4,2,2,St,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,other,4,house,1245000.0,S,Barry,2017-08-26,16.7,3150,4,...,South-Eastern Metropolitan,7392,12.600000,-0.676093,8,36,5,Cr,1,3
13576,Williamstown,3,house,1031000.0,SP,Williams,2017-08-26,6.8,3016,3,...,Western Metropolitan,6380,16.625000,-0.429185,8,22,5,Dr,1,3
13577,Williamstown,3,house,1170000.0,S,Raine,2017-08-26,6.8,3016,3,...,Western Metropolitan,6380,15.750000,-0.551601,8,20,5,St,1,3
13578,Williamstown,4,house,2500000.0,PI,Sweeney,2017-08-26,6.8,3016,4,...,Western Metropolitan,6380,17.444444,-0.693060,8,97,5,St,1,3
13579,Yarraville,4,house,1285000.0,SP,Village,2017-08-26,6.3,3013,4,...,Western Metropolitan,6543,12.444444,-0.527426,8,97,5,St,1,3

In [29]:
melb_df.groupby(by='Type', observed=True).mean(numeric_only=True)

,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,Lattitude,Longtitude,Propertycount,MeanRoomsSquare,AreaRatio,AgeBuilding
Type,,,,,,,,,,,,,,,
house,3.260874,1.242665e+06,10.979479,3104.080643,3.229336,1.613822,1.772674,617.181924,152.162553,-37.803795,144.994700,7259.025505,18.996731,-0.490031,55.669700
townhouse,2.837522,9.337351e+05,9.851346,3100.777379,2.814183,1.809695,1.555655,279.606822,134.649710,-37.815782,144.996489,7094.459605,18.569847,-0.094916,26.690305
unit,1.963871,6.051275e+05,7.607391,3110.797481,1.966523,1.183295,1.128936,477.314219,102.235863,-37.823710,144.996363,8199.280080,21.068242,0.319883,39.703016

In [31]:
melb_df.groupby(['Type'], observed=True)['Price'].mean()

Type
house        1.242665e+06
townhouse    9.337351e+05
unit         6.051275e+05
Name: Price, dtype: float64

In [35]:
melb_df.groupby(['Type'], observed=True)['Rooms'].mean()

Type
house        3.260874
townhouse    2.837522
unit         1.963871
Name: Rooms, dtype: float64

Теперь давайте выясним, какие регионы (Regionname) наиболее удалены от центра Мельбурна.

Для этого найдём минимальное значение расстояния от центра города до объекта в зависимости от его региона. Результат отсортируем по убыванию расстояния:

In [36]:
melb_df.groupby('Regionname', observed=True)['Distance'].min().sort_values(ascending=False)

Regionname
Western Victoria              29.8
Eastern Victoria              25.2
Northern Victoria             21.8
South-Eastern Metropolitan    14.7
Eastern Metropolitan           7.8
Western Metropolitan           4.3
Southern Metropolitan          0.7
Northern Metropolitan          0.0
Name: Distance, dtype: float64

### Группировка данных по одному критерию с несколькими агрегациями

Чтобы рассчитать несколько агрегирующих методов, можно воспользоваться методом agg(), который принимает список строк с названиями агрегаций.

In [38]:
melb_df.groupby('MonthSale', observed=True)['Price'].agg(
    ['count', 'mean', 'max']
).sort_values(by='count', ascending=False)

           count          mean        max
MonthSale
8           1850  1.056371e+06  6500000.0
7           1835  9.314698e+05  9000000.0
5           1644  1.097807e+06  8000000.0
6           1469  1.068981e+06  7650000.0
3           1408  1.146762e+06  5600000.0
4           1246  1.050479e+06  5500000.0
9           1188  1.126349e+06  6400000.0
10           854  1.135970e+06  6250000.0
11           750  1.142503e+06  5050000.0
12           725  1.144737e+06  5700000.0
2            333  1.169051e+06  4735000.0
1            278  9.397921e+05  5200000.0

In [43]:
melb_df.groupby('MonthSale', observed=True)['Price'].agg('describe').sort_values(by='count', ascending=False)

,count,mean,std,min,25%,50%,75%,max
MonthSale,,,,,,,,
8,1850.0,1.056371e+06,619617.476541,160000.0,635000.0,892000.0,1310000.0,6500000.0
7,1835.0,9.314698e+05,537390.803161,190000.0,586750.0,800000.0,1150000.0,9000000.0
5,1644.0,1.097807e+06,668492.867996,145000.0,650000.0,905000.0,1371250.0,8000000.0
6,1469.0,1.068981e+06,606010.069052,222000.0,660000.0,900000.0,1325000.0,7650000.0
3,1408.0,1.146762e+06,709573.596867,85000.0,680000.0,945000.0,1400000.0,5600000.0
4,1246.0,1.050479e+06,591892.902979,145000.0,655000.0,905500.0,1298750.0,5500000.0
9,1188.0,1.126349e+06,608734.690742,170000.0,725000.0,980000.0,1360000.0,6400000.0
10,854.0,1.135970e+06,692950.251627,250000.0,652625.0,950000.0,1416500.0,6250000.0
11,750.0,1.142503e+06,703666.227892,240000.0,671750.0,950000.0,1399125.0,5050000.0
12,725.0,1.144737e+06,706549.007161,250000.0,667500.0,938000.0,1412000.0,5700000.0
2,333.0,1.169051e+06,671564.357417,131000.0,710000.0,1020000.0,1478000.0,4735000.0
1,278.0,9.397921e+05,577668.924214,170000.0,570500.0,795000.0,1111250.0,5200000.0

После базовых математических функций наиболее частым агрегированием является подсчёт числа уникальных значений. Так, например, мы можем вычислить число уникальных риелторских компаний в зависимости от региона, чтобы понять, в каких регионах конкуренция на рынке недвижимости меньше. Это можно сделать, передав в параметр метода agg() строку 'nunique'. 

Более того, метод agg() поддерживает использование и других функций. Передадим дополнительно встроенную функцию set, чтобы получить множество из агентств недвижимости, которые работают в каждом из регионов:

In [45]:
melb_df.groupby('Regionname', observed=True)['SellerG'].agg(
    		['nunique', set]
)

,nunique,set
Regionname,,
Eastern Metropolitan,26,"{Marshall, RW, Barry, RT, Buxton, Love, Gary, ..."
Eastern Victoria,11,"{hockingstuart, Eview, McGrath, Fletchers, oth..."
Northern Metropolitan,40,"{Eview, LITTLE, Rendina, Burnham, Marshall, Al..."
Northern Victoria,11,"{hockingstuart, YPA, LITTLE, HAR, McGrath, Rai..."
South-Eastern Metropolitan,25,"{Eview, RW, Barry, Buxton, Gary, Hodges, Nelso..."
Southern Metropolitan,38,"{Eview, LITTLE, Rendina, Marshall, RW, Barry, ..."
Western Metropolitan,34,"{Rendina, Burnham, Alexkarbon, RW, Barry, RT, ..."
Western Victoria,6,"{hockingstuart, YPA, Raine, other, HAR, Ray}"

### tasks

Сгруппируйте данные по признаку количества комнат и найдите среднюю цену объектов недвижимости в каждой группе. В качестве ответа запишите количество комнат, для которых средняя цена наибольшая.

In [58]:
melb_df.groupby('Rooms', observed=True)['Price'].agg('describe').sort_values(by='mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
Rooms,,,,,,,,
7,10.0,1.920700e+06,9.476201e+05,1005000.0,1312500.0,1496000.0,2450000.0,4050000.0
5,596.0,1.870260e+06,9.823493e+05,355000.0,1150000.0,1660000.0,2400000.0,8000000.0
6,67.0,1.849366e+06,1.094247e+06,506000.0,1167500.0,1800000.0,2125000.0,6500000.0
8,8.0,1.602750e+06,8.306264e+05,741000.0,853250.0,1515000.0,2212500.0,2950000.0
4,2688.0,1.445282e+06,7.474872e+05,131000.0,902000.0,1285000.0,1786250.0,7650000.0
3,5881.0,1.076081e+06,5.021061e+05,283000.0,725000.0,950000.0,1320000.0,9000000.0
10,1.0,9.000000e+05,NaN,900000.0,900000.0,900000.0,900000.0,900000.0
2,3648.0,7.750812e+05,3.561259e+05,190000.0,535000.0,690000.0,912625.0,4800000.0
1,681.0,4.338245e+05,2.249857e+05,85000.0,325000.0,385000.0,460000.0,2450000.0

Какой регион имеет наименьшее стандартное отклонение по географической широте (Lattitude)?

In [59]:
melb_df.groupby('Regionname', observed=True)['Lattitude'].describe().sort_values(by='std', ascending=True)

,count,mean,std,min,25%,50%,75%,max
Regionname,,,,,,,,
Western Victoria,32.0,-37.695163,0.011579,-37.71691,-37.702827,-37.695075,-37.687370,-37.67344
Southern Metropolitan,4695.0,-37.866981,0.043080,-37.99035,-37.901200,-37.858800,-37.835670,-37.78142
Eastern Metropolitan,1471.0,-37.788820,0.047890,-37.90383,-37.823185,-37.777000,-37.751800,-37.68508
Northern Metropolitan,3890.0,-37.747258,0.049639,-37.93940,-37.785100,-37.753380,-37.713625,-37.56857
Western Metropolitan,2948.0,-37.782382,0.051251,-37.91859,-37.811885,-37.780400,-37.750275,-37.56005
South-Eastern Metropolitan,450.0,-37.993727,0.073411,-38.18255,-38.028280,-37.981155,-37.931123,-37.89210
Northern Victoria,41.0,-37.599620,0.084455,-37.68503,-37.672770,-37.638260,-37.507330,-37.40853
Eastern Victoria,53.0,-37.959292,0.147067,-38.16439,-38.070540,-38.026210,-37.788830,-37.75735

Какая риелторская компания (SellerG) имеет наименьшую общую выручку за период с 1 мая по 1 сентября (включительно) 2017 года?
Для ответа на этот вопрос рассчитайте сумму продаж (Price) каждой компании в заданный период.
Не забудьте перевести даты в формат datetime.

Подсказка (1 из 3): Произведите фильтрацию по условию попадания данных о продажах в интервал указанных дат.
Подсказка (2 из 3): Сгруппируйте данные по признаку SellerG и посчитайте сумму продаж для каждой компании.
Подсказка (3 из 3): Отсортируйте данные по возрастанию.

In [102]:
min_date = pd.to_datetime('2017-05-01')
max_date = pd.to_datetime('2017-09-02')
melb_in_period = melb_df[melb_df['Date'].between(min_date, max_date)]
melb_in_period.groupby('SellerG', observed=True)['Price'].sum().sort_values(ascending=True)

SellerG
LITTLE             2742000.0
Cayzer             4439000.0
Burnham            4550500.0
Moonee             7328000.0
Thomson            8332000.0
Bells              8656000.0
Alexkarbon        10985000.0
McDonald          14637500.0
Rendina           15422276.0
Nick              16890000.0
Douglas           18341000.0
Buckingham        19033000.0
C21               19515000.0
Eview             19791500.0
Collins           20217000.0
Philip            22051800.0
Chisholm          23225000.0
Williams          23297000.0
Love              23365500.0
Purplebricks      23401000.0
O'Brien           23855508.0
HAR               25568000.0
Village           26473000.0
RW                29261000.0
Raine             30687700.0
Stockdale         35409800.0
Sweeney           36882750.0
Gary              39138400.0
Hodges            43231000.0
YPA               46354350.0
Miles             47582000.0
Kay               48569500.0
RT                50498000.0
Brad              55955000.0
Jas               59281600.0
Harcourts         68720250.0
McGrath           78386500.0
Greg              85621000.0
Woodards          85977500.0
Noel              88129800.0
Fletchers        108847700.0
Biggin           110429500.0
Buxton           219104000.0
Ray              249572986.0
Marshall         253957888.0
hockingstuart    282834310.0
Barry            296723050.0
other            365038432.0
Nelson           379767500.0
Jellis           414121833.0
Name: Price, dtype: float64

## 5/12   Сводные таблицы

### Метод pivot_table для построения сводных таблиц

values — имя столбца, по которому необходимо получить сводные данные, применяя агрегирующую функцию;
index — имя столбца, значения которого станут строками сводной таблицы;
columns — имя столбца, значения которого станут столбцами сводной таблицы;
aggfunc — имя или список имён агрегирующих функций (по умолчанию — подсчёт среднего, 'mean');
fill_value — значение, которым необходимо заполнить пропуски (по умолчанию пропуски не заполняются).

In [116]:
melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0,
    observed=True,
).round()

Type       house  townhouse       unit
Rooms
1       866866.0   592705.0   389929.0
2      1017238.0   710158.0   610491.0
3      1109233.0   984709.0   850596.0
4      1462283.0  1217092.0  1037476.0
5      1877327.0  1035000.0        0.0
6      1869508.0        0.0   520000.0
7      1920700.0        0.0        0.0
8      1510286.0        0.0  2250000.0
10      900000.0        0.0        0.0

In [117]:
melb_df.pivot_table(
    values='Price',
    index='Regionname',
    columns='Weekend',
    aggfunc='count',
    observed=True,
)

Weekend                        0     1
Regionname
Eastern Metropolitan         447  1024
Eastern Victoria              13    40
Northern Metropolitan       1258  2632
Northern Victoria             11    30
South-Eastern Metropolitan   123   327
Southern Metropolitan       1534  3161
Western Metropolitan         960  1988
Western Victoria               8    24

Разберём ещё один пример: найдём, как зависит средняя и медианная площадь участка (Landsize) от типа объекта (Type) и его региона (Regionname). Чтобы посмотреть несколько статистических параметров, нужно передать в аргумент aggfunc список из агрегирующих функций. Построим такую сводную таблицу, где пропущенные значения заменим на 0:

In [118]:
melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0,
    observed=True,
)

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

### Многомерные сводные таблицы

Для того чтобы исследовать зависимость от большего числа признаков, можно передать список признаков в параметр index или параметр columns.

Давайте построим таблицу, в которой по индексам будут располагаться признаки метода продажи (Method) и типа объекта (Type), по столбцам — наименование региона (Regionname), а на пересечении строк и столбцов будет стоять медианная цена объекта (Price):

In [135]:
melb_df.pivot_table(
    values='Price',
    index=['Method','Type'],
    columns='Regionname',
    aggfunc='median',
    fill_value=0,
    observed=True,
)

Regionname        Eastern Metropolitan  Eastern Victoria  \
Method Type
PI     house                 1244000.0          780000.0
       townhouse              760000.0               0.0
       unit                   650000.0               0.0
S      house                 1127000.0          675000.0
       townhouse              828000.0               0.0
       unit                   645750.0          492000.0
SA     house                  932500.0          950000.0
       townhouse              807500.0               0.0
       unit                        0.0               0.0
SP     house                 1050000.0          672500.0
       townhouse              910000.0               0.0
       unit                   515000.0          400000.0
VB     house                 1100000.0          712500.0
       townhouse              892500.0               0.0
       unit                   500000.0               0.0

Regionname        Northern Metropolitan  Northern Victoria  \
Method Type
PI     house                   900000.0           500000.0
       townhouse               632500.0                0.0
       unit                    410000.0                0.0
S      house                   920000.0           555000.0
       townhouse               750000.0                0.0
       unit                    525500.0                0.0
SA     house                   817500.0           540000.0
       townhouse               425000.0                0.0
       unit                    616000.0                0.0
SP     house                   900000.0           521000.0
       townhouse               690000.0                0.0
       unit                    470000.0                0.0
VB     house                  1050000.0           690000.0
       townhouse               640000.0                0.0
       unit                    450000.0                0.0

Regionname        South-Eastern Metropolitan  Southern Metropolitan  \
Method Type
PI     house                        865000.0              1725000.0
       townhouse                   1190000.0              1055000.0
       unit                         525000.0               571250.0
S      house                        883300.0              1611000.0
       townhouse                    875000.0              1135000.0
       unit                         606000.0               655000.0
SA     house                        880000.0              1390000.0
       townhouse                         0.0              1141000.0
       unit                              0.0               580000.0
SP     house                        770000.0              1521750.0
       townhouse                    800000.0              1162500.0
       unit                         601000.0               550000.0
VB     house                        850000.0              1800000.0
       townhouse                         0.0              1250000.0
       unit                         700000.0               500000.0

Regionname        Western Metropolitan  Western Victoria
Method Type
PI     house                  870000.0          630000.0
       townhouse              670000.0               0.0
       unit                   360000.0               0.0
S      house                  870000.0          397500.0
       townhouse              729000.0               0.0
       unit                   489000.0               0.0
SA     house                  772500.0               0.0
       townhouse              467500.0               0.0
       unit                   571000.0               0.0
SP     house                  865000.0          360000.0
       townhouse              702500.0               0.0
       unit                   460000.0               0.0
VB     house                  880000.0               0.0
       townhouse              689500.0               0.0
       unit                   420000.0               0.0

In [136]:
pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0,
    observed = True,
)
pivot

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [137]:
pivot.columns

MultiIndex([('median',     'house'),
            ('median', 'townhouse'),
            ('median',      'unit'),
            (  'mean',     'house'),
            (  'mean', 'townhouse'),
            (  'mean',      'unit')],
           names=[None, 'Type'])

In [138]:
pivot['mean']['unit']

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: unit, dtype: float64

In [139]:
mask = pivot['mean']['house'] < pivot['median']['house']
filtered_pivot = pivot[mask]
display(filtered_pivot)

                      median                        mean              \
Type                   house townhouse  unit       house   townhouse
Regionname
Southern Metropolitan  586.0     246.0   0.0  569.643881  278.858824
Western Metropolitan   531.0     198.0  62.0  507.883406  244.560669


Type                         unit
Regionname
Southern Metropolitan  466.380245
Western Metropolitan   557.637232

Чтобы получить индексы отфильтрованной таблицы, можно воспользоваться атрибутом index и обернуть результат в список:

In [140]:
list(filtered_pivot.index)

['Southern Metropolitan', 'Western Metropolitan']

### tasks

Составьте сводную таблицу, которая показывает зависимость медианной площади (BuildingArea) здания от типа объекта недвижимости (Type) и количества жилых комнат в доме (Rooms). Для какой комбинации признаков площадь здания наибольшая?
В качестве ответа запишите эту комбинацию (тип здания, число комнат) через запятую, без пробелов.

In [147]:
melb_df.pivot_table(
    values='BuildingArea',
    index=['Type',],
    columns='Rooms',
    aggfunc='median',
    #fill_value=False,
    observed=True,
)

Rooms         1      2      3      4      5      6      7      8      10
Type
house      126.0  126.0  126.0  141.0  177.0  126.0  216.5  126.0  126.0
townhouse   88.0  114.0  126.0  159.5  152.0    NaN    NaN    NaN    NaN
unit        69.5  110.0  126.0  126.0    NaN  171.0    NaN  126.0    NaN

Составьте сводную таблицу, которая показывает зависимость медианной цены объекта недвижимости (Price) от риелторского агентства (SellerG) и типа здания (Type).
Во вновь созданной таблице найдите агентство, у которого медианная цена для зданий типа unit максимальна. В качестве ответа запишите название этого агентства.

In [150]:
melb_df.pivot_table(
    values='Price',
    index=['SellerG',],
    columns='Type',
    aggfunc='median',
    #fill_value=False,
    observed=True,
).sort_values(by='unit', ascending=False).head()

Type          house  townhouse      unit
SellerG
Nick      2025000.0   780000.0  900000.0
Marshall  1975000.0  1408500.0  715000.0
Cayzer    1505000.0  1450000.0  707500.0
Kay       2220000.0  1365000.0  695000.0
Noel      1400500.0   990000.0  693250.0

In [104]:
melb_df.sort_values(by='Price').head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend,quarter
2652,Footscray,1,unit,85000.0,PI,Burnham,2016-03-09,6.4,3011,1,...,Western Metropolitan,7570,42.000000,1.000000,3,9,2,St,0,1
1805,other,4,house,131000.0,PI,other,2017-02-25,8.9,3162,4,...,Southern Metropolitan,2379,17.222222,-0.525994,2,97,5,St,1,1
7303,Albion,1,unit,145000.0,PI,Biggin,2016-05-28,13.9,3020,2,...,Western Metropolitan,2185,31.500000,0.555556,5,46,5,St,1,2
1927,Coburg,4,house,145000.0,PI,Jellis,2016-04-06,7.8,3058,3,...,Northern Metropolitan,11204,20.500000,-0.531429,4,106,2,Rd,0,2
7940,Hawthorn,1,unit,160000.0,VB,HAR,2017-08-04,4.6,3122,1,...,Southern Metropolitan,11308,42.000000,-0.437500,8,8,4,St,0,3