# Begin

In [1]:
import pandas as pd

In [2]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

In [3]:
countries_df

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [4]:
countries_df.index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [5]:
countries_df = pd.DataFrame(
    data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Украина', 45.5, 603628],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
    columns = ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

# 4/12   Pandas.DataFrame task 3.5

Вы работаете аналитиком в компании ScienceYou. Ваша задача — проанализировать чистую прибыль.

Доходы (income), расходы (expenses) и годы (years), соответствующие им, предоставлены вам в виде списков.

Создайте функцию create_companyDF(income, expenses, years), которая возвращает DataFrame, составленный из входных данных со столбцами Income и Expenses и индексами, соответствующими годам рассматриваемого периода.

Пример такого DataFrame представлен ниже.

    Income  Expenses
2018    478     156
2019    512     130
2020    196     270

Также напишите функцию get_profit(df, year), которая возвращает разницу между доходом и расходом, записанными в таблице df, за год year.

Примечание. Если информация за запрашиваемый год не указана в вашей таблице, вам необходимо вернуть None.

Примечание. Не забудьте ипортировать библиотеки.

In [56]:
import pandas as pd


def create_companyDF(income, expenses, years):
    df = pd.DataFrame({
    'Income': income,
    'Expenses': expenses,
    })
    df.index = years
    return df


def get_profit(df, year):
    
    if year in df.index:
        profit = df.loc[year, 'Income'] - df.loc[year, 'Expenses']
    else:
        profit = None
    
    return profit

In [62]:
print(get_profit(df,2018))

322

In [54]:
income = [478, 512, 196]
expenses = [156, 130, 270]
years = [2018, 2019, 2020]
df = create_companyDF(income, expenses, years)

In [66]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df.to_csv('countries.csv', index=False, sep=';')

In [68]:
countries_data = pd.read_csv('countries.csv', sep=';')
display(countries_data)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

# 6/12   Знакомимся с данными: недвижимость

In [5]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [4]:
melb_data.describe()

,index,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000
mean,6789.500000,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.611856,558.416127,139.633972,1966.788218,-37.809203,144.995216,7454.417378
std,3920.352663,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.960793,3990.669241,392.217403,29.088642,0.079260,0.103916,4378.581772
min,0.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,3394.750000,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,122.000000,1960.000000,-37.856822,144.929600,4380.000000
50%,6789.500000,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,10184.250000,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,129.940000,1975.000000,-37.756400,145.058305,10331.000000
max,13579.000000,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [83]:
melb_data

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,"-37.8072, 144.9941"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,652.0,126.0,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,"-37.90562, 145.16761"
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0,"-37.85927, 144.87904"
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4.0,436.0,126.0,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0,"-37.85274, 144.88738"
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,"-37.81188, 144.88449"

In [113]:
melb_data.loc[3552, 'Landsize'] / melb_data.loc[1690, 'Landsize']

2.511904761904762

In [115]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  object
dtypes: float64(11), int64(3), object(9)
memory usage: 2.4+ MB

In [117]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [121]:
melb_data.describe().loc[:, ['Distance', 'BuildingArea', 'Price']]

           Distance  BuildingArea         Price
count  13580.000000  13580.000000  1.358000e+04
mean      10.137776    139.633972  1.075684e+06
std        5.868725    392.217403  6.393107e+05
min        0.000000      0.000000  8.500000e+04
25%        6.100000    122.000000  6.500000e+05
50%        9.200000    126.000000  9.030000e+05
75%       13.000000    129.940000  1.330000e+06
max       48.100000  44515.000000  9.000000e+06

In [135]:
melb_data.describe(include=['object'] ).loc[:, ['Type']]

         Type
count   13580
unique      3
top         h
freq     9449

In [137]:
melb_data['Type'].value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [139]:
1114 / 13580 * 100

8.203240058910161

In [125]:
melb_data.isnull().sum()

index               0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom             0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
Coordinates         0
dtype: int64

In [169]:
melb_data['Bedroom'].mode()

0    3
Name: Bedroom, dtype: int64

In [143]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [149]:
melb_data.describe().loc[:, 'Propertycount']

count    13580.000000
mean      7454.417378
std       4378.581772
min        249.000000
25%       4380.000000
50%       6555.000000
75%      10331.000000
max      21650.000000
Name: Propertycount, dtype: float64

In [151]:
melb_data.head().loc[:, 'Propertycount']

0    4019
1    4019
2    4019
3    4019
4    4019
Name: Propertycount, dtype: int64

In [153]:
landsize_median = melb_data['Landsize'].median() 
landsize_mean =  melb_data['Landsize'].mean()
print(abs(landsize_median - landsize_mean)/landsize_mean)
# 0.21205713983546193

0.21205713983546193

In [167]:
b_median = melb_data['BuildingArea'].median() 
b_mean =  melb_data['BuildingArea'].mean()
print(abs(b_median - b_mean)/b_mean)
# 0.21205713983546193

0.09764079662364533

In [159]:
melb_data['BuildingArea'].median()

126.0

In [165]:
melb_data['BuildingArea'].mean()

139.63397229013256

# 9/12   Фильтрация данных в DataFrame

In [46]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [47]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [11]:
melb_data[melb_data['Bathroom'] == 0].shape[0]

34

In [50]:
melb_data['Type'].describe()

count     13580
unique        3
top           h
freq       9449
Name: Type, dtype: object

In [18]:
melb_data[melb_data['SellerG'] == 'Nelson'].shape[0]

1565

In [23]:
melb_data[melb_data['Price'] > 3_000_000].shape[0]

221

In [25]:
melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3_000_000)].shape[0]

5

In [28]:
melb_data[melb_data['BuildingArea'] == 0]['Price'].min()

412500.0

Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, в которых либо количество комнат больше пяти, либо здание моложе 2015 года?

In [39]:
price = melb_data['Price'] < 1_000_000
room = melb_data['Rooms'] > 5
year = melb_data['YearBuilt'] > 2015
mask = price & (room | year)
melb_data[mask]['Price'].mean()

769238.6363636364

В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?

In [53]:
price = melb_data['Price'] < 3_000_000
type = melb_data['Type'] == 'h'
mask = price & type

In [66]:
melb_data[mask]['Regionname'].value_counts()

Regionname
Northern Metropolitan         2737
Southern Metropolitan         2520
Western Metropolitan          2286
Eastern Metropolitan          1167
South-Eastern Metropolitan     387
Eastern Victoria                50
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [65]:
melb_data[mask].describe(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname,Coordinates
count,9220,9220,9220,9220,9220,9220,7999,9220,9220
unique,313,9075,1,5,232,58,33,8,9160
top,Reservoir,2 Bruce St,h,S,Nelson,27/05/2017,Moreland,Northern Metropolitan,"-37.74635, 144.9229"
freq,253,3,9220,6367,1154,334,842,2737,2

In [64]:
melb_data[mask].groupby('Regionname').count()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Propertycount,Coordinates
Regionname,,,,,,,,,,,,,,,,,,,,,
Eastern Metropolitan,1167,1167,1167,1167,1167,1167,1167,1167,1167,1167,...,1167,1167,1167,1167,1167,943,1167,1167,1167,1167
Eastern Victoria,50,50,50,50,50,50,50,50,50,50,...,50,50,50,50,50,41,50,50,50,50
Northern Metropolitan,2737,2737,2737,2737,2737,2737,2737,2737,2737,2737,...,2737,2737,2737,2737,2737,2436,2737,2737,2737,2737
Northern Victoria,41,41,41,41,41,41,41,41,41,41,...,41,41,41,41,41,26,41,41,41,41
South-Eastern Metropolitan,387,387,387,387,387,387,387,387,387,387,...,387,387,387,387,387,272,387,387,387,387
Southern Metropolitan,2520,2520,2520,2520,2520,2520,2520,2520,2520,2520,...,2520,2520,2520,2520,2520,2233,2520,2520,2520,2520
Western Metropolitan,2286,2286,2286,2286,2286,2286,2286,2286,2286,2286,...,2286,2286,2286,2286,2286,2023,2286,2286,2286,2286
Western Victoria,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,25,32,32,32,32

# Модуль 4. Базовые приёмы работы с данными в Pandas

## melb_data

In [3]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
melb_data.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [4]:
melb_data.shape

(13580, 23)

In [65]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [21]:
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

За удаление строк и столбцов в таблице отвечает метод drop().

Кликните на плашку, чтобы увидеть информацию ↓

Основные параметры метода drop()

labels — порядковые номера или имена столбцов, которые подлежат удалению; если их несколько, то передаётся список;
axis — ось совершения операции, axis=0 — удаляются строки, axis=1 — удаляются столбцы;
inplace — если параметр выставлен на True, происходит замена изначального DataFrame на новый, при этом метод ничего не возвращает; если на False — возвращается копия DataFrame, из которой удалены указанные строки (столбцы), при этом первоначальный DataFrame не изменяется; по умолчанию парамр раве


н False.
Удалим столбцы index и Coordinates из таблицы с помощью метода drop(). Выведем первые пять строк таблицы и убедимся, что всё прошло успешно.

In [6]:
melb_df = melb_df.drop(['index', 'Coordinates'], axis=1)
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067,...,1,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067,...,1,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067,...,2,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067,...,2,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067,...,1,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

Альтернативный вариант:

In [ ]:
melb_df.drop(['index','Coordinates'],axis=1,inplace=True)
melb_df.head()

In [7]:
total_rooms = melb_df['Rooms'] + melb_df['Bedroom'] + melb_df['Bathroom']
display(total_rooms)

0         5
1         5
2         8
3         8
4         8
         ..
13575    10
13576     8
13577     8
13578     9
13579     9
Length: 13580, dtype: int64

А теперь введём признак MeanRoomsArea, который соответствует средней площади одной комнаты для каждого объекта. Для этого разделим площадь здания на полученное ранее общее количество комнат:

In [8]:
melb_df['MeanRoomsArea'] = melb_df['BuildingArea'] / total_rooms
display(melb_df['MeanRoomsArea'])

0        25.200000
1        15.800000
2        18.750000
3        15.750000
4        17.750000
           ...
13575    12.600000
13576    16.625000
13577    15.750000
13578    17.444444
13579    12.444444
Name: MeanRoomsArea, Length: 13580, dtype: float64

Можно ввести ещё один интересный признак — AreaRatio, коэффициент соотношения площади здания (BuildingArea) и площади участка (Landsize). Для этого разницу двух площадей поделим на их сумму:

In [9]:
diff_area = melb_df['BuildingArea'] - melb_df['Landsize']
sum_area = melb_df['BuildingArea'] + melb_df['Landsize']
melb_df['AreaRatio'] = diff_area/sum_area
display(melb_df['AreaRatio'])

0       -0.231707
1       -0.327660
2        0.056338
3        0.145455
4        0.083969
           ...
13575   -0.676093
13576   -0.429185
13577   -0.551601
13578   -0.693060
13579   -0.527426
Name: AreaRatio, Length: 13580, dtype: float64

Что показывает такой коэффициент? Если присмотреться, можно увидеть, что AreaRatio лежит в интервале от -1 до 1.

Рассмотрим три случая, чтобы понять его значение:

Если рассматриваемые площади равны, то числитель дроби зануляется и коэффициент тоже равен 0.
Если одна из площадей начинает доминировать над другой, то коэффициент начинает расти в отрицательную сторону, если площадь участка больше площади здания, и в положительную сторону, если наоборот.
Наконец, в предельном случае, если площадь здания равна 0, то числитель дроби равен знаменателю со знаком минус, а коэффициент равен -1, а если площадь участка равна 0, то числитель дроби равен знаменателю со знаком плюс, а коэффициент равен 1.
Таким образом, значение в столбце AreaRatio служит своеобразным указателем соотношения площадей объекта недвижимости. Для пустырей — участков без строений — он будет равен -1, для домов без территории — 1, во всех остальных случаях мы можем увидеть, какая площадь больше — здания или участка.

### 4/10   Работа с датами в DataFrame

In [10]:
display(melb_df['Date'])

0         3/12/2016
1         4/02/2016
2         4/03/2017
3         4/03/2017
4         4/06/2016
            ...
13575    26/08/2017
13576    26/08/2017
13577    26/08/2017
13578    26/08/2017
13579    26/08/2017
Name: Date, Length: 13580, dtype: object

In [12]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'], dayfirst=True)
display(melb_df['Date'])

0       2016-12-03
1       2016-02-04
2       2017-03-04
3       2017-03-04
4       2016-06-04
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [13]:
years_sold = melb_df['Date'].dt.year
print(years_sold)
print('Min year sold:', years_sold.min())
print('Max year sold:', years_sold.max())
print('Mode year sold:', years_sold.mode()[0])

0        2016
1        2016
2        2017
3        2017
4        2016
         ...
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int32
Min year sold: 2016
Max year sold: 2017
Mode year sold: 2017

In [16]:
melb_df['MonthSale'] = melb_df['Date'].dt.month
melb_df['MonthSale'].value_counts(normalize=True)

MonthSale
5     0.149411
7     0.145950
9     0.135862
6     0.134757
8     0.114138
11    0.082032
4     0.069882
3     0.049926
12    0.044698
10    0.040574
2     0.032622
1     0.000147
Name: proportion, dtype: float64

In [17]:
melb_df['AgeBuilding'] = melb_df['Date'].dt.year - melb_df['YearBuilt']
display(melb_df['AgeBuilding'])

0         46
1        116
2        117
3         47
4          2
        ...
13575     36
13576     22
13577     20
13578     97
13579     97
Name: AgeBuilding, Length: 13580, dtype: int64

На самом деле столбец AgeBuilding дублирует информацию столбца YearBuilt, так как, зная год постройки здания, мы автоматически знаем его возраст. Такие признаки не стоит оставлять вместе, поэтому оставим возраст здания, так как он является более наглядным, а год постройки удалим из таблицы:

In [18]:
melb_df = melb_df.drop('YearBuilt', axis=1)

Создайте в таблице melb_df признак WeekdaySale (день недели). Найдите, сколько объектов недвижимости было продано в выходные (суббота и воскресенье), результат занесите в переменную weekend_count. В качестве ответа введите результат вывода переменной weekend_count.

In [19]:
melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
melb_df['WeekdaySale'].value_counts()

WeekdaySale
5    11759
6     1063
0      597
1      133
3       28
Name: count, dtype: int64

In [20]:
weekend_count = melb_df[(melb_df['WeekdaySale'] == 6) | (melb_df['WeekdaySale'] == 5)].shape[0]
weekend_count

12822

## ufo dataset task
Вводные данные для выполнения заданий 3.4-3.5

Вам представлены данные (в формате csv) об отчётах очевидцев НЛО в США за период с 1930 по 2020 год.

В данных есть следующие признаки:

"City" — город, где был замечен НЛО;
"Colors Reported" — цвет объекта;
"Shape Reported" — форма объекта;
"State" — обозначение штата;
"Time" — время, когда был замечен НЛО (данные отсортированы от старых наблюдений к новым). 
Прочитайте данные, сделайте преобразование времени к формату datetime и выполните задания ниже.

In [89]:
import pandas as pd

ufo_data = pd.read_csv('data/ufo.txt', sep=',')
ufo_data.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [158]:
ufo_df = ufo_data.copy()
ufo_df.describe()

           City Colors Reported Shape Reported  State              Time
count     18215            2882          15597  18241             18241
unique     6475              27             27     52             16145
top     Seattle             RED          LIGHT     CA  11/16/1999 19:00
freq        187             780           2803   2529                27

In [159]:
ufo_df['Date'] = pd.to_datetime(ufo_df['Time'])
ufo_df.drop('Time', axis=1, inplace=True)
ufo_df.head()

,City,Colors Reported,Shape Reported,State,Date
0,Ithaca,NaN,TRIANGLE,NY,1930-06-01 22:00:00
1,Willingboro,NaN,OTHER,NJ,1930-06-30 20:00:00
2,Holyoke,NaN,OVAL,CO,1931-02-15 14:00:00
3,Abilene,NaN,DISK,KS,1931-06-01 13:00:00
4,New York Worlds Fair,NaN,LIGHT,NY,1933-04-18 19:00:00

In [160]:
year = ufo_df['Date'].dt.year
weekday = ufo_df['Date'].dt.dayofweek
hour = ufo_df['Date'].dt.hour
year.value_counts(normalize=True)

Date
1999    0.152075
2000    0.144455
1998    0.095554
1995    0.073680
1997    0.067814
          ...
1936    0.000110
1930    0.000110
1935    0.000055
1934    0.000055
1933    0.000055
Name: proportion, Length: 68, dtype: float64

Найдите средний интервал времени (в днях) между двумя последовательными случаями наблюдения НЛО в штате Невада (NV).

In [163]:
ufo_df[ufo_df['State'] == 'NV'].head()

           City Colors Reported Shape Reported State                Date
76    Las Vegas             NaN           DISK    NV 1947-07-15 10:00:00
172  Nellis AFB             NaN           DISK    NV 1952-02-17 18:00:00
565      Fallon             NaN           OVAL    NV 1959-09-15 00:00:00
566   Goldfield             NaN          LIGHT    NV 1959-09-15 01:00:00
613         NaN             NaN           DISK    NV 1960-07-01 12:00:00

In [164]:
dates_NV = ufo_df[ufo_df['State'] == 'NV']['Date']

In [165]:
delta_days = dates_NV.diff()
delta_days.mean()

Timedelta('68 days 22:19:49.399293286')

#### Задание 2.3 (External resource)

Напишите функцию delete_columns(df, col=[]), которая удаляет столбцы из DataFrame и возвращает новую таблицу. Если одного из указанных столбцов не существует в таблице, то функция должна возвращать None.

Пример DataFrame:

In [60]:
customer_df = pd.DataFrame({
            'number': [0, 1, 2, 3, 4],
            'cust_id': [128, 1201, 9832, 4392, 7472],
            'cust_age': [13, 21, 19, 21, 60],
            'cust_sale': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
            'cust_order': [1400, 14142, 900, 1240, 8430]
        })
customer_df

   number  cust_id  cust_age  cust_sale  cust_year_birth  cust_order
0       0      128        13       0.00             2008        1400
1       1     1201        21       0.00             2000       14142
2       2     9832        19       0.20             2002         900
3       3     4392        21       0.15             2000        1240
4       4     7472        60       0.30             1961        8430

In [61]:
import pandas as pd

def delete_columns(df=pd.DataFrame(), col=[]):
    headers_list = df.columns.tolist()
    for el in col:
        if el not in headers_list:
            return None
    df.drop(col, axis=1, inplace=True)
    return df

In [62]:
print(delete_columns(col = ['cust_sale'], df = customer_df))

   number  cust_id  cust_age  cust_year_birth  cust_order
0       0      128        13             2008        1400
1       1     1201        21             2000       14142
2       2     9832        19             2002         900
3       3     4392        21             2000        1240
4       4     7472        60             1961        8430

### Задание 2.4

Задан DataFrame countries_df, содержащий следующие столбцы: название страны, население (population) в миллионах человек и площадь страны (area) в квадратных километрах.

In [93]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

In [95]:
density = countries_df['population'] * 1_000_000 / countries_df['area']

In [101]:
density.mean()

84.93080566562001

## 5/10   Создание и преобразование столбцов с помощью функций

Представьте, что вы занимаетесь подготовкой данных о вакансиях с платформы hh.ru. В вашем распоряжении имеется таблица, в которой с помощью парсинга собраны резюме кандидатов. В этой таблице есть текстовый столбец «Опыт работы». Пример такого столбца представлен ниже в виде объекта Series. Структура текста в столбце фиксирована и не может измениться.

Напишите функцию get_experience(arg), аргументом которой является строка столбца с опытом работы. Функция должна возвращать опыт работы в месяцах. Не забудьте привести результат к целому числу.

Примечание. Обратите внимание, что опыт работы может выражаться только в годах или только в месяцах. Учтите это при построении своей функции.

При проверке мы будем применять вашу функцию к разным Series с помощью метода apply().

Пример результата работы функции get_experience:

In [45]:
import pandas as pd

def get_experience(arg):
    year_words = ['лет', 'года', 'год',]
    month_words = ['месяца', 'месяцев', 'месяц',]
    words = arg.split()
    experience_months = 0
    
    for i, word in enumerate(words):
        if word in year_words:
            experience_months += int(words[i-1]) * 12
        elif word in month_words:
            experience_months += int(words[i-1])
            
    return experience_months

In [46]:
hh_df = pd.DataFrame({
    'experience': ['Опыт работы 8 лет 3 месяца', 
                   'Опыт работы 3 года 5 месяцев',
                   'Опыт работы 1 год 9 месяцев',
                   'Опыт работы 3 месяца',
                   'Опыт работы 6 лет',
                   'Опыт работы 1 год 1 месяц',
                  ],})

hh_df['exp_months'] = hh_df['experience'].apply(get_experience)
hh_df

                     experience  exp_months
0    Опыт работы 8 лет 3 месяца          99
1  Опыт работы 3 года 5 месяцев          41
2   Опыт работы 1 год 9 месяцев          21
3          Опыт работы 3 месяца           3
4             Опыт работы 6 лет          72
5     Опыт работы 1 год 1 месяц          13

## citibike-tripdata

In [64]:
import pandas as pd

In [65]:
# работаетn только direct_url
direct_url = 'https://drive.google.com/uc?export=view&id=1YLZ0s6GhSmmQH6mRPKSv_1VtAvXJgZo7'
standart_url = 'https://drive.google.com/file/d/1YLZ0s6GhSmmQH6mRPKSv_1VtAvXJgZo7/view?usp=sharing'
sk_std_url = 'https://drive.google.com/file/d/1ERm5SXJBx4dg6FBWnzTzeNl5lVHjqurY/view?usp=sharing'
sk_direct_url = 'https://drive.google.com/uc?export=view&id=1ERm5SXJBx4dg6FBWnzTzeNl5lVHjqurY'
data = pd.read_csv(sk_direct_url)

In [63]:
df = data.copy()
df

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,2018-09-05 19:08:27.8460,2018-09-05 19:15:51.4940,494.0,W 26 St & 8 Ave,40.747348,-73.997236,448.0,W 37 St & 10 Ave,40.756604,-73.997901,19531,Subscriber,1990,2
299996,2018-09-05 19:08:28.3700,2018-09-05 19:20:01.5080,3016.0,Kent Ave & N 7 St,40.720368,-73.961651,3086.0,Graham Ave & Conselyea St,40.715143,-73.944507,34020,Subscriber,1982,1
299997,2018-09-05 19:08:27.5090,2018-09-05 19:13:40.5060,3686.0,Gansevoort St & Hudson St,40.739448,-74.005070,168.0,W 18 St & 6 Ave,40.739713,-73.994564,33220,Subscriber,1991,1
299998,2018-09-05 19:08:29.2300,2018-09-05 20:04:29.3220,254.0,W 11 St & 6 Ave,40.735324,-73.998004,499.0,Broadway & W 60 St,40.769155,-73.981918,34744,Subscriber,1975,0
299999,2018-09-05 19:08:29.7110,2018-09-05 19:12:14.7620,3496.0,1 Ave & E 110 St,40.792327,-73.938300,3502.0,Lexington Ave & E 111 St,40.795412,-73.944123,18292,Subscriber,1966,1

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [68]:
df.columns

Index(['starttime', 'stoptime', 'start station id', 'start station name',
       'start station latitude', 'start station longitude', 'end station id',
       'end station name', 'end station latitude', 'end station longitude',
       'bikeid', 'usertype', 'birth year', 'gender'],
      dtype='object')

Сколько пропусков в столбце start station id?

In [79]:
df['start station id'].isnull().sum()

169

Найдите идентификатор самой популярной стартовой стоянки. Запишите идентификатор в виде целого числа.

In [80]:
df['start station id'].value_counts()

start station id
281.0     1928
2006.0    1909
519.0     1873
514.0     1845
426.0     1835
          ...
3432.0      15
3599.0      11
2005.0       9
3704.0       7
3583.0       6
Name: count, Length: 759, dtype: int64

Велосипед с каким идентификатором является самым популярным?

In [81]:
df['bikeid'].value_counts()

bikeid
33887    107
34358    104
34159    103
34258    103
33916    102
        ...
18587      1
17324      1
29593      1
33157      1
25794      1
Name: count, Length: 10004, dtype: int64

Какой тип клиентов (столбец usertype) является преобладающим — Subscriber или Customer? В качестве ответа запишите долю клиентов преобладающего типа среди общего количества клиентов. Ответ округлите до сотых.

In [88]:
df['usertype'].value_counts()

usertype
Subscriber    232202
Customer       67798
Name: count, dtype: int64

In [95]:
232202 + 67798

300000

In [94]:
df['usertype'].shape[0]

300000

In [96]:
df[df['usertype'] == 'Subscriber'].shape[0] / df['usertype'].shape[0]

0.7740066666666666

Кто больше занимается велоспортом — мужчины или женщины? В ответ запишите число поездок для той группы, у которой их больше.

In [97]:
df.columns

Index(['starttime', 'stoptime', 'start station id', 'start station name',
       'start station latitude', 'start station longitude', 'end station id',
       'end station name', 'end station latitude', 'end station longitude',
       'bikeid', 'usertype', 'birth year', 'gender'],
      dtype='object')

In [100]:
df['gender'].shape[0]

300000

In [101]:
df['gender'].value_counts()

gender
1    183582
2     74506
0     41912
Name: count, dtype: int64

gender — пол клиента (0 — неизвестный, 1 — мужчина, 2 — женщина).

Выберите утверждения,которые соответствуют нашим данным:
A Число уникальных стартовых и конечных стоянок, которыми воспользовались клиенты, не равны друг другу
B В рассматриваемые дни минимальный возраст клиента составлял 10 лет
C Самой непопулярной стартовой стоянкой из тех, которыми воспользовались клиенты, является стоянка с названием "Eastern Pkwy & Washington Ave"
D Наибольшее количество поездок завершается на стоянке под названием "Liberty Light Rail"

In [105]:
df['start station name'].value_counts()

start station name
Grand Army Plaza & Central Park S    1928
Central Park S & 6 Ave               1909
Pershing Square North                1873
12 Ave & W 40 St                     1845
West St & Chambers St                1835
                                     ...
NYCBS Depot - GOW                      15
Franklin Ave & Empire Blvd             11
Railroad Ave & Kay Ave                  9
47 Ave & Skillman Ave                   7
Eastern Pkwy & Washington Ave           6
Name: count, Length: 759, dtype: int64

In [106]:
df['end station name'].value_counts()

end station name
West St & Chambers St          1963
12 Ave & W 40 St               1909
Pershing Square North          1850
Central Park S & 6 Ave         1828
E 17 St & Broadway             1804
                               ...
Exchange Place                    3
Union St                          1
Warren St                         1
Montrose Ave & Bushwick Ave       1
Liberty Light Rail                1
Name: count, Length: 765, dtype: int64

In [103]:
df['birth year'].describe()

count    300000.000000
mean       1979.364803
std          11.920796
min        1885.000000
25%        1969.000000
50%        1982.000000
75%        1989.000000
max        2002.000000
Name: birth year, dtype: float64

Датасет представляет собой таблицу с информацией о 300 тысячах поездок за первые пять дней сентября 2018 года и включает в себя следующую информацию:

In [104]:
2018 - 2002

16

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [108]:
df['start station id'].nunique()

759

In [110]:
df['start station name'].nunique()

759

In [109]:
df['end station id'].nunique()

765

In [111]:
df['end station name'].nunique()

765

In [114]:
df.drop(['start station id', 'end station id'], axis=1, inplace=True)

In [115]:
df.shape

(300000, 12)

Замените признак birth year на более понятный признак возраста клиента age. Годом отсчёта возраста выберите 2018 год. Столбец birth year удалите из таблицы. Сколько поездок совершено клиентами старше 60 лет?

In [117]:
df['age'] = 2018 - df['birth year']

In [120]:
df[['age', 'birth year']]

        age  birth year
0        38        1980
1        49        1969
2        43        1975
3        34        1984
4        24        1994
...     ...         ...
299995   28        1990
299996   36        1982
299997   27        1991
299998   43        1975
299999   52        1966

[300000 rows x 2 columns]

In [121]:
df.drop(['birth year'], axis=1, inplace=True)

In [122]:
df.columns

Index(['starttime', 'stoptime', 'start station name', 'start station latitude',
       'start station longitude', 'end station name', 'end station latitude',
       'end station longitude', 'bikeid', 'usertype', 'gender', 'age'],
      dtype='object')

In [124]:
df['age'].value_counts()

age
49     43959
30     12551
28     12051
29     11704
27     11640
       ...
129        1
103        1
82         1
109        1
111        1
Name: count, Length: 91, dtype: int64

Сколько поездок совершено клиентами старше 60 лет?

In [130]:
df[df['age'] > 60]['age'].value_counts().sum()

11837

Создайте признак длительности поездки trip duration. Для этого вычислите интервал времени между временем окончания поездки (stoptime) и её началом (starttime). Сколько целых минут длилась поездка под индексом 3 в таблице?

In [141]:
df['starttime'] = pd.to_datetime(df['starttime'])
df['stoptime'] = pd.to_datetime(df['stoptime'])

In [144]:
df['trip duration'] = df['stoptime'] - df['starttime']

In [145]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  datetime64[ns]
 1   stoptime                 300000 non-null  datetime64[ns]
 2   start station name       299831 non-null  object
 3   start station latitude   300000 non-null  float64
 4   start station longitude  300000 non-null  float64
 5   end station name         299831 non-null  object
 6   end station latitude     300000 non-null  float64
 7   end station longitude    300000 non-null  float64
 8   bikeid                   300000 non-null  int64
 9   usertype                 300000 non-null  object
 10  gender                   300000 non-null  int64
 11  age                      300000 non-null  int64
 12  trip duration            300000 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(4), int64(3), object(3), timedelta64[ns](1)
memory usage: 29.8+ MB

In [146]:
df['trip duration']

0        0 days 00:27:15.365000
1        0 days 00:02:12.200000
2        0 days 00:55:37.898000
3        0 days 00:07:16.837000
4        0 days 02:20:57.993000
                  ...
299995   0 days 00:07:23.648000
299996   0 days 00:11:33.138000
299997   0 days 00:05:12.997000
299998   0 days 00:56:00.092000
299999   0 days 00:03:45.051000
Name: trip duration, Length: 300000, dtype: timedelta64[ns]

Сколько целых минут длилась поездка под индексом 3 в таблице?

In [148]:
df['trip duration'][3]

Timedelta('0 days 00:07:16.837000')

# Модуль 5. Продвинутые методы работы с данными в Pandas

## 6/12   Объединение DataFrame: знакомимся с новыми данными

В этой части модуля мы будем работать с популярным датасетом MovieLens, в котором собраны логи некоторой рекомендательной системы фильмов.
Наши данные представляют собой четыре таблицы:

ratings1 и ratings2 — таблицы с данными о выставленных пользователями оценках фильмов. Они имеют одинаковую структуру и типы данных — на самом деле это две части одной таблицы с оценками фильмов.
userId — уникальный идентификатор пользователя, который выставил оценку;
movieId — уникальный идентификатор фильма;
rating — рейтинг фильма.

dates — таблица с датами выставления всех оценок.
date — дата и время выставления оценки фильму.

movies — таблица с информацией о фильмах.
movieId — уникальный идентификатор фильма;
title — название фильма и год его выхода;
genres — жанры фильма.

In [13]:
import pandas as pd
ratings1 = pd.read_csv('movies_data/ratings1.csv')
ratings2 = pd.read_csv('movies_data/ratings2.csv')
dates = pd.read_csv('movies_data/dates.csv')
movies = pd.read_csv('movies_data/movies.csv')

In [14]:
ratings1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40001 entries, 0 to 40000
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   userId   40001 non-null  int64
 1   movieId  40001 non-null  int64
 2   rating   40001 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 937.7 KB

In [15]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [16]:
movies.nunique()

movieId    9742
title      9737
genres      951
dtype: int64

In [18]:
ratings1.nunique()

userId      274
movieId    6219
rating       10
dtype: int64

In [31]:
dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    100836 non-null  datetime64[ns]
 1   year    100836 non-null  int32
dtypes: datetime64[ns](1), int32(1)
memory usage: 1.2 MB

In [27]:
dates['date'] = pd.to_datetime(dates['date'])
dates['year'] = dates['date'].dt.year

In [32]:
dates['year'].value_counts()

year
2000    10061
2017     8198
2007     7114
2016     6703
2015     6616
2018     6418
1996     6040
2005     5813
2012     4656
2008     4351
2009     4158
2006     4059
2003     4014
2001     3922
2002     3478
2004     3279
1999     2439
2010     2301
1997     1916
2011     1690
2013     1664
2014     1439
1998      507
Name: count, dtype: int64

Основные параметры функции concat()

objs — список объектов DataFrame ([df1, df2,…]), которые должны быть сконкатенированы;
axis — ось определяет направление конкатенации: 0 — конкатенация по строкам (по умолчанию), 1 — конкатенация по столбцам;
join — либо inner (пересечение), либо outer (объединение); рассмотрим этот момент немного позже;
ignore_index — по умолчанию установлено значение False, которое позволяет значениям индекса оставаться такими, какими они были в исходных данных. Если установлено значение True, параметр будет игнорировать исходные значения и повторно назначать значения индекса в последовательном порядке.

In [35]:
ratings = pd.concat(
    [ratings1, ratings2],
    ignore_index=True,
)
display(ratings)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [34]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100837 entries, 0 to 60835
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userId   100837 non-null  int64
 1   movieId  100837 non-null  int64
 2   rating   100837 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 3.1 MB

In [38]:
print(ratings.shape[0], '- число строк в таблице ratings.',)
print(dates.shape[0], '- число строк в таблице dates.',)
print(ratings.shape[0] == dates.shape[0])

100837 - число строк в таблице ratings.
100836 - число строк в таблице dates.
False

В результате конкатенации случилось дублирование строк. В данном примере их легко найти — выведем последнюю строку таблицы ratings1 и первую строку таблицы ratings2:

In [39]:
display(ratings1.tail(1))
display(ratings2.head(1))

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

Чтобы очистить таблицу от дублей, мы можем воспользоваться методом DataFrame drop_duplicates(), который удаляет повторяющиеся строки в таблице. Не забываем обновить индексы после удаления дублей, выставив параметр ignore_index в методе drop_duplicates() на значение True:

In [40]:
ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

Число строк в таблице ratings:  100836

Теперь, мы можем добавить к нашей таблице с оценками даты их выставления. Для этого конкатенируем таблицы ratings и dates по столбцам:

In [65]:
ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating                date  year
100829     610   164179     5.0 2017-05-03 21:07:11  2017
100830     610   166528     4.0 2017-05-04 06:29:25  2017
100831     610   166534     4.0 2017-05-03 21:53:22  2017
100832     610   168248     5.0 2017-05-03 22:21:31  2017
100833     610   168250     5.0 2017-05-08 19:50:47  2017
100834     610   168252     5.0 2017-05-03 21:19:12  2017
100835     610   170875     3.0 2017-05-03 21:20:15  2017

#### tasks

В ваше распоряжение предоставлена директория users ('./Root/users'). В данной директории содержатся csv-файлы, в каждом из которых хранится информация об идентификаторах пользователей (user_id) и ссылках на их фотографии (image_url). Количество файлов в директории может быть любым.

Вам необходимо написать функцию concat_user_files(path), параметром которой является path — путь до директории.

Функция должна:

Объединить информацию из всех csv-файлов в единый DataFrame.
Удалить дубликаты.
Обновить индексы результирующей таблицы.
Отсортировать пользователей по числовой части user_id (игнорируя буквенную часть).

##### Задание 6.3 объединить все файлы csv в папке, удалить дубликаты, вернуть DataFrame

In [64]:
import pandas as pd
import os

def concat_user_files(path):
    data = pd.DataFrame()
    file_names = os.listdir(path)
    file_names.sort()
    for file in file_names:
        tmp_data = pd.read_csv(path + '/' + file)
        data = pd.concat([data, tmp_data], axis=0, ignore_index=True)
    data = data.drop_duplicates()
    return data

In [63]:
concat_user_files('movies_data')

                       date   movieId title genres  userId  rating
0       2000-07-30 18:45:03       NaN   NaN    NaN     NaN     NaN
1       2000-07-30 18:20:47       NaN   NaN    NaN     NaN     NaN
2       2000-07-30 18:37:04       NaN   NaN    NaN     NaN     NaN
3       2000-07-30 19:03:35       NaN   NaN    NaN     NaN     NaN
4       2000-07-30 18:48:51       NaN   NaN    NaN     NaN     NaN
...                     ...       ...   ...    ...     ...     ...
211410                  NaN  166534.0   NaN    NaN   610.0     4.0
211411                  NaN  168248.0   NaN    NaN   610.0     5.0
211412                  NaN  168250.0   NaN    NaN   610.0     5.0
211413                  NaN  168252.0   NaN    NaN   610.0     5.0
211414                  NaN  170875.0   NaN    NaN   610.0     3.0

[195621 rows x 6 columns]

## 8/12   Объединение DataFrame: join, merge

### join()

other — таблица, которую мы присоединяем. При объединении она является «правой», а исходная таблица, от имени которой вызывается метод, является «левой».
how — параметр типа объединения. Он может принимать значения 'inner', 'left' (left outer), 'right' (right outer), и 'outer' (full outer). По умолчанию параметр установлен на 'left'.
on — параметр, который определяет, по какому столбцу в «левой» таблице происходит объединение по индексам из «правой».
lsuffix и rsuffix — дополнения (суффиксы) к названиям одноимённых столбцов в «левой» и «правой» таблицах.

In [67]:
ratings.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [68]:
ratings_dates.head()

   userId  movieId  rating                date  year
0       1        1     4.0 2000-07-30 18:45:03  2000
1       1        3     4.0 2000-07-30 18:20:47  2000
2       1        6     4.0 2000-07-30 18:37:04  2000
3       1       47     5.0 2000-07-30 19:03:35  2000
4       1       50     5.0 2000-07-30 18:48:51  2000

In [70]:
joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,year,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,2000,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,2000,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,2000,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

### merge()

right — присоединяемая таблица. По умолчанию она является «правой».
how — параметр типа объединения. По умолчанию принимает значение 'inner'.
on — параметр, который определяет, по какому столбцу происходит объединение. Определяется автоматически, но рекомендуется указывать вручную.
left_on — если названия столбцов в «левой» и «правой» таблицах не совпадают, то данный параметр отвечает за наименования ключевого столбца исходной таблицы.
right_on — аналогично предыдущему, параметр отвечает за наименование ключевого столбца присоединяемой таблицы.

In [71]:
merged = ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
display(merged.head())

,userId,movieId,rating,date,year,title,genres
0,1,1,4.0,2000-07-30 18:45:03,2000,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2000,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,2000,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,2000,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,2000,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [73]:
merge_ratings = ratings1.merge(ratings2, how='outer')
print('Число строк в таблице merge_ratings: ', merge_ratings.shape[0])
display(merge_ratings)
# Число строк в таблице merge_ratings: 100836

Число строк в таблице merge_ratings:  100836

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

#### tasks

##### simple

Даны две исходные таблицы:

In [74]:
a = pd.DataFrame({'A': ['a', 'b', 'c'], 'B': [103, 214, 124], 'C': [1, 4, 2]})
b = pd.DataFrame({'V': ['d', 'b', 'c'], 'U': [1393.7, 9382.2, 1904.5], 'C': [1, 3, 2]})

In [76]:
a

   A    B  C
0  a  103  1
1  b  214  4
2  c  124  2

In [77]:
b

   V       U  C
0  d  1393.7  1
1  b  9382.2  3
2  c  1904.5  2

In [79]:
a.merge(b)

   A    B  C  V       U
0  a  103  1  d  1393.7
1  c  124  2  c  1904.5

In [80]:
b.merge(a)

   V       U  C  A    B
0  d  1393.7  1  a  103
1  c  1904.5  2  c  124

In [82]:
a.merge(b, how='left', on='C')

   A    B  C    V       U
0  a  103  1    d  1393.7
1  b  214  4  NaN     NaN
2  c  124  2    c  1904.5

In [84]:
b.join(a.set_index('C'), how='right', on='C')

       V       U  C  A    B
0.0    d  1393.7  1  a  103
NaN  NaN     NaN  4  b  214
2.0    c  1904.5  2  c  124

In [85]:
a.merge(b, how='right', on='C')

     A      B  C  V       U
0    a  103.0  1  d  1393.7
1  NaN    NaN  3  b  9382.2
2    c  124.0  2  c  1904.5

##### harder

Информация в таблицах представлена в виде следующих столбцов:

item_id — идентификатор модели;
vendor — производитель модели;
stock_count — имеющееся на складе количество данных моделей (в штуках);
purchase_id — идентификатор покупки;
price — стоимость модели в покупке.
Вам необходимо сделать следующее:

Сформируйте DataFrame merged, так чтобы после объединения purchase_df и items_df остались модели, которые учтены на складе и имели продажи.

На основе таблицы merged найдите суммарную выручку, которую можно было бы получить от продажи всех товаров, имеющихся на складе. Результат занесите в переменную income.r

In [138]:
import pandas as pd

items_df = pd.DataFrame({
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 100132, 312394],
            'vendor': ['Samsung', 'LG', 'Apple', 'Apple', 'LG', 'Apple', 'Samsung', 'Samsung', 'LG', 'ZTE'],
            'stock_count': [54, 33, 122, 18, 102, 43, 77, 143, 60, 19]
        })

purchase_df = pd.DataFrame({
            'purchase_id': [101, 101, 101, 112, 121, 145, 145, 145, 145, 221],
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 103845, 100132],
            'price': [13900, 5330, 38200, 49990, 9890, 33000, 67500, 34500, 89900, 11400]
        })

# Введите свое решение ниже
merged = purchase_df.merge(items_df)
merged['gross'] = merged['price'] * merged['stock_count']
income = merged['gross'].sum()

task_order = ['item_id',
              'vendor',
              'stock_count',
              'purchase_id',
              'price',
             ]

merged = merged[task_order]
merged

   item_id   vendor  stock_count  purchase_id  price
0   417283  Samsung           54          101  13900
1   849734       LG           33          101   5330
2   132223    Apple          122          101  38200
3   573943    Apple           18          112  49990
4    19475       LG          102          121   9890
5  3294095    Apple           43          145  33000
6   382043  Samsung           77          145  67500
7   302948  Samsung          143          145  34500
8   100132       LG           60          221  11400

In [137]:
# SkillFactory view:
merged = items_df.merge(purchase_df, how='inner', on='item_id')
income = (merged['price'] * merged['stock_count']).sum()
merged

   item_id   vendor  stock_count  purchase_id  price
0   417283  Samsung           54          101  13900
1   849734       LG           33          101   5330
2   132223    Apple          122          101  38200
3   573943    Apple           18          112  49990
4    19475       LG          102          121   9890
5  3294095    Apple           43          145  33000
6   382043  Samsung           77          145  67500
7   302948  Samsung          143          145  34500
8   100132       LG           60          221  11400

Ожидаемый ответ:

item_id   vendor  stock_count  purchase_id  price
0   417283  Samsung           54          101  13900
1   849734       LG           33          101   5330
2   132223    Apple          122          101  38200
3   573943    Apple           18          112  49990
4    19475       LG          102          121   9890
5  3294095    Apple           43          145  33000
6   382043  Samsung           77          145  67500
7   302948  Samsung          143          145  34500
8   100132       LG           60          221  11400

In [107]:
income

19729490.0

## 9/12   Закрепление знаний

### first part

✍ В первой части данного урока мы проанализируем построенную нами таблицу c рейтингами фильмов, а во второй — рассмотрим новые данные (заказы в интернет-магазине) и выполним задания по ним.

In [145]:
import pandas as pd
ratings_movies = pd.read_csv('movies_data/ratings_movies.csv')
ratings_movies.head()

,Unnamed: 0,userId,movieId,rating,date,title,genres
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

Для решения задач нам понадобится выделить из признака title год выпуска фильма. Для этого напишем функцию get_year_release(arg).

Из модуля re нам понадобится только функция findall(), которая позволяет найти в строке все слова, удовлетворяющие шаблону. Мы находим в строке с названием фильма шаблон "(DDDD)" — четыре цифры, обёрнутых в скобки, что соответствует году выпуска фильма. Если такого шаблона не было найдено (год выпуска не указан), функция возвращает None (в таблице это будет помечено как пропуск).

In [146]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

Создайте в таблице новый признак year_release, который соответствует году выпуска фильма.
У скольких фильмов не указан год их выпуска?

In [150]:
ratings_movies['year_release'] = ratings_movies['title'].apply(get_year_release)

In [151]:
ratings_movies.columns

Index(['Unnamed: 0', 'userId', 'movieId', 'rating', 'date', 'title', 'genres',
       'year_release'],
      dtype='object')

In [152]:
ratings_movies.head()

,Unnamed: 0,userId,movieId,rating,date,title,genres,year_release
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance,1995.0
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller,1995.0
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1995.0
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1995.0

In [154]:
ratings_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    100836 non-null  int64
 1   userId        100836 non-null  int64
 2   movieId       100836 non-null  int64
 3   rating        100836 non-null  float64
 4   date          100836 non-null  object
 5   title         100836 non-null  object
 6   genres        100836 non-null  object
 7   year_release  100818 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 6.2+ MB

In [155]:
ratings_movies['year_release'].describe()

count    100818.000000
mean       1994.444990
std          14.361424
min        1902.000000
25%        1990.000000
50%        1997.000000
75%        2003.000000
max        2018.000000
Name: year_release, dtype: float64

In [157]:
ratings_movies['year_release'].value_counts()

year_release
1995.0    6144
1994.0    5296
1999.0    4536
1996.0    4509
2000.0    4268
          ...
1903.0       2
1908.0       1
1917.0       1
1915.0       1
1919.0       1
Name: count, Length: 106, dtype: int64

In [178]:
ratings_movies['year_release'].isna().sum()

18

In [177]:
ratings_movies[ratings_movies['year_release'].isna() == True]

,Unnamed: 0,userId,movieId,rating,date,title,genres,year_release
9147,9147,62,176601,5.0,2018-05-08 16:00:52,Black Mirror,(no genres listed),NaN
16886,16886,105,147250,5.0,2018-05-13 10:29:14,The Adventures of Sherlock Holmes and Doctor W...,(no genres listed),NaN
16913,16913,105,171749,5.0,2018-05-13 10:29:25,Death Note: Desu nôto (2006–2007),(no genres listed),NaN
17879,17879,111,171631,1.0,2018-01-31 23:21:49,Maria Bamford: Old Baby,(no genres listed),NaN
17881,17881,111,171891,3.5,2018-01-31 23:09:59,Generation Iron 2,(no genres listed),NaN
30039,30039,209,140956,3.5,2018-04-23 22:23:59,Ready Player One,Action|Sci-Fi|Thriller,NaN
30090,30090,210,40697,4.0,2018-05-25 16:36:31,Babylon 5,Sci-Fi,NaN
46593,46593,305,140956,4.5,2018-07-31 13:26:17,Ready Player One,Action|Sci-Fi|Thriller,NaN
46711,46711,306,149334,3.0,2018-02-11 20:19:32,Nocturnal Animals,Drama|Thriller,NaN
49851,49851,318,171495,5.0,2018-01-24 20:40:06,Cosmos,(no genres listed),NaN
58040,58040,380,140956,3.0,2018-08-13 16:02:38,Ready Player One,Action|Sci-Fi|Thriller,NaN
64964,64964,414,167570,4.0,2017-11-24 15:03:56,The OA,(no genres listed),NaN
70432,70432,448,143410,2.0,2016-09-18 18:53:22,Hyena Road,(no genres listed),NaN
71984,71984,462,162414,5.0,2016-11-07 03:32:11,Moonlight,Drama,NaN
81445,81445,514,140956,3.0,2018-08-11 00:08:39,Ready Player One,Action|Sci-Fi|Thriller,NaN
83380,83380,528,40697,0.5,2014-02-07 01:27:47,Babylon 5,Sci-Fi,NaN
88136,88136,567,156605,4.5,2018-05-02 17:50:48,Paterson,(no genres listed),NaN
95078,95078,599,171495,4.0,2018-02-20 08:55:12,Cosmos,(no genres listed),NaN

Какой фильм, выпущенный в 1999 году, получил наименьшую среднюю оценку зрителей?
В качестве ответа запишите название этого фильма без указания года его выпуска.

In [181]:

ratings_movies[ratings_movies['year_release'] == 1999].sort_values('rating')

,Unnamed: 0,userId,movieId,rating,date,title,genres,year_release
68328,68328,442,2881,0.5,2012-03-12 13:55:18,Double Jeopardy (1999),Action|Crime|Drama|Thriller,1999.0
27637,27637,187,2701,0.5,2006-10-26 07:52:48,Wild Wild West (1999),Action|Comedy|Sci-Fi|Western,1999.0
78748,78748,489,2485,0.5,2012-03-31 22:20:12,She's All That (1999),Comedy|Romance,1999.0
20882,20882,138,2707,0.5,2008-09-29 08:13:53,Arlington Road (1999),Thriller,1999.0
21326,21326,140,2683,0.5,2004-01-26 22:01:51,Austin Powers: The Spy Who Shagged Me (1999),Action|Adventure|Comedy,1999.0
...,...,...,...,...,...,...,...,...
23095,23095,157,2959,5.0,2001-06-14 00:51:45,Fight Club (1999),Action|Crime|Drama|Thriller,1999.0
76131,76131,479,2583,5.0,2002-12-08 17:13:36,Cookie's Fortune (1999),Comedy|Drama,1999.0
22970,22970,156,2997,5.0,2005-01-27 19:42:38,Being John Malkovich (1999),Comedy|Drama|Fantasy,1999.0
76136,76136,479,2700,5.0,2002-12-08 17:13:36,"South Park: Bigger, Longer and Uncut (1999)",Animation|Comedy|Musical,1999.0
162,162,1,2502,5.0,2000-07-30 18:21:18,Office Space (1999),Comedy|Crime,1999.0

In [187]:
pivot = ratings_movies[ratings_movies['year_release'] == 1999].pivot_table(
    values = 'rating',
    index = 'title',
)

In [189]:
pivot.sort_values(by='rating')

                                            rating
title
Bloodsport: The Dark Kumite (1999)             0.5
Simon Sez (1999)                               1.0
Chill Factor (1999)                            1.0
Source, The (1999)                             1.0
Trippin' (1999)                                1.0
...                                            ...
Trailer Park Boys (1999)                       5.0
Larry David: Curb Your Enthusiasm (1999)       5.0
Sun Alley (Sonnenallee) (1999)                 5.0
George Carlin: You Are All Diseased (1999)     5.0
Five Senses, The (1999)                        5.0

[261 rows x 1 columns]

Какое сочетание жанров фильмов (genres), выпущенных в 2010 году, получило наименьшую среднюю оценку (rating)?
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [191]:
ratings_movies.columns

Index(['Unnamed: 0', 'userId', 'movieId', 'rating', 'date', 'title', 'genres',
       'year_release'],
      dtype='object')

In [192]:
ratings_movies[ratings_movies['year_release'] == 2010].pivot_table(
    values = 'rating',
    index = 'genres',
).sort_values(by='rating')

                                     rating
genres
Action|Sci-Fi                      1.000000
Action|Adventure|Horror            1.500000
Action|Drama|Fantasy               1.500000
Crime|Romance                      1.500000
Adventure|Comedy|Fantasy           1.833333
...                                     ...
Crime                              4.750000
Comedy|Musical                     5.000000
Animation|Drama|Fantasy|Mystery    5.000000
Adventure|Children|Comedy|Mystery  5.000000
Animation|Children|Mystery         5.000000

[119 rows x 1 columns]

Какой пользователь (userId) посмотрел наибольшее количество различных (уникальных) комбинаций жанров (genres) фильмов? В качестве ответа запишите идентификатор этого пользователя.

In [203]:
users_genres = ratings_movies[['userId', 'genres',]]

users_genres = users_genres.drop_duplicates()

users_genres.pivot_table(
    index = 'userId',
    aggfunc = 'count',
).sort_values(by='genres', ascending=False)

        genres
userId
599        524
414        482
448        403
380        399
474        395
...        ...
578         15
12          15
85          13
214         13
245         13

[610 rows x 1 columns]

Найдите пользователя, который выставил наименьшее количество оценок, но его средняя оценка фильмам наибольшая.
В качестве ответа укажите идентификатор этого пользователя.
Чтобы рассчитать несколько параметров для каждого пользователя (количество оценок и среднюю оценку), можно воспользоваться методом agg() на сгруппированных данных.

In [229]:
users_ratings = ratings_movies.pivot_table(
    index = 'userId',
    values = 'rating',
    aggfunc = ['count', 'mean'],
)
users_ratings.sort_values(by=[('count', 'rating'), ('mean', 'rating')],
                         ascending = [True, False],).head()

        count   mean
       rating rating
userId
53         20  5.000
595        20  4.200
189        20  4.100
569        20  4.000
278        20  3.875

In [214]:
users_ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 610 entries, 1 to 610
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (count, rating)  610 non-null    int64
 1   (mean, rating)   610 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 14.3 KB

Найдите сочетание жанров (genres) за 2018 год, которое имеет наибольший средний рейтинг (среднее по столбцу rating), и при этом число выставленных ему оценок (количество значений в столбце rating) больше 10.
Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

In [234]:
ratings_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    100836 non-null  int64
 1   userId        100836 non-null  int64
 2   movieId       100836 non-null  int64
 3   rating        100836 non-null  float64
 4   date          100836 non-null  object
 5   title         100836 non-null  object
 6   genres        100836 non-null  object
 7   year_release  100818 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 6.2+ MB

In [240]:
ratings_movies['year_release'].describe()

count    100818.000000
mean       1994.444990
std          14.361424
min        1902.000000
25%        1990.000000
50%        1997.000000
75%        2003.000000
max        2018.000000
Name: year_release, dtype: float64

In [257]:
genres = ratings_movies[ratings_movies['year_release'] == 2018]
genres = genres.pivot_table(
    index = 'genres',
    values = 'rating',
    aggfunc = ['mean', 'count',],
).sort_values(
    by=[('mean', 'rating'), ('count', 'rating')],
    ascending = [False, False],
)
genres[genres[('count', 'rating')] >= 10]

                             mean  count
                           rating rating
genres
Action|Adventure|Sci-Fi  3.928571     14
Action|Comedy|Sci-Fi     3.875000     12

Добавьте в таблицу новый признак year_rating — год выставления оценки. Создайте сводную таблицу, которая иллюстрирует зависимость среднего рейтинга фильма от года выставления оценки и жанра. Выберите верные варианты ответа, исходя из построенной таблицы:

In [267]:
ratings_movies['date'] = pd.to_datetime(ratings_movies['date'])
year_rating = ratings_movies['date'].dt.year
ratings_movies.insert(5, 'year_rating', year_rating)

In [287]:
pivot = ratings_movies.pivot_table(
    index = 'year_rating',
    values = 'rating',
    columns = 'genres',
)
pivot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 1996 to 2018
Columns: 951 entries, (no genres listed) to Western
dtypes: float64(951)
memory usage: 171.0 KB

In [ ]:
pivot['Action|Adventure'].describe()

count    23.000000
mean      3.758512
std       0.291688
min       3.277778
25%       3.513889
50%       3.722222
75%       3.950000
max       4.304348
Name: Action|Adventure, dtype: float64

In [294]:
pivot['Action|Adventure|Animation|Children|Comedy|IMAX'].nlargest(1)

year_rating
2013    5.0
Name: Action|Adventure|Animation|Children|Comedy|IMAX, dtype: float64

In [315]:
pivot.T[2018].nlargest(7)

genres
Action|Comedy|Documentary                    5.0
Action|Crime|Sci-Fi|Thriller                 5.0
Action|Crime|Thriller|Western                5.0
Adventure|Children|Comedy|Fantasy|Mystery    5.0
Adventure|Fantasy|Musical                    5.0
Animation|Children|Mystery                   5.0
Animation|Comedy|Drama                       5.0
Name: 2018, dtype: float64

In [342]:
comedy = pivot['Comedy']
comedy = comedy.to_frame()
comedy['diff'] = comedy.diff()
comedy

               Comedy      diff
year_rating
1996         3.228571       NaN
1997         3.409091  0.180519
1998         3.000000 -0.409091
1999         3.606061  0.606061
2000         3.141291 -0.464769
2001         3.318408  0.177117
2002         3.198556 -0.119852
2003         3.120066 -0.078490
2004         3.356877  0.236812
2005         2.963325 -0.393552
2006         3.347534  0.384208
2007         2.928187 -0.419347
2008         3.426667  0.498480
2009         3.273292 -0.153375
2010         3.179825 -0.093467
2011         3.232877  0.053052
2012         3.478477  0.245600
2013         3.489474  0.010997
2014         3.271429 -0.218045
2015         3.106183 -0.165246
2016         3.373431  0.267248
2017         2.852668 -0.520763
2018         3.121296  0.268628

### second part

✍ А теперь поговорим о заказах в интернет-магазине.

In [1]:
import pandas as pd

In [14]:
orders_data = pd.read_csv('data/orders.csv', sep=';')

In [18]:
orders_data.head()

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5

In [30]:
products_data = pd.read_csv('data/products.csv', sep=';')

In [31]:
products_data.head()

   Product_ID                      Name  Price CURRENCY
0          47      Шатны Полосатый рейс   2999      RUR
1          51  Платье Аленький цветочек   4999      RUR
2          53    Штаны Цветочная Поляна   4999      RUR
3          71       Платье Ночная Жизнь   7999      RUR
4          74  Платье Ночная Жизнь XXXL   8999      RUR

In [49]:
orders = orders_data.copy()
products = products_data.copy()

In [50]:
merged = orders.merge(products, left_on='ID товара', right_on='Product_ID', how='left', indicator=True)

In [52]:
merged['Revenue'] = merged['Количество'] * merged['Price']
merged.tail()

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Product_ID,Name,Price,CURRENCY,_merge,Revenue
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,47.0,Шатны Полосатый рейс,2999.0,RUR,both,2999.0
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,71.0,Платье Ночная Жизнь,7999.0,RUR,both,7999.0
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,86.0,"Носки Простые, муж",45.0,RUR,both,45.0
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,51.0,Платье Аленький цветочек,4999.0,RUR,both,4999.0
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN,NaN,left_only,NaN

Какой покупатель принёс наибольшую суммарную прибыль интернет-магазину за указанный период?
В ответ запишите идентификатор этого покупателя (ID Покупателя).
Прибыль состоит только из оплаченных заказов и рассчитывается как количество купленного товара, умноженное на его цену.

In [58]:
paid = merged[merged['Оплачен'] == 'Да']
paid.describe()

,Order ID,ID Покупателя,ID товара,Количество,Product_ID,Price,Revenue
count,10.000000,10.000000,10.000000,10.000000,9.000000,9.000000,9.000000
mean,1.700000,6.000000,139.200000,1.400000,80.666667,3398.555556,3498.111111
std,0.948683,2.108185,187.235918,0.843274,29.920729,3537.333286,3441.206491
min,0.000000,1.000000,47.000000,1.000000,47.000000,45.000000,45.000000
25%,1.000000,5.000000,57.500000,1.000000,53.000000,199.000000,597.000000
50%,2.000000,7.000000,80.000000,1.000000,74.000000,2999.000000,2999.000000
75%,2.000000,7.000000,103.750000,1.000000,103.000000,4999.000000,4999.000000
max,3.000000,8.000000,666.000000,3.000000,137.000000,8999.000000,8999.000000

In [62]:
paid.pivot_table(
    index = 'ID Покупателя',
    values = 'Revenue',
    aggfunc = 'sum',
).sort_values(by='Revenue', ascending=False)

               Revenue
ID Покупателя
7              17096.0
5              13043.0
8               1344.0
1                  0.0