In [1]:
import pandas as pd

In [2]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

In [3]:
countries_df

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [4]:
countries_df.index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [5]:
countries_df = pd.DataFrame(
    data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Украина', 45.5, 603628],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
    columns = ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

# 4/12   Pandas.DataFrame task 3.5

Вы работаете аналитиком в компании ScienceYou. Ваша задача — проанализировать чистую прибыль.

Доходы (income), расходы (expenses) и годы (years), соответствующие им, предоставлены вам в виде списков.

Создайте функцию create_companyDF(income, expenses, years), которая возвращает DataFrame, составленный из входных данных со столбцами Income и Expenses и индексами, соответствующими годам рассматриваемого периода.

Пример такого DataFrame представлен ниже.

    Income  Expenses
2018    478     156
2019    512     130
2020    196     270

Также напишите функцию get_profit(df, year), которая возвращает разницу между доходом и расходом, записанными в таблице df, за год year.

Примечание. Если информация за запрашиваемый год не указана в вашей таблице, вам необходимо вернуть None.

Примечание. Не забудьте ипортировать библиотеки.

In [56]:
import pandas as pd


def create_companyDF(income, expenses, years):
    df = pd.DataFrame({
    'Income': income,
    'Expenses': expenses,
    })
    df.index = years
    return df


def get_profit(df, year):
    
    if year in df.index:
        profit = df.loc[year, 'Income'] - df.loc[year, 'Expenses']
    else:
        profit = None
    
    return profit

In [62]:
print(get_profit(df,2018))

322

In [54]:
income = [478, 512, 196]
expenses = [156, 130, 270]
years = [2018, 2019, 2020]
df = create_companyDF(income, expenses, years)

In [66]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df.to_csv('countries.csv', index=False, sep=';')

In [68]:
countries_data = pd.read_csv('countries.csv', sep=';')
display(countries_data)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

# 6/12   Знакомимся с данными: недвижимость

In [5]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [4]:
melb_data.describe()

,index,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000
mean,6789.500000,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.611856,558.416127,139.633972,1966.788218,-37.809203,144.995216,7454.417378
std,3920.352663,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.960793,3990.669241,392.217403,29.088642,0.079260,0.103916,4378.581772
min,0.000000,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,3394.750000,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,122.000000,1960.000000,-37.856822,144.929600,4380.000000
50%,6789.500000,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,10184.250000,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,129.940000,1975.000000,-37.756400,145.058305,10331.000000
max,13579.000000,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [83]:
melb_data

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0,"-37.8072, 144.9941"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,652.0,126.0,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0,"-37.90562, 145.16761"
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0,"-37.85927, 144.87904"
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4.0,436.0,126.0,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0,"-37.85274, 144.88738"
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0,"-37.85908, 144.89299"
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0,"-37.81188, 144.88449"

In [113]:
melb_data.loc[3552, 'Landsize'] / melb_data.loc[1690, 'Landsize']

2.511904761904762

In [115]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  object
dtypes: float64(11), int64(3), object(9)
memory usage: 2.4+ MB

In [117]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [121]:
melb_data.describe().loc[:, ['Distance', 'BuildingArea', 'Price']]

           Distance  BuildingArea         Price
count  13580.000000  13580.000000  1.358000e+04
mean      10.137776    139.633972  1.075684e+06
std        5.868725    392.217403  6.393107e+05
min        0.000000      0.000000  8.500000e+04
25%        6.100000    122.000000  6.500000e+05
50%        9.200000    126.000000  9.030000e+05
75%       13.000000    129.940000  1.330000e+06
max       48.100000  44515.000000  9.000000e+06

In [135]:
melb_data.describe(include=['object'] ).loc[:, ['Type']]

         Type
count   13580
unique      3
top         h
freq     9449

In [137]:
melb_data['Type'].value_counts()

Type
h    9449
u    3017
t    1114
Name: count, dtype: int64

In [139]:
1114 / 13580 * 100

8.203240058910161

In [125]:
melb_data.isnull().sum()

index               0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom             0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
Coordinates         0
dtype: int64

In [169]:
melb_data['Bedroom'].mode()

0    3
Name: Bedroom, dtype: int64

In [143]:
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [149]:
melb_data.describe().loc[:, 'Propertycount']

count    13580.000000
mean      7454.417378
std       4378.581772
min        249.000000
25%       4380.000000
50%       6555.000000
75%      10331.000000
max      21650.000000
Name: Propertycount, dtype: float64

In [151]:
melb_data.head().loc[:, 'Propertycount']

0    4019
1    4019
2    4019
3    4019
4    4019
Name: Propertycount, dtype: int64

In [153]:
landsize_median = melb_data['Landsize'].median() 
landsize_mean =  melb_data['Landsize'].mean()
print(abs(landsize_median - landsize_mean)/landsize_mean)
# 0.21205713983546193

0.21205713983546193

In [167]:
b_median = melb_data['BuildingArea'].median() 
b_mean =  melb_data['BuildingArea'].mean()
print(abs(b_median - b_mean)/b_mean)
# 0.21205713983546193

0.09764079662364533

In [159]:
melb_data['BuildingArea'].median()

126.0

In [165]:
melb_data['BuildingArea'].mean()

139.63397229013256

# 9/12   Фильтрация данных в DataFrame

In [46]:
import pandas as pd

melb_data = pd.read_csv('data/melb_data.csv', sep=',')

In [47]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [11]:
melb_data[melb_data['Bathroom'] == 0].shape[0]

34

In [50]:
melb_data['Type'].describe()

count     13580
unique        3
top           h
freq       9449
Name: Type, dtype: object

In [18]:
melb_data[melb_data['SellerG'] == 'Nelson'].shape[0]

1565

In [23]:
melb_data[melb_data['Price'] > 3_000_000].shape[0]

221

In [25]:
melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3_000_000)].shape[0]

5

In [28]:
melb_data[melb_data['BuildingArea'] == 0]['Price'].min()

412500.0

Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, в которых либо количество комнат больше пяти, либо здание моложе 2015 года?

In [39]:
price = melb_data['Price'] < 1_000_000
room = melb_data['Rooms'] > 5
year = melb_data['YearBuilt'] > 2015
mask = price & (room | year)
melb_data[mask]['Price'].mean()

769238.6363636364

В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?

In [53]:
price = melb_data['Price'] < 3_000_000
type = melb_data['Type'] == 'h'
mask = price & type

In [66]:
melb_data[mask]['Regionname'].value_counts()

Regionname
Northern Metropolitan         2737
Southern Metropolitan         2520
Western Metropolitan          2286
Eastern Metropolitan          1167
South-Eastern Metropolitan     387
Eastern Victoria                50
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [65]:
melb_data[mask].describe(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname,Coordinates
count,9220,9220,9220,9220,9220,9220,7999,9220,9220
unique,313,9075,1,5,232,58,33,8,9160
top,Reservoir,2 Bruce St,h,S,Nelson,27/05/2017,Moreland,Northern Metropolitan,"-37.74635, 144.9229"
freq,253,3,9220,6367,1154,334,842,2737,2

In [64]:
melb_data[mask].groupby('Regionname').count()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Propertycount,Coordinates
Regionname,,,,,,,,,,,,,,,,,,,,,
Eastern Metropolitan,1167,1167,1167,1167,1167,1167,1167,1167,1167,1167,...,1167,1167,1167,1167,1167,943,1167,1167,1167,1167
Eastern Victoria,50,50,50,50,50,50,50,50,50,50,...,50,50,50,50,50,41,50,50,50,50
Northern Metropolitan,2737,2737,2737,2737,2737,2737,2737,2737,2737,2737,...,2737,2737,2737,2737,2737,2436,2737,2737,2737,2737
Northern Victoria,41,41,41,41,41,41,41,41,41,41,...,41,41,41,41,41,26,41,41,41,41
South-Eastern Metropolitan,387,387,387,387,387,387,387,387,387,387,...,387,387,387,387,387,272,387,387,387,387
Southern Metropolitan,2520,2520,2520,2520,2520,2520,2520,2520,2520,2520,...,2520,2520,2520,2520,2520,2233,2520,2520,2520,2520
Western Metropolitan,2286,2286,2286,2286,2286,2286,2286,2286,2286,2286,...,2286,2286,2286,2286,2286,2023,2286,2286,2286,2286
Western Victoria,32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,25,32,32,32,32