<div style="text-align: right"> Марина Архипцева </div>

### Основы Pandas

In [2]:
import pandas as pd
pd.__version__

'2.2.2'

In [4]:
pd.__name__

'pandas'

###  Основные структуры данных в Pandas: Series и DataFrame

#### Series

**Series** — это одномерная структура данных, аналогичная списку в Python или одномерному массиву NumPy. Она представляет собой упорядоченную (элементы имеют индекс) последовательность элементов одного типа данных (например, целые числа, строки, вещественные числа и т.д.).

In [8]:
s = pd.Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
s[0]

10

In [12]:
s1 = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
s1

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [14]:
s1['a']

10

In [16]:
s1[0]

C:\Users\LysogorA\AppData\Local\Temp\ipykernel_11248\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

10

In [20]:
s1.iloc[0]

10

In [22]:
s_new = pd.Series([1, 3.14, 'hello', True, None])

s_new

0        1
1     3.14
2    hello
3     True
4     None
dtype: object

In [24]:
# Срезы (с 1 по 3 элемент)
series_new = s[1:4]
print(series_new)

# Что получили в результе среза?

1    20
2    30
3    40
dtype: int64

In [26]:
series_new.reset_index(drop=True)

0    20
1    30
2    40
dtype: int64

In [28]:
# вместо стандартного индекса можно использовать произвольные метки.

s = pd.Series([100, 200, 250, 300, 400, 500], index=['a', 'a', 'b', 'c', 'd', 'e'])
s

a    100
a    200
b    250
c    300
d    400
e    500
dtype: int64

In [30]:
print(s['a'])
print(s[0])

a    100
a    200
dtype: int64
100

C:\Users\LysogorA\AppData\Local\Temp\ipykernel_11248\1148839198.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [44]:
s['a'], s.iloc[0]

(a    100
 a    200
 dtype: int64,
 100)

In [46]:
s['a':'b']

a    100
a    200
b    250
dtype: int64

#### Методы для доступа к элементам по индексу

- loc[]: Используется для доступа к элементам по индексу (метке), которая может быть строкой, числом или другим объектом.
- iloc[]: Используется для доступа к элементам по целочисленной позиции (аналогично индексам в списках Python).

- В случае срезов по строковым индексам при использовании loc[] обе границы среза включены.
- В случае срезов по целочисленным позициям срезы работают как в стандартных списках Python: верхняя граница не включается.
- При использовании iloc[] для срезов всегда используются целочисленные позиции, независимо от кастомного индекса.

In [49]:
s

a    100
a    200
b    250
c    300
d    400
e    500
dtype: int64

In [51]:
# Срез от 'b' до 'd' включительно
print(s.loc['b':'d'])

b    250
c    300
d    400
dtype: int64

In [53]:
# Срез по целочисленным позициям (от 1 до 3, не включая 3)
print(s.iloc[1:3])

a    200
b    250
dtype: int64

In [55]:
# Неявный срез по строковому индексу
print(s['b':'d'])  # Это аналогично .loc['b':'d']

b    250
c    300
d    400
dtype: int64

In [57]:
# Неявный срез по числовым позициям
print(s[1:3])  # Это аналогично .iloc[1:3]

a    200
b    250
dtype: int64

| Операция          | `.loc[]`                         | `.iloc[]`                    |
|-------------------|----------------------------------|------------------------------|
| Доступ по         | Индексу (именному)               | Позиции (числовой)           |
| Тип индекса       | Строки, числа, другие объекты    | Только целые числа (позиции) |
| Включение верхней границы в срезе | Включена                   | Не включена                  |
| Пример            | `s.loc['b']`                     | `s.iloc[1]`                  |
| Пример среза      | `s.loc['b':'d']` (включает 'd')  | `s.iloc[1:4]` (не включает 4)|

#### Операции с Series

In [62]:
# Арифметические операции

s = pd.Series([1, 2, 3, 4, 5])
s + 1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [64]:
s * 2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [66]:
s ** 2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [68]:
# Фильтрация по условию
s[s > 3]

3    4
4    5
dtype: int64

In [70]:
# Присвоение значений по индексу
s[1] = 100
s

0      1
1    100
2      3
3      4
4      5
dtype: int64

In [72]:
s['a'] = 100
s

0      1
1    100
2      3
3      4
4      5
a    100
dtype: int64

In [74]:
s.values

array([  1, 100,   3,   4,   5, 100], dtype=int64)

In [76]:
s.index

Index([0, 1, 2, 3, 4, 'a'], dtype='object')

In [78]:
s.dtype

dtype('int64')

In [80]:
'a' in s

True

In [82]:
s.get('a')

100

In [84]:
s1 = pd.Series([1, 2, 3, 4])
s2 = pd.Series([10, 20, 30, 40, 50])
s2 + s1

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

#### DataFrame
`DataFrame` — это двумерная табличная структура данных, которая представляет собой коллекцию `Series`, каждая из которых является столбцом. 

`DataFrame` можно рассматривать как аналог таблицы в базах данных или как электронную таблицу Excel.

##### Основные характеристики `DataFrame`:
- **Двумерная структура**: Данные представлены в виде строк и столбцов.
- **Гибкость типов данных**: Разные столбцы могут иметь разные типы данных (например, числа в одном столбце и строки в другом).
- **Индексация**: Строки и столбцы имеют индексы, которые можно использовать для доступа к данным.
- **Поддержка операций с табличными данными**: Pandas предоставляет инструменты для агрегации, сортировки, фильтрации и работы с отсутствующими значениями.

#### Создание DataFrame

In [88]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [90]:
# Пустой DataFrame с заданными именами столбцов
df = pd.DataFrame(columns=['Name', 'Age', 'Score'])
df

Empty DataFrame
Columns: [Name, Age, Score]
Index: []

In [92]:
import pandas as pd
# Из словаря
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Score': [85.5, 90.2, 88.0]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25   85.5
1      Bob   30   90.2
2  Charlie   35   88.0

In [94]:
# Из списка
data = [
    ['Alice', 25, 85.5],
    ['Bob', 30, 90.2],
    ['Charlie', 35, 88.0]
]

df1 = pd.DataFrame(data, columns=['Name', 'Age', 'Score'])
df1

      Name  Age  Score
0    Alice   25   85.5
1      Bob   30   90.2
2  Charlie   35   88.0

In [96]:
# Из массива Numpy
import numpy as np

# 2D массив NumPy
data = np.array([[25, 85.5], [30, 90.2], [35, 88.0]])

df2 = pd.DataFrame(data, columns=['Age', 'Score'],  index=['a', 'b', 'c'])
df2

    Age  Score
a  25.0   85.5
b  30.0   90.2
c  35.0   88.0

In [98]:
# из Series
s0 = pd.Series(['Alice', 'Bob', 'Charlie'])
s1 = pd.Series([85.5, 90.2, 88.0])
s2 = pd.Series([25, 30, 35])

df3 = pd.DataFrame({'Name': s0, 'Score': s1, 'Age': s2})
df3

      Name  Score  Age
0    Alice   85.5   25
1      Bob   90.2   30
2  Charlie   88.0   35

In [100]:
# Из файла (например, CSV)
df4 = pd.read_csv('emp.csv')
df4

# read_excel(), read_sql(), read_json() - аналогично для загрузки данных из других форматов

      name   position  salary
0    Alice    Manager   80000
1      Bob  Developer   60000
2  Charlie   Designer   55000
3    David  Developer   65000
4      Eve    Manager   90000

In [102]:
df4.values

array([['Alice', 'Manager', 80000],
       ['Bob', 'Developer', 60000],
       ['Charlie', 'Designer', 55000],
       ['David', 'Developer', 65000],
       ['Eve', 'Manager', 90000]], dtype=object)

##### Доступ к строкам и столбцам

In [105]:
# Обращение к столбцу как к ключу словаря
df4['name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: object

In [107]:
# Как атрибут
df4.name

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: object

In [109]:
# Для работы с строками используются индексы

# loc (для именованных индексов) или iloc (для целочисленных индексов)

# Получение строки с индексом 1
df4.loc[1]  # Строка с индексом 1

name              Bob
position    Developer
salary          60000
Name: 1, dtype: object

In [111]:
# Получение строки по позиции
df4.iloc[1]  # Строка с индексом 1 (аналогично .loc)

name              Bob
position    Developer
salary          60000
Name: 1, dtype: object

In [113]:
df

      Name  Age  Score
0    Alice   25   85.5
1      Bob   30   90.2
2  Charlie   35   88.0

In [115]:
df[df['Age'] >= 30]

      Name  Age  Score
1      Bob   30   90.2
2  Charlie   35   88.0

In [117]:
# Фильтрация строк по условию

# Все строки, где возраст больше 30
filtered_df = df[df['Age'] >= 30]
filtered_df

      Name  Age  Score
1      Bob   30   90.2
2  Charlie   35   88.0

In [119]:
df[df['Age'] >= 30]

      Name  Age  Score
1      Bob   30   90.2
2  Charlie   35   88.0

#### Добавление нового столбца

In [122]:
df['Passed'] = df['Score'] > 90
df

      Name  Age  Score  Passed
0    Alice   25   85.5   False
1      Bob   30   90.2    True
2  Charlie   35   88.0   False

In [124]:
df['City'] = ['Moscow', 'Sochi', 'Omsk']

In [126]:
df

      Name  Age  Score  Passed    City
0    Alice   25   85.5   False  Moscow
1      Bob   30   90.2    True   Sochi
2  Charlie   35   88.0   False    Omsk

In [128]:
df['University'] = ['MIFI', 0, [5, 6]]
df

      Name  Age  Score  Passed    City University
0    Alice   25   85.5   False  Moscow       MIFI
1      Bob   30   90.2    True   Sochi          0
2  Charlie   35   88.0   False    Omsk     [5, 6]

In [130]:
df['Age_at_final'] = df['Age'] + 2
df['Name_length'] = df['Name'].apply(len)
df

      Name  Age  Score  Passed    City University  Age_at_final  Name_length
0    Alice   25   85.5   False  Moscow       MIFI            27            5
1      Bob   30   90.2    True   Sochi          0            32            3
2  Charlie   35   88.0   False    Omsk     [5, 6]            37            7

#### Добавление новой строки

! DataFrame оптимизирован для работы с векторными операциями, и добавление строк вручную может быть неэффективным, особенно если это делать в цикле

In [133]:
df.drop(columns=['City', 'University', 'Age_at_final', 'Name_length'], inplace=True)

In [135]:
df.loc[3] = ['Cler', 36, 90.0, True]
df

      Name  Age  Score  Passed
0    Alice   25   85.5   False
1      Bob   30   90.2    True
2  Charlie   35   88.0   False
3     Cler   36   90.0    True

In [137]:
df.at[3, 'Name']

'Cler'

In [139]:
# Добавление строки с помощью at[]
df.at[4, 'Name'] = 'David'
df.at[4, 'Age'] = 45
df.at[4, 'Score'] = 98.0

df

      Name   Age  Score Passed
0    Alice  25.0   85.5  False
1      Bob  30.0   90.2   True
2  Charlie  35.0   88.0  False
3     Cler  36.0   90.0   True
4    David  45.0   98.0    NaN

In [141]:
# Добавление строки с помощью concat
# Этот вариант самый лучший
new_row = pd.DataFrame([{'Name': 'Eve', 'Age': 37, 'Score': 95.5}])
new_row

  Name  Age  Score
0  Eve   37   95.5

In [143]:
pd.concat([df, new_row], ignore_index=True)

      Name   Age  Score Passed
0    Alice  25.0   85.5  False
1      Bob  30.0   90.2   True
2  Charlie  35.0   88.0  False
3     Cler  36.0   90.0   True
4    David  45.0   98.0    NaN
5      Eve  37.0   95.5    NaN

#### Удаление столбцов или строк

In [146]:
# Удаление столбца
df.drop(columns=['Passed'], inplace=True)

In [148]:
df

      Name   Age  Score
0    Alice  25.0   85.5
1      Bob  30.0   90.2
2  Charlie  35.0   88.0
3     Cler  36.0   90.0
4    David  45.0   98.0

In [87]:
# Удаление строки
df = df.drop(index=[1])
df

      Name  Age  Score  Passed
0    Alice   25   85.5   False
2  Charlie   35   88.0   False

In [88]:
df.reset_index(inplace=True, drop=True)
df

      Name  Age  Score  Passed
0    Alice   25   85.5   False
1  Charlie   35   88.0   False

#### Выгрузка DataFrame в файл

In [150]:
df.to_csv('students.csv')

#### Операции

In [153]:
df['Score'].mean()  # Средний балл

90.34

In [155]:
df['Age'] = df['Age'] + 2
df

      Name   Age  Score
0    Alice  27.0   85.5
1      Bob  32.0   90.2
2  Charlie  37.0   88.0
3     Cler  38.0   90.0
4    David  47.0   98.0

In [157]:
# Сортировка данных
sorted_df = df.sort_values(by='Score', ascending=False)
sorted_df

      Name   Age  Score
4    David  47.0   98.0
1      Bob  32.0   90.2
3     Cler  38.0   90.0
2  Charlie  37.0   88.0
0    Alice  27.0   85.5

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      float64
 2   Score   5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 332.0+ bytes

In [161]:
df.shape

(5, 3)

In [163]:
df.describe(include='object')

         Name
count       5
unique      5
top     Alice
freq        1

In [10]:
help(df.describe)

Help on method describe in module pandas.core.generic:

describe(percentiles=None, include=None, exclude=None) -> 'Self' method of pandas.core.frame.DataFrame instance
    Generate descriptive statistics.

    Descriptive statistics include those that summarize the central
    tendency, dispersion and shape of a
    dataset's distribution, excluding ``NaN`` values.

    Analyzes both numeric and object series, as well
    as ``DataFrame`` column sets of mixed data types. The output
    will vary depending on what is provided. Refer to the notes
    below for more detail.

    Parameters
    ----------
    percentiles : list-like of numbers, optional
        The percentiles to include in the output. All should
        fall between 0 and 1. The default is
        ``[.25, .5, .75]``, which returns the 25th, 50th, and
        75th percentiles.
    include : 'all', list-like of dtypes or None (default), optional
        A white list of data types to include in the result. Ignored
        for ``Series``. Here are the options:

        - 'all' : All columns of the input will be included in the output.
        - A list-like of dtypes : Limits the results to the
          provided data types.
          To limit the result to numeric types submit
          ``numpy.number``. To limit it instead to object columns submit
          the ``numpy.object`` data type. Strings
          can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(include=['O'])``). To
          select pandas categorical columns, use ``'category'``
        - None (default) : The result will include all numeric columns.
    exclude : list-like of dtypes or None (default), optional,
        A black list of data types to omit from the result. Ignored
        for ``Series``. Here are the options:

        - A list-like of dtypes : Excludes the provided data types
          from the result. To exclude numeric types submit
          ``numpy.number``. To exclude object columns submit the data
          type ``numpy.object``. Strings can also be used in the style of
          ``select_dtypes`` (e.g. ``df.describe(exclude=['O'])``). To
          exclude pandas categorical columns, use ``'category'``
        - None (default) : The result will exclude nothing.

    Returns
    -------
    Series or DataFrame
        Summary statistics of the Series or Dataframe provided.

    See Also
    --------
    DataFrame.count: Count number of non-NA/null observations.
    DataFrame.max: Maximum of the values in the object.
    DataFrame.min: Minimum of the values in the object.
    DataFrame.mean: Mean of the values.
    DataFrame.std: Standard deviation of the observations.
    DataFrame.select_dtypes: Subset of a DataFrame including/excluding
        columns based on their dtype.

    Notes
    -----
    For numeric data, the result's index will include ``count``,
    ``mean``, ``std``, ``min``, ``max`` as well as lower, ``50`` and
    upper percentiles. By default the lower percentile is ``25`` and the
    upper percentile is ``75``. The ``50`` percentile is the
    same as the median.

    For object data (e.g. strings or timestamps), the result's index
    will include ``count``, ``unique``, ``top``, and ``freq``. The ``top``
    is the most common value. The ``freq`` is the most common value's
    frequency. Timestamps also include the ``first`` and ``last`` items.

    If multiple object values have the highest count, then the
    ``count`` and ``top`` results will be arbitrarily chosen from
    among those with the highest count.

    For mixed data types provided via a ``DataFrame``, the default is to
    return only an analysis of numeric columns. If the dataframe consists
    only of object and categorical data without any numeric columns, the
    default is to return an analysis of both the object and categorical
    columns. If ``include='all'`` is provided as an option, the result
    will include a union of attributes of each type.

    The `include` and `exclude` parameters can be used to limit
    which columns in a ``DataFrame`` are analyzed for the output.
    The parameters are ignored when analyzing a ``Series``.

    Examples
    --------
    Describing a numeric ``Series``.

    >>> s = pd.Series([1, 2, 3])
    >>> s.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    dtype: float64

    Describing a categorical ``Series``.

    >>> s = pd.Series(['a', 'a', 'b', 'c'])
    >>> s.describe()
    count     4
    unique    3
    top       a
    freq      2
    dtype: object

    Describing a timestamp ``Series``.

    >>> s = pd.Series([
    ...     np.datetime64("2000-01-01"),
    ...     np.datetime64("2010-01-01"),
    ...     np.datetime64("2010-01-01")
    ... ])
    >>> s.describe()
    count                      3
    mean     2006-09-01 08:00:00
    min      2000-01-01 00:00:00
    25%      2004-12-31 12:00:00
    50%      2010-01-01 00:00:00
    75%      2010-01-01 00:00:00
    max      2010-01-01 00:00:00
    dtype: object

    Describing a ``DataFrame``. By default only numeric fields
    are returned.

    >>> df = pd.DataFrame({'categorical': pd.Categorical(['d', 'e', 'f']),
    ...                    'numeric': [1, 2, 3],
    ...                    'object': ['a', 'b', 'c']
    ...                    })
    >>> df.describe()
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Describing all columns of a ``DataFrame`` regardless of data type.

    >>> df.describe(include='all')  # doctest: +SKIP
           categorical  numeric object
    count            3      3.0      3
    unique           3      NaN      3
    top              f      NaN      a
    freq             1      NaN      1
    mean           NaN      2.0    NaN
    std            NaN      1.0    NaN
    min            NaN      1.0    NaN
    25%            NaN      1.5    NaN
    50%            NaN      2.0    NaN
    75%            NaN      2.5    NaN
    max            NaN      3.0    NaN

    Describing a column from a ``DataFrame`` by accessing it as
    an attribute.

    >>> df.numeric.describe()
    count    3.0
    mean     2.0
    std      1.0
    min      1.0
    25%      1.5
    50%      2.0
    75%      2.5
    max      3.0
    Name: numeric, dtype: float64

    Including only numeric columns in a ``DataFrame`` description.

    >>> df.describe(include=[np.number])
           numeric
    count      3.0
    mean       2.0
    std        1.0
    min        1.0
    25%        1.5
    50%        2.0
    75%        2.5
    max        3.0

    Including only string columns in a ``DataFrame`` description.

    >>> df.describe(include=[object])  # doctest: +SKIP
           object
    count       3
    unique      3
    top         a
    freq        1

    Including only categorical columns from a ``DataFrame`` description.

    >>> df.describe(include=['category'])
           categorical
    count            3
    unique           3
    top              d
    freq             1

    Excluding numeric columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[np.number])  # doctest: +SKIP
           categorical object
    count            3      3
    unique           3      3
    top              f      a
    freq             1      1

    Excluding object columns from a ``DataFrame`` description.

    >>> df.describe(exclude=[object])  # doctest: +SKIP
           categorical  numeric
    count            3      3.0
    unique           3      NaN
    top              f      NaN
    freq             1      NaN
    mean           NaN      2.0
    std            NaN      1.0
    min            NaN      1.0
    25%            NaN      1.5
    50%            NaN      2.0
    75%            NaN      2.5
    max            NaN      3.0

#### Работа с отсутствующими значениями

In [ ]:
new_rows = pd.DataFrame([{'Name': 'Frank'}, {'Name': 'Grace'}])
new_rows

In [ ]:
df

In [ ]:
df = pd.concat([df, new_rows], ignore_index=True)

df

In [ ]:
sum(df['Age']) / len(df)

In [ ]:
df

In [ ]:
df_new = df.fillna('-')
df_new

In [ ]:
df_new['Score']

In [ ]:
# Заполнение отсутствующих значений

df['Age'] = df['Age'].fillna(30)
df

In [ ]:
sum(df['Age']) / len(df)

In [ ]:
# Удаление строк с пропущенными значениями
df = df.dropna()
df

#### Оси

1. **Ось 0 (Axis 0)** — это строки (индексация по строкам).
   - Эта ось идет сверху вниз.
   - Многие операции по умолчанию выполняются вдоль оси 0, например, агрегационные функции вроде `sum()`, `mean()`, и т.д., которые по умолчанию вычисляются для каждого столбца, объединяя строки.

2. **Ось 1 (Axis 1)** — это столбцы (индексация по столбцам).
   - Эта ось идет слева направо.
   - При выполнении операций вдоль оси 1 агрегируются столбцы. Например, функция `sum(axis=1)` будет суммировать значения вдоль строк (по каждому столбцу).

<img src="axes.png" style="width: 400px;"/>

In [ ]:
data = {
    'A': [1, 2, 5],
    'B': [4, 3, 7],
    'C': [3, 6, 9]
}

df = pd.DataFrame(data)
df = df.transpose()
df

In [ ]:
df.axes

In [ ]:
df.sum()

In [ ]:
df.sum(axis=1)

### Примеры методов, использующих оси:

- `df.sum(axis=0)` — по умолчанию суммирует значения по оси 0 (по строкам для каждого столбца).
- `df.mean(axis=1)` — вычисляет среднее по строкам (агрегация столбцов).
- `df.drop(axis=1)` — удаляет столбец при использовании `axis=1`.