In [114]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import tree
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV

In [ ]:
# работает через direct_url
standart_url = 'https://drive.google.com/file/d/14upz4Y45oImXk52zjZZ62SxM889WIhTp/view?usp=drive_link'
direct_url = 'https://drive.google.com/uc?export=view&id=14upz4Y45oImXk52zjZZ62SxM889WIhTp'

data_load = pd.read_csv(direct_url)

In [ ]:
df = data_load.copy()
df.head()

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

Данные содержат 23 признака и 145 460 наблюдений. Из этих 23 признаков шесть — категориальные, в одном записана дата, а остальные являются непрерывными числовыми данными.

Примеры числовых признаков: температура, скорость ветра, влажность, облачность, атмосферное давление в разное время суток, количество осадков, испарение, количество часов с солнечной погодой.
Примеры категориальных признаков: местоположение, направление ветра в разное время суток, наличие дождя сегодня или завтра.
Целевой переменной является столбец RainTomorrow. Значение этой переменной мы и будем пытаться предсказать.

Подробная расшифровка всех признаков
Date — дата, в которую зафиксировано наблюдение;
Location — местонахождение метеорологической станции;
MinTemp — минимальная температура (℃);
MaxTemp — максимальная температура (℃);
Rainfall — количество осадков (дождь) за сутки (мм);
Evaporation — количество испарений до 9 утра (мм);
Sunshine — количество часов в сутках, когда светило солнце;
WindGustDir — направление самого сильного порыва ветра за последние 24 часа;
WindGustSpeed — скорость самого сильного порыва ветра за последние 24 часа;
WindDir9am — направление ветра в 9 утра;
WindDir3pm — направление ветра в 3 часа дня;
WindSpeed9am — скорость ветра в 9 часов утра;
WindSpeed3pm — скорость ветра в 3 часа дня;
Humidity9am — влажность в 9 утра;
Humidity3pm — влажность в 3 часа дня;
Pressure9am — атмосферное давление в 9 утра;
Pressure3pm — атмосферное давление в 3 часа дня;
Cloud9am — часть неба, закрытая облаками, в 9 утра;
Cloud3pm — часть неба, закрытая облаками, в 3 часа дня;
Temp9am — температура в 9 утра;
Temp3pm — температура в 3 часа дня;
RainToday — наличие дождя в этот день;
RainTomorrow — наличие дождя на следующий день.

In [47]:
df.isnull().sum().sum()

343248

In [48]:
cols_was = df.shape[1]
cols_was

23

In [49]:
df.isnull().sum() > len(df) * 0.4

Date             False
Location         False
MinTemp          False
MaxTemp          False
Rainfall         False
Evaporation       True
Sunshine          True
WindGustDir      False
WindGustSpeed    False
WindDir9am       False
WindDir3pm       False
WindSpeed9am     False
WindSpeed3pm     False
Humidity9am      False
Humidity3pm      False
Pressure9am      False
Pressure3pm      False
Cloud9am         False
Cloud3pm          True
Temp9am          False
Temp3pm          False
RainToday        False
RainTomorrow     False
dtype: bool

In [50]:
# 1. Рассчитываем процент пропущенных значений для каждого столбца
#    и отфильтровываем столбцы, где этот процент превышает 40% (или 0.4)

threshold = (1 - 0.4) * len(df) # Минимальное количество непропущенных значений для сохранения столбца
df = df.dropna(axis='columns', thresh=threshold)

In [51]:
df.shape

(145460, 20)

**Задание 4.3**

Теперь обработаем признаки RainToday и RainTomorrow таким образом, чтобы вместо yes было значение 1, а вместо no — значение 0. Обратите внимание на то, что в признаках RainToday и RainTomorrow присутствуют пропуски, и их трогать не нужно, они должны остаться пропусками. Поэтому обрабатывайте столбцы таким образом, чтобы не видоизменить пропущенные значения.

Вычислите среднее арифметическое для преобразованного признака RainToday и запишите его в ответ, предварительно округлив до двух знаков после точки-разделителя.

In [52]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow'],
      dtype='object')

In [53]:
df['RainToday'].value_counts()

RainToday
No     110319
Yes     31880
Name: count, dtype: int64

In [54]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     110316
Yes     31877
Name: count, dtype: int64

In [55]:
df.RainToday = df.RainToday.map({'No': 0, 'Yes': 1})
df.RainTomorrow = df.RainTomorrow.map({'No': 0, 'Yes': 1})

In [58]:
df['RainToday'].value_counts()

RainToday
0.0    110319
1.0     31880
Name: count, dtype: int64

In [59]:
df['RainTomorrow'].value_counts()

RainTomorrow
0.0    110316
1.0     31877
Name: count, dtype: int64

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   WindGustDir    135134 non-null  object
 6   WindGustSpeed  135197 non-null  float64
 7   WindDir9am     134894 non-null  object
 8   WindDir3pm     141232 non-null  object
 9   WindSpeed9am   143693 non-null  float64
 10  WindSpeed3pm   142398 non-null  float64
 11  Humidity9am    142806 non-null  float64
 12  Humidity3pm    140953 non-null  float64
 13  Pressure9am    130395 non-null  float64
 14  Pressure3pm    130432 non-null  float64
 15  Cloud9am       89572 non-null   float64
 16  Temp9am        143693 non-null  float64
 17  Temp3pm        141851 non-null  float64
 18  RainToday      142199 non-null  float64
 19  RainTomorrow   142193 non-null  float64
dtypes: float64(15), object(5)
memory usage: 22.2+ MB

In [61]:
df.describe()

,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Temp9am,Temp3pm,RainToday,RainTomorrow
count,143975.000000,144199.000000,142199.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,89572.000000,143693.000000,141851.00000,142199.000000,142193.000000
mean,12.194034,23.221348,2.360918,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,4.447461,16.990631,21.68339,0.224193,0.224181
std,6.398495,7.119049,8.478060,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,2.887159,6.488753,6.93665,0.417051,0.417043
min,-8.500000,-4.800000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,0.000000,-7.200000,-5.40000,0.000000,0.000000
25%,7.600000,17.900000,0.000000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,1.000000,12.300000,16.60000,0.000000,0.000000
50%,12.000000,22.600000,0.000000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,5.000000,16.700000,21.10000,0.000000,0.000000
75%,16.900000,28.200000,0.800000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,7.000000,21.600000,26.40000,0.000000,0.000000
max,33.900000,48.100000,371.000000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,9.000000,40.200000,46.70000,1.000000,1.000000

**Задание 4.4**

Обработайте признак Date таким образом, чтобы выделить в отдельный признак Month (номер месяца). Изначальный признак Date удалите. Определите, какой месяц имеет самую большую часть дождливых дней относительно всех дней месяца. В качестве ответа введите порядковый номер месяца.

In [65]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow'],
      dtype='object')

In [66]:
df['Date'] = pd.to_datetime(df['Date'])

In [67]:
df['Date'].describe()

count                           145460
mean     2013-04-04 21:08:51.907053568
min                2007-11-01 00:00:00
25%                2011-01-11 00:00:00
50%                2013-06-02 00:00:00
75%                2015-06-14 00:00:00
max                2017-06-25 00:00:00
Name: Date, dtype: object

In [68]:
# Шаг 2: Извлекаем номер месяца и создаем новый столбец 'Month'
df['Month'] = df['Date'].dt.month

In [69]:
df['Month'].describe()

count    145460.000000
mean          6.399615
std           3.427262
min           1.000000
25%           3.000000
50%           6.000000
75%           9.000000
max          12.000000
Name: Month, dtype: float64

In [70]:
df = df.drop(columns='Date')

In [71]:
df.columns

Index(['Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm', 'Cloud9am', 'Temp9am', 'Temp3pm', 'RainToday',
       'RainTomorrow', 'Month'],
      dtype='object')

In [73]:
df['Month'].value_counts().sum()

145460

In [74]:
df.groupby('Month')['RainToday'].sum().sort_values() / df['Month'].value_counts().sum()

Month
2     0.014959
12    0.015839
10    0.015956
11    0.016603
1     0.016822
4     0.016850
9     0.017874
3     0.019462
5     0.019944
8     0.020473
7     0.021924
6     0.022460
Name: RainToday, dtype: float64

In [75]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

In [76]:
month_days_rain = df.groupby('Month')['RainToday'].sum()
for i in range(1, 13):
    print(i, month_days_rain[i] / days_in_month[i-1])

1 78.93548387096774
2 77.71428571428571
3 91.3225806451613
4 81.7
5 93.58064516129032
6 108.9
7 102.87096774193549
8 96.06451612903226
9 86.66666666666667
10 74.87096774193549
11 80.5
12 74.3225806451613

In [77]:
df_season = df.groupby('Month').mean(numeric_only=True)
df_season[['RainToday']]

       RainToday
Month
1       0.189484
2       0.206746
3       0.217135
4       0.216845
5       0.222163
6       0.263638
7       0.270736
8       0.253167
9       0.229135
10      0.196512
11      0.210843
12      0.213037

**Задание 4.5**

Обработайте оставшиеся категориальные признаки. С помощью метода get_dummies с настройками по умолчанию создайте dummy-переменные для всех категориальных признаков (их пять), которые есть в данных на этот момент.

Кодировку признаков важно выполнить именно в следующем порядке: categoricals = ['Month', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']. Это необходимо для того, чтобы ваши дальнейшие ответы сходились с нашим решением, так как алгоритм случайного леса, который мы будем использовать в дальнейшем, чувствителен к порядку столбцов. Аргумент categoricals передаётся в функцию pd.get_dummies() с использованием ключевого слова columns, а именно columns=categoricals.

Сколько теперь признаков в данных, если считать целевую переменную?

In [78]:
categoricals = ['Month', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']
df = pd.get_dummies(df, columns=categoricals)

In [79]:
df.shape

(145460, 124)

**Задание 4.6**

Осталось совсем немного. Удалите все строки, где есть пропуски. Далее разбейте данные на обучающую и тестовую выборки в соотношении 70/30, в качестве значения параметра random_state возьмите число 31.

Каково среднее значение целевой переменной на тестовой выборке? Ответ округлите до двух знаков после точки-разделителя.

In [80]:
df = df.dropna()

In [81]:
# делим выборку на фичи и таргет
target = 'RainTomorrow'
y = df[target]
X = df.drop(columns=target)

In [82]:
y.describe()

count    78257.000000
mean         0.227302
std          0.419092
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: RainTomorrow, dtype: float64

In [83]:
# Формируем обучающую и тестовую выборки
test_size = 0.3
random_state = 31
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=test_size, random_state=random_state)
print('Train shape: {}'.format(X_train.shape))
print('Test shape: {}'.format(X_test.shape))

Train shape: (54779, 123)
Test shape: (23478, 123)

In [111]:
Y_train, Y_test = y_train, y_test

In [84]:
y_test.describe()

count    23478.000000
mean         0.227703
std          0.419359
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: RainTomorrow, dtype: float64

**Задание 4.7**

Теперь давайте вспомним про бутстреп. Он не понадобится нам для решения этой задачи, но будет полезно реализовать его «вручную».

Сделайте оценку стандартного отклонения для среднего значения минимальной температуры для обучающей выборки (то есть для среднего значения по признаку MinTemp). Для этого сгенерируйте 1000 случайных выборок из наших данных — каждая из них должна быть такого же объёма, как и обучающая выборка. Для генерации выборки используйте np.random.randint(): сгенерируйте необходимое количество индексов и по ним извлеките соответствующие элементы выборки. Случайность фиксируйте с помощью np.random.seed(31).

Для каждой выборки вычислите среднее значение, а после найдите стандартное отклонение для этих значений. Ответ округлите до двух знаков после точки-разделителя.

In [87]:
df['MinTemp'].describe()

count    78257.000000
mean        12.924265
std          6.524590
min         -6.900000
25%          8.000000
50%         12.700000
75%         17.900000
max         31.400000
Name: MinTemp, dtype: float64

In [86]:
# copy-paste
def gbs(data, n):     
    inds = np.random.randint(0, len(data), (n, len(data))) #определяем индексы случайным образом
    numbers = data[inds] #выбираем значения по индексам
    return numbers
target = X_train['MinTemp'].values #выбираем целевую переменную
np.random.seed(31) #задаём параметр генератора случайных чисел
mean_values = [np.mean(x) for x in gbs(target, 1000)] #получаем все средние значения
np.std(mean_values) #находим для них стандартное отклонение

0.02879072820657669

**Задание 4.8**

Теперь можно перейти к обучению прогностических моделей. Начнём с того, что построим простейшую логистическую регрессию (без настройки гиперпараметров). Это будет та модель, с качеством которой мы будем сравнивать результаты, полученные далее.

В качестве ответа введите значение метрики roc_auc на тестовой выборке. Ответ округлите до двух знаков после точки-разделителя.

In [ ]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
preds_train = clf.predict(X_train)
preds_test = clf.predict(X_test)

In [99]:
roc_auc_score(y_test, preds_test)

0.7277651877254788

**Задание 4.9**

Теперь попробуйте обучить на наших данных другой алгоритм — дерево решений. С помощью GridSearchCV сделайте перебор гиперпараметров по следующей сетке:

```params = {'max_leaf_nodes': list(range(2, 10)), 'min_samples_split': [2, 3, 4], 'max_depth': [5,7,9,11]}```
Для параметра кросс-валидации cv задайте значение 3. Для решающего дерева определите параметр random_state=42. Остальные параметры оставьте по умолчанию.

1. Вычислите значение roc_auc для решающего дерева с гиперпараметрами, определёнными в качестве оптимальных. Ответ округлите до двух знаков после точки-разделителя.

In [108]:
params = {
    'max_leaf_nodes': list(range(2, 10)), 
    'min_samples_split': [2, 3, 4], 
    'max_depth': [5,7,9,11]
}

grid_search_cv = GridSearchCV(
    DecisionTreeClassifier(random_state=42), 
    params, 
    verbose=3, 
    cv=3)
grid_search_cv.fit(X_train, y_train)
print(grid_search_cv.best_params_)

Fitting 3 folds for each of 96 candidates, totalling 288 fits
[CV 1/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=2;, score=0.817 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=2;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=3;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=4;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=2, min_samples_split=4;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=3;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=4;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=5, max_leaf_nodes=3, min_samples_split=4;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=4, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=5, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=6, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=2;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=2;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=3;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=3;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=4;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=4;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=7, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=2;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=2;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=2;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=3;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=3;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=3;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=4;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=4;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=8, min_samples_split=4;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=2;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=2;, score=0.840 total time=   0.3s
[CV 3/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=2;, score=0.837 total time=   0.3s
[CV 1/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=3;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=3;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=3;, score=0.837 total time=   0.2s
[CV 1/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=4;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=4;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=5, max_leaf_nodes=9, min_samples_split=4;, score=0.837 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=2;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=2;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=3;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=4;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=2, min_samples_split=4;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=2;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=2;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=3;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=4;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=7, max_leaf_nodes=3, min_samples_split=4;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=4, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=5, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=6, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=2;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=2;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=3;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=3;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=4;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=4;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=7, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=2;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=2;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=2;, score=0.836 total time=   0.3s
[CV 1/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=3;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=3;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=3;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=4;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=4;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=8, min_samples_split=4;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=2;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=2;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=2;, score=0.837 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=3;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=3;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=3;, score=0.837 total time=   0.2s
[CV 1/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=4;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=4;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=7, max_leaf_nodes=9, min_samples_split=4;, score=0.837 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=2;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=2;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=3;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=4;, score=0.817 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=2, min_samples_split=4;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=2;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=2;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=2;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=3;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=3;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=3;, score=0.825 total time=   0.1s
[CV 1/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=4;, score=0.819 total time=   0.1s
[CV 2/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=4;, score=0.820 total time=   0.1s
[CV 3/3] END max_depth=9, max_leaf_nodes=3, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=4, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=2;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=3;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=5, min_samples_split=4;, score=0.825 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=2;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=2;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=3;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=3;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=4;, score=0.819 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=4;, score=0.820 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=6, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=2;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=2;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=2;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=3;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=3;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=3;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=4;, score=0.831 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=4;, score=0.834 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=7, min_samples_split=4;, score=0.832 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=2;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=2;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=2;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=3;, score=0.835 total time=   0.2s
[CV 2/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=3;, score=0.840 total time=   0.2s
[CV 3/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=3;, score=0.836 total time=   0.2s
[CV 1/3] END max_depth=9, max_leaf_nodes=8, min_samples_split=4;, score=0.835 total time=   0.2s

In [110]:
clf = DecisionTreeClassifier(max_depth = 5, max_leaf_nodes = 9, min_samples_split = 2, random_state=42)
clf.fit(X_train, y_train)
preds_train = clf.predict(X_train)
preds_test = clf.predict(X_test)
print(round(roc_auc_score(y_test, preds_test), 2))

0.7

**Задание 4.10**

К сожалению, деревья решений не помогли нам в улучшении качества модели, так что попробуем ещё уменьшить ошибку с помощью ансамблей.

Теперь постройте случайный лес, включающий 100 деревьев. Задайте параметр random_state=31. Остальные параметры оставьте по умолчанию.

Какой теперь будет метрика roc_auc на тестовой выборке? Ответ округлите до двух знаков после точки-разделителя.

In [115]:
# Задание 4.10
# copy-paste

clf = RandomForestClassifier(n_estimators = 100, random_state=31)
clf.fit(X_train, Y_train)
preds_train = clf.predict(X_train)
preds_test = clf.predict(X_test)
print(round(roc_auc_score(Y_test, preds_test), 2))

0.73

**Задание 4.11**

Основные параметры, которые отвечают за качество обучения в случайном лесе, следующие:'max_features', 'min_samples_leaf', 'max_depth'.

Возьмите случайный лес из 100 деревьев и найдите оптимальную комбинацию этих трёх параметров. Сетка для перебора следующая:
```{'max_features': [ 4, 5, 6, 7], 'min_samples_leaf': [3, 5, 7, 9, 11], 'max_depth': [5, 10, 15]}```
Перебор осуществите с помощью GridSearchCV. Для параметра кросс-валидации cv задайте значение 3. Случайности фиксируйте параметром random_state = 31. Остальные значения оставьте по умолчанию.

Какое значение roc_auc получилось для оптимальных гиперпараметров?

In [116]:
# Задание 4.11

params = {
    'max_features': [4, 5, 6, 7], 
    'min_samples_leaf': [3, 5, 7, 9, 11], 
    'max_depth': [5, 10, 15]
}
grid_search_cv = GridSearchCV(RandomForestClassifier(random_state=31), params, verbose=3, cv=3)
grid_search_cv.fit(X_train, Y_train)
print(grid_search_cv.best_params_)
clf = RandomForestClassifier(n_estimators = 100, max_depth=15, max_features=7, min_samples_leaf=3, random_state=31)
clf.fit(X_train, Y_train)
preds_train = clf.predict(X_train)
preds_test = clf.predict(X_test)
print(round(roc_auc_score(Y_test, preds_test), 2))

Fitting 3 folds for each of 60 candidates, totalling 180 fits
[CV 1/3] END max_depth=5, max_features=4, min_samples_leaf=3;, score=0.776 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=4, min_samples_leaf=3;, score=0.775 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=4, min_samples_leaf=3;, score=0.775 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=4, min_samples_leaf=5;, score=0.776 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=4, min_samples_leaf=5;, score=0.775 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=4, min_samples_leaf=5;, score=0.775 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=4, min_samples_leaf=7;, score=0.776 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=4, min_samples_leaf=7;, score=0.775 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=4, min_samples_leaf=7;, score=0.775 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=4, min_samples_leaf=9;, score=0.776 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=4, min_samples_leaf=9;, score=0.775 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=4, min_samples_leaf=9;, score=0.775 total time=   0.7s
[CV 1/3] END max_depth=5, max_features=4, min_samples_leaf=11;, score=0.776 total time=   0.7s
[CV 2/3] END max_depth=5, max_features=4, min_samples_leaf=11;, score=0.775 total time=   0.7s
[CV 3/3] END max_depth=5, max_features=4, min_samples_leaf=11;, score=0.775 total time=   0.7s
[CV 1/3] END max_depth=5, max_features=5, min_samples_leaf=3;, score=0.782 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=5, min_samples_leaf=3;, score=0.780 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_leaf=3;, score=0.781 total time=   0.8s
[CV 1/3] END max_depth=5, max_features=5, min_samples_leaf=5;, score=0.781 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=5, min_samples_leaf=5;, score=0.781 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_leaf=5;, score=0.781 total time=   0.8s
[CV 1/3] END max_depth=5, max_features=5, min_samples_leaf=7;, score=0.782 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=5, min_samples_leaf=7;, score=0.780 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_leaf=7;, score=0.782 total time=   0.8s
[CV 1/3] END max_depth=5, max_features=5, min_samples_leaf=9;, score=0.782 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=5, min_samples_leaf=9;, score=0.779 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_leaf=9;, score=0.781 total time=   0.8s
[CV 1/3] END max_depth=5, max_features=5, min_samples_leaf=11;, score=0.784 total time=   0.8s
[CV 2/3] END max_depth=5, max_features=5, min_samples_leaf=11;, score=0.781 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_leaf=11;, score=0.783 total time=   0.8s
[CV 1/3] END max_depth=5, max_features=6, min_samples_leaf=3;, score=0.795 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=6, min_samples_leaf=3;, score=0.793 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=6, min_samples_leaf=3;, score=0.796 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=6, min_samples_leaf=5;, score=0.793 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=6, min_samples_leaf=5;, score=0.792 total time=   0.8s
[CV 3/3] END max_depth=5, max_features=6, min_samples_leaf=5;, score=0.795 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=6, min_samples_leaf=7;, score=0.798 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=6, min_samples_leaf=7;, score=0.794 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=6, min_samples_leaf=7;, score=0.795 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=6, min_samples_leaf=9;, score=0.796 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=6, min_samples_leaf=9;, score=0.795 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=6, min_samples_leaf=9;, score=0.795 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=6, min_samples_leaf=11;, score=0.795 total time=   0.9s
[CV 2/3] END max_depth=5, max_features=6, min_samples_leaf=11;, score=0.798 total time=   0.9s
[CV 3/3] END max_depth=5, max_features=6, min_samples_leaf=11;, score=0.795 total time=   0.9s
[CV 1/3] END max_depth=5, max_features=7, min_samples_leaf=3;, score=0.798 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=7, min_samples_leaf=3;, score=0.801 total time=   1.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_leaf=3;, score=0.794 total time=   1.0s
[CV 1/3] END max_depth=5, max_features=7, min_samples_leaf=5;, score=0.798 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=7, min_samples_leaf=5;, score=0.801 total time=   1.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_leaf=5;, score=0.797 total time=   1.0s
[CV 1/3] END max_depth=5, max_features=7, min_samples_leaf=7;, score=0.794 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=7, min_samples_leaf=7;, score=0.800 total time=   1.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_leaf=7;, score=0.795 total time=   1.0s
[CV 1/3] END max_depth=5, max_features=7, min_samples_leaf=9;, score=0.796 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=7, min_samples_leaf=9;, score=0.800 total time=   1.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_leaf=9;, score=0.795 total time=   1.0s
[CV 1/3] END max_depth=5, max_features=7, min_samples_leaf=11;, score=0.796 total time=   1.0s
[CV 2/3] END max_depth=5, max_features=7, min_samples_leaf=11;, score=0.803 total time=   1.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_leaf=11;, score=0.795 total time=   1.0s
[CV 1/3] END max_depth=10, max_features=4, min_samples_leaf=3;, score=0.810 total time=   1.3s
[CV 2/3] END max_depth=10, max_features=4, min_samples_leaf=3;, score=0.815 total time=   1.3s
[CV 3/3] END max_depth=10, max_features=4, min_samples_leaf=3;, score=0.813 total time=   1.3s
[CV 1/3] END max_depth=10, max_features=4, min_samples_leaf=5;, score=0.812 total time=   1.3s
[CV 2/3] END max_depth=10, max_features=4, min_samples_leaf=5;, score=0.811 total time=   1.2s
[CV 3/3] END max_depth=10, max_features=4, min_samples_leaf=5;, score=0.813 total time=   1.3s
[CV 1/3] END max_depth=10, max_features=4, min_samples_leaf=7;, score=0.811 total time=   1.3s
[CV 2/3] END max_depth=10, max_features=4, min_samples_leaf=7;, score=0.812 total time=   1.2s
[CV 3/3] END max_depth=10, max_features=4, min_samples_leaf=7;, score=0.812 total time=   1.3s
[CV 1/3] END max_depth=10, max_features=4, min_samples_leaf=9;, score=0.809 total time=   1.2s
[CV 2/3] END max_depth=10, max_features=4, min_samples_leaf=9;, score=0.812 total time=   1.2s
[CV 3/3] END max_depth=10, max_features=4, min_samples_leaf=9;, score=0.811 total time=   1.2s
[CV 1/3] END max_depth=10, max_features=4, min_samples_leaf=11;, score=0.813 total time=   1.2s
[CV 2/3] END max_depth=10, max_features=4, min_samples_leaf=11;, score=0.812 total time=   1.2s
[CV 3/3] END max_depth=10, max_features=4, min_samples_leaf=11;, score=0.813 total time=   1.2s
[CV 1/3] END max_depth=10, max_features=5, min_samples_leaf=3;, score=0.819 total time=   1.5s
[CV 2/3] END max_depth=10, max_features=5, min_samples_leaf=3;, score=0.826 total time=   1.4s
[CV 3/3] END max_depth=10, max_features=5, min_samples_leaf=3;, score=0.820 total time=   1.4s
[CV 1/3] END max_depth=10, max_features=5, min_samples_leaf=5;, score=0.821 total time=   1.4s
[CV 2/3] END max_depth=10, max_features=5, min_samples_leaf=5;, score=0.826 total time=   1.5s
[CV 3/3] END max_depth=10, max_features=5, min_samples_leaf=5;, score=0.820 total time=   1.5s
[CV 1/3] END max_depth=10, max_features=5, min_samples_leaf=7;, score=0.820 total time=   1.4s
[CV 2/3] END max_depth=10, max_features=5, min_samples_leaf=7;, score=0.819 total time=   1.4s
[CV 3/3] END max_depth=10, max_features=5, min_samples_leaf=7;, score=0.820 total time=   1.4s
[CV 1/3] END max_depth=10, max_features=5, min_samples_leaf=9;, score=0.819 total time=   1.4s
[CV 2/3] END max_depth=10, max_features=5, min_samples_leaf=9;, score=0.824 total time=   1.4s
[CV 3/3] END max_depth=10, max_features=5, min_samples_leaf=9;, score=0.816 total time=   1.4s
[CV 1/3] END max_depth=10, max_features=5, min_samples_leaf=11;, score=0.822 total time=   1.4s
[CV 2/3] END max_depth=10, max_features=5, min_samples_leaf=11;, score=0.826 total time=   1.4s
[CV 3/3] END max_depth=10, max_features=5, min_samples_leaf=11;, score=0.817 total time=   1.4s
[CV 1/3] END max_depth=10, max_features=6, min_samples_leaf=3;, score=0.832 total time=   1.6s
[CV 2/3] END max_depth=10, max_features=6, min_samples_leaf=3;, score=0.834 total time=   1.6s
[CV 3/3] END max_depth=10, max_features=6, min_samples_leaf=3;, score=0.830 total time=   1.6s
[CV 1/3] END max_depth=10, max_features=6, min_samples_leaf=5;, score=0.829 total time=   1.6s
[CV 2/3] END max_depth=10, max_features=6, min_samples_leaf=5;, score=0.835 total time=   1.6s
[CV 3/3] END max_depth=10, max_features=6, min_samples_leaf=5;, score=0.828 total time=   1.6s
[CV 1/3] END max_depth=10, max_features=6, min_samples_leaf=7;, score=0.831 total time=   1.6s
[CV 2/3] END max_depth=10, max_features=6, min_samples_leaf=7;, score=0.835 total time=   1.6s
[CV 3/3] END max_depth=10, max_features=6, min_samples_leaf=7;, score=0.831 total time=   1.6s
[CV 1/3] END max_depth=10, max_features=6, min_samples_leaf=9;, score=0.830 total time=   1.6s
[CV 2/3] END max_depth=10, max_features=6, min_samples_leaf=9;, score=0.835 total time=   1.6s
[CV 3/3] END max_depth=10, max_features=6, min_samples_leaf=9;, score=0.831 total time=   1.6s
[CV 1/3] END max_depth=10, max_features=6, min_samples_leaf=11;, score=0.831 total time=   1.6s
[CV 2/3] END max_depth=10, max_features=6, min_samples_leaf=11;, score=0.835 total time=   1.6s
[CV 3/3] END max_depth=10, max_features=6, min_samples_leaf=11;, score=0.827 total time=   1.6s
[CV 1/3] END max_depth=10, max_features=7, min_samples_leaf=3;, score=0.833 total time=   1.9s
[CV 2/3] END max_depth=10, max_features=7, min_samples_leaf=3;, score=0.839 total time=   1.9s
[CV 3/3] END max_depth=10, max_features=7, min_samples_leaf=3;, score=0.831 total time=   1.9s
[CV 1/3] END max_depth=10, max_features=7, min_samples_leaf=5;, score=0.834 total time=   1.8s
[CV 2/3] END max_depth=10, max_features=7, min_samples_leaf=5;, score=0.838 total time=   1.8s
[CV 3/3] END max_depth=10, max_features=7, min_samples_leaf=5;, score=0.832 total time=   1.9s
[CV 1/3] END max_depth=10, max_features=7, min_samples_leaf=7;, score=0.831 total time=   1.8s
[CV 2/3] END max_depth=10, max_features=7, min_samples_leaf=7;, score=0.838 total time=   1.8s
[CV 3/3] END max_depth=10, max_features=7, min_samples_leaf=7;, score=0.829 total time=   1.8s
[CV 1/3] END max_depth=10, max_features=7, min_samples_leaf=9;, score=0.833 total time=   1.8s
[CV 2/3] END max_depth=10, max_features=7, min_samples_leaf=9;, score=0.838 total time=   1.8s
[CV 3/3] END max_depth=10, max_features=7, min_samples_leaf=9;, score=0.831 total time=   1.8s
[CV 1/3] END max_depth=10, max_features=7, min_samples_leaf=11;, score=0.834 total time=   1.9s
[CV 2/3] END max_depth=10, max_features=7, min_samples_leaf=11;, score=0.837 total time=   1.9s
[CV 3/3] END max_depth=10, max_features=7, min_samples_leaf=11;, score=0.828 total time=   2.0s
[CV 1/3] END max_depth=15, max_features=4, min_samples_leaf=3;, score=0.829 total time=   1.9s
[CV 2/3] END max_depth=15, max_features=4, min_samples_leaf=3;, score=0.836 total time=   1.8s
[CV 3/3] END max_depth=15, max_features=4, min_samples_leaf=3;, score=0.829 total time=   1.8s
[CV 1/3] END max_depth=15, max_features=4, min_samples_leaf=5;, score=0.828 total time=   1.8s
[CV 2/3] END max_depth=15, max_features=4, min_samples_leaf=5;, score=0.834 total time=   1.9s
[CV 3/3] END max_depth=15, max_features=4, min_samples_leaf=5;, score=0.829 total time=   1.9s
[CV 1/3] END max_depth=15, max_features=4, min_samples_leaf=7;, score=0.828 total time=   1.8s
[CV 2/3] END max_depth=15, max_features=4, min_samples_leaf=7;, score=0.832 total time=   1.7s
[CV 3/3] END max_depth=15, max_features=4, min_samples_leaf=7;, score=0.827 total time=   1.7s
[CV 1/3] END max_depth=15, max_features=4, min_samples_leaf=9;, score=0.825 total time=   1.7s
[CV 2/3] END max_depth=15, max_features=4, min_samples_leaf=9;, score=0.832 total time=   1.6s
[CV 3/3] END max_depth=15, max_features=4, min_samples_leaf=9;, score=0.824 total time=   1.7s
[CV 1/3] END max_depth=15, max_features=4, min_samples_leaf=11;, score=0.826 total time=   1.7s
[CV 2/3] END max_depth=15, max_features=4, min_samples_leaf=11;, score=0.831 total time=   1.8s
[CV 3/3] END max_depth=15, max_features=4, min_samples_leaf=11;, score=0.824 total time=   1.6s
[CV 1/3] END max_depth=15, max_features=5, min_samples_leaf=3;, score=0.832 total time=   2.1s
[CV 2/3] END max_depth=15, max_features=5, min_samples_leaf=3;, score=0.843 total time=   2.1s
[CV 3/3] END max_depth=15, max_features=5, min_samples_leaf=3;, score=0.833 total time=   2.1s
[CV 1/3] END max_depth=15, max_features=5, min_samples_leaf=5;, score=0.835 total time=   2.2s
[CV 2/3] END max_depth=15, max_features=5, min_samples_leaf=5;, score=0.843 total time=   2.1s
[CV 3/3] END max_depth=15, max_features=5, min_samples_leaf=5;, score=0.834 total time=   2.1s
[CV 1/3] END max_depth=15, max_features=5, min_samples_leaf=7;, score=0.834 total time=   2.0s
[CV 2/3] END max_depth=15, max_features=5, min_samples_leaf=7;, score=0.839 total time=   1.9s
[CV 3/3] END max_depth=15, max_features=5, min_samples_leaf=7;, score=0.830 total time=   2.0s
[CV 1/3] END max_depth=15, max_features=5, min_samples_leaf=9;, score=0.832 total time=   1.9s
[CV 2/3] END max_depth=15, max_features=5, min_samples_leaf=9;, score=0.838 total time=   1.9s
[CV 3/3] END max_depth=15, max_features=5, min_samples_leaf=9;, score=0.831 total time=   1.9s
[CV 1/3] END max_depth=15, max_features=5, min_samples_leaf=11;, score=0.834 total time=   1.9s
[CV 2/3] END max_depth=15, max_features=5, min_samples_leaf=11;, score=0.838 total time=   1.9s
[CV 3/3] END max_depth=15, max_features=5, min_samples_leaf=11;, score=0.831 total time=   1.9s
[CV 1/3] END max_depth=15, max_features=6, min_samples_leaf=3;, score=0.841 total time=   2.4s
[CV 2/3] END max_depth=15, max_features=6, min_samples_leaf=3;, score=0.847 total time=   2.4s
[CV 3/3] END max_depth=15, max_features=6, min_samples_leaf=3;, score=0.840 total time=   2.4s
[CV 1/3] END max_depth=15, max_features=6, min_samples_leaf=5;, score=0.842 total time=   2.3s
[CV 2/3] END max_depth=15, max_features=6, min_samples_leaf=5;, score=0.847 total time=   2.3s
[CV 3/3] END max_depth=15, max_features=6, min_samples_leaf=5;, score=0.839 total time=   2.3s
[CV 1/3] END max_depth=15, max_features=6, min_samples_leaf=7;, score=0.842 total time=   2.2s
[CV 2/3] END max_depth=15, max_features=6, min_samples_leaf=7;, score=0.845 total time=   2.3s
[CV 3/3] END max_depth=15, max_features=6, min_samples_leaf=7;, score=0.841 total time=   2.3s
[CV 1/3] END max_depth=15, max_features=6, min_samples_leaf=9;, score=0.840 total time=   2.2s
[CV 2/3] END max_depth=15, max_features=6, min_samples_leaf=9;, score=0.845 total time=   2.2s
[CV 3/3] END max_depth=15, max_features=6, min_samples_leaf=9;, score=0.837 total time=   2.4s
[CV 1/3] END max_depth=15, max_features=6, min_samples_leaf=11;, score=0.840 total time=   2.2s
[CV 2/3] END max_depth=15, max_features=6, min_samples_leaf=11;, score=0.846 total time=   2.2s
[CV 3/3] END max_depth=15, max_features=6, min_samples_leaf=11;, score=0.838 total time=   2.2s
[CV 1/3] END max_depth=15, max_features=7, min_samples_leaf=3;, score=0.845 total time=   2.8s
[CV 2/3] END max_depth=15, max_features=7, min_samples_leaf=3;, score=0.850 total time=   2.7s
[CV 3/3] END max_depth=15, max_features=7, min_samples_leaf=3;, score=0.845 total time=   2.8s
[CV 1/3] END max_depth=15, max_features=7, min_samples_leaf=5;, score=0.844 total time=   2.9s
[CV 2/3] END max_depth=15, max_features=7, min_samples_leaf=5;, score=0.849 total time=   2.7s
[CV 3/3] END max_depth=15, max_features=7, min_samples_leaf=5;, score=0.844 total time=   2.8s
[CV 1/3] END max_depth=15, max_features=7, min_samples_leaf=7;, score=0.842 total time=   2.7s
[CV 2/3] END max_depth=15, max_features=7, min_samples_leaf=7;, score=0.850 total time=   2.5s
[CV 3/3] END max_depth=15, max_features=7, min_samples_leaf=7;, score=0.841 total time=   2.6s
[CV 1/3] END max_depth=15, max_features=7, min_samples_leaf=9;, score=0.842 total time=   2.5s
[CV 2/3] END max_depth=15, max_features=7, min_samples_leaf=9;, score=0.848 total time=   2.5s
[CV 3/3] END max_depth=15, max_features=7, min_samples_leaf=9;, score=0.841 total time=   2.6s
[CV 1/3] END max_depth=15, max_features=7, min_samples_leaf=11;, score=0.840 total time=   2.5s
[CV 2/3] END max_depth=15, max_features=7, min_samples_leaf=11;, score=0.847 total time=   2.4s
[CV 3/3] END max_depth=15, max_features=7, min_samples_leaf=11;, score=0.840 total time=   2.5s
{'max_depth': 15, 'max_features': 7, 'min_samples_leaf': 3}
0.7

**Задание 4.12**

Как мы говорили в предыдущем уроке, благодаря случайному лесу можно узнать, какие признаки оказывают большее влияние на целевую переменную по сравнению с другими.

Оцените значимость признаков. Отметьте три признака, которые дают наибольший вклад в целевую переменную (в каждой колонке находится как минимум один верный вариант ответа):

In [118]:
# Задание 4.12

feature_names = [x for x in df if x != 'RainTomorrow']
pd.DataFrame({'feat': feature_names,
              'coef': clf.feature_importances_}).sort_values(by='coef', ascending=False)

                   feat      coef
7           Humidity3pm  0.250783
2              Rainfall  0.079757
6           Humidity9am  0.070403
10             Cloud9am  0.067092
9           Pressure3pm  0.065272
..                  ...       ...
50   Location_Newcastle  0.000000
62  Location_SalmonGums  0.000000
51        Location_Nhil  0.000000
52   Location_NorahHead  0.000000
40   Location_GoldCoast  0.000000

[123 rows x 2 columns]