## Функции

### План

- Функции в Python
- Параметры функции
- Аргументы по умолчанию
- Запакованные переменные и аргументы
- Анонимные (lambda) функции
- ---
- Область видимости, вложенные функции
- Функции высшего порядка
- Декораторы
- Рекурсия

**Функции в Python** - это удобный способ организации и структурирования кода. Они позволяют объединить повторяющиеся фрагменты кода в отдельные блоки, которые можно вызывать из разных мест программы.

* Повторное использование кода
* Модульность
* Абстракция
* Улучшение структуры кода
* Повышение эффективности
* Разделение ответственности

In [ ]:
# заголовок функции
def имя_функции(параметры):
    # тело функции - выполняемые операции
    # return - возвращаемое значение (если необходимо)

Параметры – это переменные, которые определяются в момент создания функции и используется функцией для выполнения работы.

Аргументы – это конкретные значения, которые передаются в функцию при её вызове.

[Встроенные функции Python](https://docs.python.org/3/library/functions.html)

In [1]:
lst = [10, -8, 11, 15, 1, -9]
max_el = max(lst)
max_el

15

In [2]:
def max_test(my_lst):
    max_val = my_lst[0]
    for el in my_lst[1:]:
        if el > max_val:
            max_val = el
    return max_val

In [3]:
max_el = max_test(lst)
print(max_el)

15

In [4]:
def avg_num(lst):
    if lst:
        n = sum(lst) / len(lst)
        return n
    return 0

In [5]:
avg_ = avg_num([1, 2])
print(avg_)

1.5

In [6]:
print(avg_num([]))

0

### Параметры функции

Если мы передаем аргументы, перечисляя их значения при вызове функции, то такие аргументы называются позиционными.

Так же мы можем передать значение аргумента по его имени. Такой аргумент назвается именованным. 

** Когда у функции большое количество параметров, то вспомнить порядок их перечисления бывает сложно. 

Сначала передаем порядковые аргументы, а затем именованные. Для именованных порядок записи не важен.

In [7]:
def create_profile(name, age, city):
    print(name)
    print(age)
    print(city)
    print('---')
    print(f"Создан профиль пользователя: Имя - {name}, Возраст - {age}, Город - {city}.")
    print()

# Вызов функции с позиционными аргументами
create_profile("Анна", 25, "Москва")

create_profile("Анна", "Москва", 25)

Анна
25
Москва
---
Создан профиль пользователя: Имя - Анна, Возраст - 25, Город - Москва.

Анна
Москва
25
---
Создан профиль пользователя: Имя - Анна, Возраст - Москва, Город - 25.

In [8]:
name1 = 'Анна'
age = 25
gorod = 'Москва'
create_profile(name1, city=gorod, age=age)

Анна
25
Москва
---
Создан профиль пользователя: Имя - Анна, Возраст - 25, Город - Москва.

In [9]:
create_profile("Оксана", city='Уфа', age=35)

Оксана
35
Уфа
---
Создан профиль пользователя: Имя - Оксана, Возраст - 35, Город - Уфа.

In [10]:
# Вызов функции с именованными аргументами
create_profile(city="Санкт-Петербург", name="Иван", age=30)

Иван
30
Санкт-Петербург
---
Создан профиль пользователя: Имя - Иван, Возраст - 30, Город - Санкт-Петербург.

- Используйте позиционные аргументы, когда порядок естественный и очевидный.
- Используйте именованные аргументы, когда количество параметров большое или когда некоторые из них имеют значения по умолчанию.
- При использовании обоих типов аргументов передавайте сначала позиционные, а затем именованные.

### Аргументы по умолчанию

Параметры по умолчанию позволяют задать значения, которые будут использоваться для аргументов функции, если при вызове функции эти аргументы не переданы.

Такие аргументы необязательно явно задавать при вызове функции, в таком случае она будет работать с значениями по умолчанию.

In [ ]:
print(*objects, sep=' ', end='\n', file=None, flush=False)

In [2]:
# sep
print('тестируем', 'функцию', 'print')
print('test')

тестируем функцию print
test

In [3]:
print('тестируем', 'функцию', 'print', sep=', ')
print('test')

тестируем, функцию, print
test

In [4]:
# end
print('Функция — это')
print('фрагмент программного кода, к которому можно обратиться из другого места программы.')

Функция — это
фрагмент программного кода, к которому можно обратиться из другого места программы.

In [5]:
print('Функция — это', end=' ')
print('фрагмент программного кода, к которому можно обратиться из другого места программы.')

Функция — это фрагмент программного кода, к которому можно обратиться из другого места программы.

In [6]:
# file
file = open('print.txt','w') # открываем файл
print('какой-то вывод', file=file) 
file.close()  # закрываем файл

In [7]:
def func1(a, b=10):
    pass

def func2(a=10, b):
    pass

SyntaxError: parameter without a default follows parameter with a default (119820441.py, line 4)

In [8]:
def generate_invoice(invoice_number, tax_percentage=20):
    """
    Функция для генерации счета на оплату.

    :param invoice_number: Номер счета.
    :param tax_percentage: Процент налога (по умолчанию 20).
    :return: Сгенерированный счет на оплату.
    """
    invoice = {
        "invoice_number": invoice_number,
        "tax_percentage": tax_percentage,
        # другие поля счета
    }
    return invoice

# Генерация счета с указанным номером счета и стандартным налоговым процентом
invoice1 = generate_invoice("INV-001")
print(invoice1)

# Генерация счета с указанным номером счета и налоговым процентом
invoice2 = generate_invoice("INV-002", 15)
print(invoice2)

{'invoice_number': 'INV-001', 'tax_percentage': 20}
{'invoice_number': 'INV-002', 'tax_percentage': 15}

docstring

- https://peps.python.org/pep-0257/
- Перевод - https://habr.com/ru/articles/499358/

Docstring может быть многострочным и может содержать информацию о параметрах, возвращаемых значениях, примерах использования, особенностях работы функции и т. д. Важно помнить, что docstring является обязательным элементом хорошего стиля программирования и помогает другим разработчикам (и вам самим) легче понять и использовать код.

In [9]:
print(generate_invoice.__doc__)

    Функция для генерации счета на оплату.

    :param invoice_number: Номер счета.
    :param tax_percentage: Процент налога (по умолчанию 20).
    :return: Сгенерированный счет на оплату.

In [10]:
help(generate_invoice)

Help on function generate_invoice in module __main__:

generate_invoice(invoice_number, tax_percentage=20)
    Функция для генерации счета на оплату.

    :param invoice_number: Номер счета.
    :param tax_percentage: Процент налога (по умолчанию 20).
    :return: Сгенерированный счет на оплату.

In [11]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [13]:
def calculate_price(price, discount_price=0, is_vip=False):
    """
    Функция для вычисления итоговой стоимости товара с учетом скидки

    :param price: Исходная цена товара.
    :param discount_percent: Процент скидки.
    :param is_vip: Флаг, указывающий, является ли покупатель VIP-клиентом. Если покупатель VIP-клиент, то к скидке прибавляется 5%
    :return: Итоговая цена.
    """
    discount_price += 5 if is_vip else 0
    # discount_price = discount_price + ...
    return price * ( 1 - discount_price / 100)

In [14]:
price1 = calculate_price(100)
print(f"Цена без акции: {price1}")

price1 = calculate_price(100, 10)
print(f"Цена по акции -10%: {price1}")

price2 = calculate_price(100, 10, True)
print(f"Цена по акции -10% для VIP-клиента: {price2}")

price3 = calculate_price(100, is_vip=True)
print(f"Цена без акции для VIP-клиента: {price3}")

Цена без акции: 100.0
Цена по акции -10%: 90.0
Цена по акции -10% для VIP-клиента: 85.0
Цена без акции для VIP-клиента: 95.0

#### Проблемы аргументов по умолчанию

In [15]:
def test(lst=[]):
    lst.append(100)
    print(lst)

a = [10,]
test(a)
a

[10, 100]

[10, 100]

In [18]:
test()

[100, 100, 100]

In [19]:
def test(lst=None):
    if not lst: # if lst not is None
        return [100]
    lst += [100]
    return lst

a = [10,]
test(a)
a

[10, 100]

In [22]:
test()

[100]

### Запакованные переменные и аргументы

Термин "запакованные переменные" используется когда присваиваем одновременно несколько значений в одну переменную или коллекцию данных. 

Запаковка значений может быть выполнена с помощью различных структур данных, например, кортежи (tuples) и списки (lists).

Термин "распакованные переменные" используется когда присваиваем значения из структуры данных (кортежа, списка и т.д.) отдельным переменным.

In [23]:
# запаковка в кортеж
person = 'Сидоров Петр Иванович', 30, 'Москва'
print(person)

('Сидоров Петр Иванович', 30, 'Москва')

In [24]:
# распаковка из кортежа
fio, age, region = person
print(fio)
print(age)
print(region)

Сидоров Петр Иванович
30
Москва

In [25]:
# Автоматическая запаковка-распаковка
a, b = 1, 2
print(a)
print(b)

1
2

In [26]:
a, b

(1, 2)

In [37]:
numbers = [1, 2, 3, 4, 5]
first, *second, rest = numbers
# Оператор * означает, что остаток списка запакуется в одну переменную
print(first)
print(second)
print(rest)

1
[2, 3, 4]
5

***
*Запакованные аргументы*

In [38]:
def average2(a, b):
    return (a+b)/2

print(average2(2, 4))

3.0

In [39]:
def average3(a, b, c):
    return (a+b+c)/3

print(average3(2, 4, 6))

4.0

In [40]:
def average4(a, b, c, d):
    return (a+b+c+d)/4

print(average4(2, 4, 6, 8))

5.0

In [41]:
def average(*args):
    print(type(args))
    if len(args) == 0:
        return 0  # Если аргументов нет, возвращаем 0

    return sum(args) / len(args)

In [42]:
print(average(2, 4, 6, 8))

print(average(10, 20, 30, 40, 50))

print(average(5))

print(average())

<class 'tuple'>
5.0
<class 'tuple'>
30.0
<class 'tuple'>
5.0
<class 'tuple'>
0

Запакованные аргументы полезны, когда вы не знаете заранее, сколько аргументов будет передано в функцию или когда вы хотите передать переменное количество аргументов без явного перечисления каждого из них при вызове функции.

In [46]:
print(['Python', 'Functions'], 'test')

['Python', 'Functions'] test

In [43]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [ ]:
# Написать функцию, которая принимает произвольное количество интервалов в минутах и возвращает их общую длительность в часах и минутах.

calc_time(15, 20, 25, 10)

In [47]:
def calc_time(*args):
    return divmod(sum(args), 60)

In [49]:
calc_time(15, 20, 25, 10, 100)

(2, 50)

Для именованных аргументов используем оператор **.

Аргументы **kwargs (сокращение от "keyword arguments") используются для передачи и обработки произвольного количества именованных аргументов в функцию. kwargs представляет собой словарь, в котором ключи - это имена аргументов, а значения - соответствующие им значения.

In [50]:
def create_user_profile(first_name, last_name, **kwargs):
    """
    Создаёт профиль пользователя с обязательными и дополнительными параметрами.

    :param first_name: Имя пользователя
    :param last_name: Фамилия пользователя
    :param kwargs: Дополнительные параметры профиля
    :return: Словарь с данными профиля пользователя
    """
    profile = {
        'first_name': first_name,
        'last_name': last_name,
    }
    
    # Добавляем все дополнительные параметры в профиль
    # for key, value in kwargs.items():
    #     profile[key] = value

    # profile = **profile, **kwargs
    profile = profile | kwargs
    
    return profile

In [53]:
def create_user_profile2(**kwargs):
    """
    Создаёт профиль пользователя 

    :param kwargs: Параметры профиля
    :return: Словарь с данными профиля пользователя
    """
    profile = {
        'fio': f"{kwargs['first_name']} {kwargs['last_name']}",
    }
    
    # Добавляем все дополнительные параметры в профиль
    profile = profile | {key:value for key, value in kwargs.items() if key not in ('first_name', 'last_name')}
    
    return profile

In [54]:
# Пример использования функции с дополнительными аргументами
user1_2 = create_user_profile2(
    first_name="Иван",
    last_name="Иванов",
    age=30,
    email="ivan.ivanov@example.com",
    city="Москва"
)
print(user1_2)

{'fio': 'Иван Иванов', 'age': 30, 'email': 'ivan.ivanov@example.com', 'city': 'Москва'}

In [55]:
user2_2 = create_user_profile2(
    first_name="Анна",
    last_name="Петрова",
    occupation="Инженер",
    phone="+7-123-456-7890"
)

print(user2_2)

{'fio': 'Анна Петрова', 'occupation': 'Инженер', 'phone': '+7-123-456-7890'}

**Преимущества использования запакованных аргументов**

1. Гибкость функций:
   - Позволяют создавать функции, которые могут обрабатывать различное количество аргументов без необходимости заранее знать их количество.

2. Упрощение кода:
   - Избегают необходимости создавать множество версий функций для разного количества аргументов.

3. Повышенная универсальность:
   - Позволяют передавать аргументы из других коллекций (например, списков или словарей) без необходимости распаковывать их вручную.

4. Поддержка расширяемости:
   - Облегчают добавление новых параметров в функции без нарушения существующего кода.

In [56]:
# функция логирования, принимающая любое количество сообщений и уровней логирования
def log_messages(*messages, **levels):
    for i, message in enumerate(messages, 1):
        level = levels.get(i, 'INFO')
        print(f"[{level}] Сообщение {i}: {message}")

# Вызов функции с различными аргументами
log_messages("Система запущена", "Произошла ошибка", "Пользователь вошёл", 1="DEBUG", 2="ERROR")

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3932452437.py, line 8)

In [57]:
def log_messages(*messages, **levels):
    for i, message in enumerate(messages, 1):
        # Добавляем префикс 'level_' к номеру сообщения
        level_key = f"level_{i}"
        level = levels.get(level_key, 'INFO')
        print(f"[{level}] Сообщение {i}: {message}")

# Вызов функции с различными аргументами
log_messages(
    "Система запущена",
    "Произошла ошибка",
    "Пользователь вошёл",
    level_1="DEBUG",
    level_2="ERROR"
)

[DEBUG] Сообщение 1: Система запущена
[ERROR] Сообщение 2: Произошла ошибка
[INFO] Сообщение 3: Пользователь вошёл

### Анонимные (lambda) функции

Анонимные функции — это функции, которые не имеют имени и обычно создаются на лету для выполнения небольших задач. Такие функции полезны, когда требуется небольшая функция на короткое время, без необходимости её повторного использования.

```
lambda параметры: выражение
```

In [58]:
# Анонимная функция, которая удваивает значение аргумента
double = lambda x: x*2
# Вызов функции
print(double(5))

10

In [ ]:
def double(x):
    return x * 2

*Семантически лямбда-функции просто синтаксический сахар для обычного определения функции.*

In [59]:
# Анонимная функция, которая складывает два числа
add = lambda x, y: x + y
# Вызов функции
result = add(3, 5)
print(result)

8

Отличия от обычных функций
- Анонимные функции не имеют имени (хотя их можно присвоить переменной).
- Лямбда-функция может иметь любое количество аргументов, но вычисляет и возвращает только одно значение.
- Определение лямбды не включает оператор return, а вовзращен будет результат указанного выражения. 
- Лямбда-функции ограничены одним выражением и не могут содержать множественных операторов или инструкций.
- Чаще всего используются там, где необходима небольшая функция для передачи в другую функцию.
- Лямбда-функции ограничены одним выражением и не могут содержать множественные операторы или инструкции, такие как полноценные конструкции if-else (можно тернарный оператор), циклы, try-except и т.д.

In [60]:
calculate_discount = lambda price, discount: price - (price * discount / 100) if discount > 0 else price

In [61]:
calculate_discount(100, 10)

90.0

In [63]:
# использование лямбда функции для сортировки
students = [
   {"name": "Анна", "age": 19, "grade": 88},
   {"name": "Борис", "age": 21, "grade": 92},
   {"name": "Виктор", "age": 21, "grade": 85},
   {"name": "Галина", "age": 19, "grade": 90},
   {"name": "Дмитрий", "age": 23, "grade": 75}
]

# Сортировка по возрасту (от младшего к старшему)
sorted_by_age = sorted(students, key=lambda student: student['age'])
sorted_by_age

[{'name': 'Анна', 'age': 19, 'grade': 88},
 {'name': 'Галина', 'age': 19, 'grade': 90},
 {'name': 'Борис', 'age': 21, 'grade': 92},
 {'name': 'Виктор', 'age': 21, 'grade': 85},
 {'name': 'Дмитрий', 'age': 23, 'grade': 75}]

In [62]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

In [64]:
# Сортировка по оценке (от высокого к низкому)
sorted_by_grade_desc = sorted(students, key=lambda student: student['grade'], reverse=True)
sorted_by_grade_desc

[{'name': 'Борис', 'age': 21, 'grade': 92},
 {'name': 'Галина', 'age': 19, 'grade': 90},
 {'name': 'Анна', 'age': 19, 'grade': 88},
 {'name': 'Виктор', 'age': 21, 'grade': 85},
 {'name': 'Дмитрий', 'age': 23, 'grade': 75}]

In [65]:
# Сортировка по возрасту, затем по оценке
sorted_by_age_then_grade = sorted(students, key=lambda student: (student['age'], student['grade']))
sorted_by_age_then_grade

[{'name': 'Анна', 'age': 19, 'grade': 88},
 {'name': 'Галина', 'age': 19, 'grade': 90},
 {'name': 'Виктор', 'age': 21, 'grade': 85},
 {'name': 'Борис', 'age': 21, 'grade': 92},
 {'name': 'Дмитрий', 'age': 23, 'grade': 75}]

In [66]:
# Использование в DataFrame

import pandas as pd

df = pd.DataFrame({
    'имя': ['Иван', 'Анна', 'Сергей'],
    'возраст': [15, 12, 17]
})
df

      имя  возраст
0    Иван       15
1    Анна       12
2  Сергей       17

In [67]:
df['возраст'].apply(lambda x: x * 12)

0    180
1    144
2    204
Name: возраст, dtype: int64

In [68]:
df['возраст_в_месяцах'] = df['возраст'].apply(lambda x: x * 12)
# Добавит новый столбец с возрастом в месяцах

In [69]:
df

      имя  возраст  возраст_в_месяцах
0    Иван       15                180
1    Анна       12                144
2  Сергей       17                204

### Область видимости

Область видимости (scope) определяет доступность переменных, функций и других объектов в разных частях программы. Он определяет, где и какие имена (идентификаторы) могут быть использованы.

Поскольку имена не объявляются заранее, интерпретатор Python по местоположению операции присваивания связывает имя с конкретным пространством имен. **Место, где выполняется присваивание, определяет пространство имен, в котором будет находиться имя, а следовательно, и область его видимости.**

Правило LEGB описывает последовательность, в которой Python ищет имена переменных

* L - Local (локальная область видимости): Это область видимости переменных внутри функции или блока кода. Переменные, определенные внутри функции или блока кода, имеют локальную область видимости и доступны только внутри этой функции или блока.
* E - Enclosing (внешняя область видимости): Если функция определена внутри другой функции, то внутренняя функция имеет доступ к переменным внешней функции.
* G - Global (глобальная область видимости): Это область видимости переменных, определенных на верхнем уровне модуля. Переменные, функции и другие объекты, определенные на этом уровне, могут быть доступны из любой части программы.
* B - Built-in (встроенная область видимости): Это область видимости встроенных имен, которые являются частью стандартной библиотеки Python. Эти имена доступны в любой части программы без необходимости импортирования.

<img src="scope.png" style="width: 400px;"/>

In [70]:
min = min(7, 8)
min

7

In [71]:
min(7, 8)

TypeError: 'int' object is not callable

In [72]:
# Global scope
x = 0

def outer():
    # enclosed scope
    x = 1 # local scope функции outer
    def inner(): # local scope функции outer
        # local scope
        x = 2
        print(f'inner func x = {x}')
    inner() # print(2)
    print(f'outers func x = {x}') # print(1)

In [73]:
outer()
print(x)

inner func x = 2
outers func x = 1
0

В Python существуют три типа переменных, связанных с областями видимости: глобальные (global), локальные (local) и нелокальные (nonlocal) переменные.

1) Глобальные переменные (global variables): Это переменные, определенные в глобальной области видимости, т.е. вне всех функций или блоков кода. Глобальные переменные могут быть доступны из любой части программы.

In [74]:
x = 10  # глобальная переменная

def my_function():
    print(x)  # доступ к глобальной переменной
    
print(x)
my_function()

10
10

In [75]:
x = 10

def my_function():
    x = 20
    print(x)  # доступ к локальной переменной
    
print(x)
my_function()
print(x)

10
20
10

In [76]:
x = 10 

def my_function():
    global x 
    x = 20
    print(x)
    
print(x)
my_function()
print(x)

10
20
20

2) Локальные переменные (local variables): Это переменные, определенные внутри функций или блоков кода. Локальные переменные имеют область видимости, ограниченную функцией или блоком, в котором они определены. Они не доступны вне этой функции или блока.

In [77]:
def my_function():
    m = 20  # локальная переменная
    print(m)

my_function()  

print(m)  # Ошибка: переменная m не определена (в глобальной области видимости её нет)

20

NameError: name 'm' is not defined

3) Нелокальные переменные (nonlocal variables): Это переменные, определенные внутри вложенных функций. Они используются, когда внутренняя функция хочет изменить значение переменной, определенной во внешней функции.

In [78]:
def outer_function():
    x = 10

    def inner_function():
        x = 20
        print(x)

    inner_function()
    print(x)

outer_function()

20
10

In [79]:
def outer_function():
    x = 10  # внешняя переменная

    def inner_function():
        nonlocal x  # объявление переменной как нелокальной
        x = 20  # изменение значения внешней переменной
        print(x)

    print(x)
    inner_function()
    print(x)

outer_function()

10
20
20

In [84]:
x = 5
def outer_function():
    # x = 10

    def inner_function():
        x = 20
        def inner2_function():
            print('inner2', x)
        inner2_function()
        print('inner', x)

    inner_function()
    print('outer', x)

outer_function()

inner2 20
inner 20
outer 5

In [88]:
x = 5
def my_func():
    print(x)
    x = 10
my_func()

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

### Функции высшего порядка

В Python функции являются объектами первого класса — их можно передавать в качестве аргументов другим функциям, возвращать как значения из других функций и хранить в переменных или структурах данных как любой другой объект. 

Функции высшего порядка — это функции, которые принимают другие функции в качестве аргументов или возвращают функции как результат.

***
Встроенные функции высшего порядка — ``` map, filter ```

In [90]:
# map принимает функцию и итерируемый объект (например, список) и применяет данную функцию ко всем элементам итерируемого объекта.
def square(x):
    return x * x
 
numbers = [1, 2, 3, 4, 5]
squares = map(square, numbers)
 
print(list(squares))

[1, 4, 9, 16, 25]

In [91]:
list(map(lambda x: x*x, numbers))

[1, 4, 9, 16, 25]

In [92]:
# filter принимает функцию-предикат и итерируемый объект, проходит по каждому элементу итерируемого объекта и возвращает новый итератор, 
# состоящий только из тех элементов, для которых функция-предикат вернула True.
	
def is_even(x):
    return x % 2 == 0
 
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(is_even, numbers))
 
print(even_numbers)  # [2, 4, 6]

[2, 4, 6]

In [93]:
list(filter(lambda x: x % 2 == 0, numbers))

[2, 4, 6]

In [94]:
# ! Использование list comprehensions является более предпочтительным по сравнению с функциями map и filter

# 1. Читаемость кода
# list comprehensions это больше в стиле Python
# Их синтаксис списков более нагляден и интуитивно понятен

# list comprehension
squared = [x ** 2 for x in range(10)]

# map() с лямбдой
squared = list(map(lambda x: x ** 2, range(10)))

# Генератор списка с условием
evens_squared = [x ** 2 for x in range(20) if x % 2 == 0]

# map() и filter() потребуют два вызова
evens_squared = list(map(lambda x: x ** 2, filter(lambda x: x % 2 == 0, range(20))))

In [95]:
# 2. Философия Python ("Zen of Python")
# В "Дзен Python" (PEP 20) есть принципы, такие как "Явное лучше, чем неявное" и "Простое лучше, чем сложное". 

# Явный и простой код
evens = [x for x in range(20) if x % 2 == 0]

# Скрытая логика в filter()
evens = list(filter(lambda x: x % 2 == 0, range(20)))

In [102]:
# 3. Производительность

# Генератор списка выполняется напрямую
%time
squared = [x ** 2 for x in range(10000000)]

CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 5.96 μs

In [103]:
# map() сначала создаёт итератор, затем преобразует его в список
%time
squared = list(map(lambda x: x ** 2, range(10000000)))

CPU times: user 5 μs, sys: 1e+03 ns, total: 6 μs
Wall time: 8.82 μs

### Декораторы

Декораторы позволяют изменять поведение функции или класса, обертывая их вокруг других функций. Они представляют собой функции, которые принимают функцию в качестве аргумента и возвращают другую функцию. Декораторы широко используются для добавления функциональности к существующим функциям без изменения их исходного кода.

In [ ]:
def decorator_function(original_function):
    def wrapper_function():
        print("Дополнительный код, выполняемый перед вызовом функции")
        original_function()
        print("Дополнительный код, выполняемый после вызова функции")
    return wrapper_function

@decorator_function
def my_function():
    print("Оригинальная функция")

# my_function = decorator_function(my_function)
my_function()

In [ ]:
my_function()

In [ ]:
decorator_function(my_function)()

In [ ]:
@decorator_function
def my_function2():
    print('Ещё одна функция')
    print("Оригинальная функция2")
my_function2()

In [ ]:
# декоратор, выводящий время работы функции
from time import time, sleep

def my_timer(func):
    # func - оригинальная функция
    def wrapper_function():
        start_time = time()
        func()
        print(f"Время работы функции - {time() - start_time} с.")
    return wrapper_function

@my_timer
def my_func():
    sleep(3)

my_func()

In [ ]:
# декоратор retry, который повторяет вызов функции в случае ошибки.
def retry(func):
    def wrapper_function(*args, **kwargs):
        for attempt in range(3):
            try:
                return func(*args, **kwargs)
            except Exception as e:
                print(f"Попытка {attempt + 1} не удалась: {e}")
                sleep(1)  # Подождем секунду перед повторной попыткой
        print("Все попытки исчерпаны")
    return wrapper_function

In [ ]:
import random
# Пример использования
@retry
def unstable_function():
    print("Ждём сигнал")
    # Симулируем ошибку
    x = random.randint(0, 10)
    if x > 3:
        raise ValueError(f"Ошибка, значение равно {x}")
    return f"Задача выполнена успешно. Преобразованный сигнал {10/x}"

# Вызов
unstable_function()

In [ ]:
for _ in range(10):
    print(f"Тест {_+1}")
    x = unstable_function()
    if x:
        print(x)
    print("-----------")

In [ ]:
# добавим параметры, чтобы можно было указать количество попыток и время ожидания между ними
def retry(max_attempts=3, delay=1):
    def decorator(func):
        def wrapper_function(*args, **kwargs):
            for attempt in range(max_attempts):
                try:
                    return func(*args, **kwargs)
                except Exception as e:
                    print(f"Попытка {attempt + 1} не удалась: {e}")
                    sleep(delay)
            print(f"Все {max_attempts} попытки исчерпаны")
        return wrapper_function
    return decorator

In [ ]:
# Пример использования
@retry(max_attempts=5, delay=2)
def unstable_function():
    print("Ждём сигнал")
    # Симулируем ошибку
    x = random.randint(0, 10)
    if x > 3:
        raise ValueError(f"Ошибка, значение равно {x}")
    return f"Задача выполнена успешно. Преобразованный сигнал {10/x}"

# Вызов
for _ in range(10):
    print(f"Тест {_+1}")
    x = unstable_function()
    if x:
        print(x)
    print("-----------")

### Рекурсия

<img src="rec.png" style="width: 800px;"/>

Рекурсия - не цикл!

Рекурсия:
- Рекурсия - это процесс, когда функция вызывает саму себя.
- В рекурсии присутствует базовый случай, который определяет условие остановки рекурсии. Без базового случая рекурсия может привести к бесконечному циклу.
- Рекурсивная функция разбивает сложную задачу на более простые подзадачи, которые решаются путем вызова той же функции с другими аргументами.
- Рекурсивные функции использует стек вызовов для хранения промежуточных результатов и возврата к предыдущим вызовам функции после выполнения вложенных вызовов.

Циклы:
- Циклы - это конструкции, которые выполняют определенный блок кода несколько раз, пока выполняется определенное условие.
- Циклы могут быть представлены различными конструкциями, такими как `for`, `while` и т. д., в зависимости от языка программирования.
- Циклы выполняются последовательно и повторяют определенный блок кода до выполнения условия завершения цикла.
- Циклы обычно используются для обработки итерируемых структур данных, таких как списки, массивы и строки.
- Циклы могут быть более подходящими для задач, где требуется последовательная обработка данных или выполнение определенного числа итераций.

Оба подхода имеют свои преимущества и недостатки. В некоторых случаях рекурсия может быть более элегантным и понятным решением, тогда как в других случаях циклы могут быть более простым и эффективным способом выполнения задачи.

Рекурсия работает следующим образом:

1. Функция вызывает саму себя внутри своего тела.
2. При вызове функции создается новый экземпляр функции со своими собственными локальными переменными.
3. Каждый экземпляр функции выполняет свою работу, основанную на переданных аргументах.
4. Каждый экземпляр функции также может вызывать другие экземпляры функции или себя же с новыми значениями аргументов.
5. Процесс вызова функций продолжается до достижения базового случая, который определяет условие остановки рекурсии.
6. Когда базовый случай достигнут, выполнение возвращается обратно по стеку вызовов, и результаты вычислений объединяются.
7. Результат рекурсивной функции возвращается из исходного вызова функции.

In [104]:
def sum_list(*lst):
    if not lst: 
        return 0
    else:
        return lst[0] + sum_list(*lst[1:])

result = sum_list(1, 2, 33, 4, 5)
print(result)

45

<img src="calls.jpg" style="width: 600px;"/>

<img src="returns.jpg" style="width: 600px;"/>

Когда полезна рекурсия:

1. Решение сложных задач. Рекурсивный подход позволяет разбить сложную задачу на более простые подзадачи, что может сделать решение более понятным и легко управляемым. Каждый уровень рекурсии может решать свою часть задачи, а затем комбинировать результаты для получения окончательного результата.

2. Удобство решения некоторых задач. Некоторые задачи имеют естественную структуру, которая может быть легко выражена с использованием рекурсии. Например, обход дерева или графа, работа с вложенными списками.

3. Меньший объем кода. Рекурсивные решения могут быть более компактными и лаконичными, чем итеративные решения. Вместо использования циклов и временных переменных, рекурсивные функции могут вызывать себя с более простыми аргументами.

Однако, необходимо быть осторожным при использовании рекурсии, так как она может привести к бесконечному циклу и переполнению стека вызовов при неправильной реализации. Важно правильно определить базовый случай и условия остановки рекурсии, чтобы избежать проблем.

In [105]:
import sys
sys.getrecursionlimit()

3000

In [106]:
sys.setrecursionlimit(3500)
sys.getrecursionlimit()

3500

In [108]:
# Проверка наличия элемента во вложенных списках
def nested_list_contains(nested_list, target):
    for item in nested_list:
        print(item)
        if item == target:
            return True
        elif isinstance(item, list):
            if nested_list_contains(item, target):
                return True
    return False

my_list = [1, 2, [3, 4, [5, 6]], 7, [8, 9]]
result = nested_list_contains(my_list, 18)
print(result)

1
2
[3, 4, [5, 6]]
3
4
[5, 6]
5
6
7
[8, 9]
8
9
False

In [109]:
# Написать функцию, которая считает количество элементов в списке с учетом вложенных списков.
def count_elements(my_list):
    cnt = 0
    for item in my_list:
        print(item)
        if isinstance(item, list):
            cnt += count_elements(item)
        else:
            cnt += 1
    print('cnt=', cnt)
    return cnt

In [110]:
my_list = [1, 2, [3, 4, [5, 6]], 7, [8, [9, 10]]]
result = count_elements(my_list)
print(result)

1
2
[3, 4, [5, 6]]
3
4
[5, 6]
5
6
cnt= 2
cnt= 4
7
[8, [9, 10]]
8
[9, 10]
9
10
cnt= 2
cnt= 3
cnt= 10
10