# 🐼 Неделя 8. Общий семинар.

**Сегодня в программе:**
1. Принципы работы с табличными данными.  
2. Основные структуры и типы данных в Pandas.  
3. Основные атрибуты и методы.  
4. Индексация, срезы, фильтрация.  
5. Изменение структуры и создание новых столбцов.  

Использовать будем Python и библиотеку **Pandas**.  

[*Ссылка на документацию Pandas*](https://pandas.pydata.org/).

In [ ]:
# сделайте, если раньше не пользовались библиотекой
# ! pip install pandas

In [ ]:
import pandas as pd

## 🟢 1. Принципы работы с табличными данными.
См. слайды в презентации к занятию.

## 🟢 2. Основные структуры и типы данных в Pandas.

Преджде познакомимся с таблицей, с которой будем работать - это известный **датасет "Титаник"**, с него всегда начинается изучение анализа данных:)

Подробнее про него почитать можно, например, [тут](https://neurohive.io/ru/osnovy-data-science/razbor-resheniya-zadachi-titanik-na-kaggle-dlya-nachinajushhih/).

In [ ]:
# считываем данные в формате csv по ссылке и кладём в переменную data,
# параметр sep отвечает за разделитель
data = pd.read_csv('train.csv', sep = ',')
print(type(data)) # посмотрим название питоновского типа

<class 'pandas.core.frame.DataFrame'>

Кто хорошо знает Excel, SQL, SAS, R или Stata, возможно, будет полезно заглянуть [сюда](http://pandas.geekwriter.ru/getting_started/comparison/index.html).

### 2.1. Series - одномерная структура

`Series` — это **одномерный массив с метками (индексом)**.
Его можно воспринимать как "улучшенный словарь" или "одномерную таблицу", где каждой строке соответствует метка.

In [ ]:
# отдельные колонки - это Series
ages = data['Age']

print(type(ages))
print(ages.head())

<class 'pandas.core.series.Series'>
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [ ]:
# получение одного элемента по индексу
ages[0]

22.0

In [ ]:
# проверка типов данных и их размер
ages.dtype, ages.shape

(dtype('float64'), (891,))

In [ ]:
# векторные операции сравнения
ages.mean()        # средний возраст
(ages > 60).sum()  # сколько пожилых пассажиров

22

In [ ]:
# Series можно воспринимать как словарь
first_five = data['Name'].head()
first_five.to_dict()

{0: 'Braund, Mr. Owen Harris',
 1: 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 2: 'Heikkinen, Miss. Laina',
 3: 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 4: 'Allen, Mr. William Henry'}

### 2.2. DataFrame - двумерная структура

`DataFrame` — это **таблица**, состоящая из строк и столбцов,
где каждый столбец — это `Series` с собственным именем и типом данных.


**Различия между Series и DataFrame:**

| Характеристика | Series          | DataFrame                     |
| -------------- | --------------- | ----------------------------- |
| Размерность    | 1D              | 2D                            |
| Индексы        | Один индекс     | Два уровня (строки и столбцы) |
| Аналог в NumPy | Вектор          | Матрица                       |
| Пример         | Столбец таблицы | Вся таблица                   |

In [ ]:
print(type(data))
data.head()

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Иногда бывает не нужно работать со всеми столбцами. Если Вам нужен какой-то конкретный, можно обратиться к нему **напрямую**; а если нужны несколько -- можно сделать **срез**.

In [ ]:
# выбор одного столбца (Series)
data['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [ ]:
# выбор нескольких столбцов
data[['Sex', 'Age', 'Fare']].head()

      Sex   Age     Fare
0    male  22.0   7.2500
1  female  38.0  71.2833
2  female  26.0   7.9250
3  female  35.0  53.1000
4    male  35.0   8.0500

In [ ]:
# можно выбрать один столбец как датафрейм:)
type(data[['Age']])

pandas.core.frame.DataFrame

## 🟢 3. Основные атрибуты и методы.

In [ ]:
# метод head показывает заданное количество первых строк (head - голова)
# в скобках указываем кол-во выводимых строк
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
# а метод tail показывает последние строки (tail - хвост)
data.tail(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

In [ ]:
# случайный набор строк из данных
data.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.525,C62 C64,C
668,669,0,3,"Cook, Mr. Jacob",male,43.0,0,0,A/5 3536,8.050,NaN,S
553,554,1,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.225,NaN,C

Видим, что в данных есть пропуски (**NaN -- Not a Number**). Их количество можно подсчитать:

In [ ]:
# метод info помогает подсчитать пропуски по столбцам
# + определяет, какого типа каждый из них
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# альтернативный вариант для подсчёта пропусков
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Ещё бывает полезно смотреть на **основные статистики датасета**: минимум, максимум, среднее, квантили...

Таким образом сразу можно обнаружить **выбросы**.

In [ ]:
# для этого поможет метод describe, ДЛЯ ЧИСЕЛ
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# для этого поможет метод describe, ДЛЯ КАТЕГ. ПРИЗНАКОВ
data.describe(include=['object'])

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
# встроенная документация
# help(data.info)

Посмотрим ещё на ряд важных характеристик таблицы -- её **размерность, названия колонок и непосредственно значения**.

Тут мы **не пишем скобочек**, т.к. это уже не **методы**, а **аттрибуты** датафрейма.

In [ ]:
# посмотрим колонки в таблице
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
# и их значения
data.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [ ]:
# по сути - это массив, поэтому можно сделать срез
data.values[:10]

array([[1, 0, 3, 'Braund, Mr. Owen Harris', 'male', 22.0, 1, 0,
        'A/5 21171', 7.25, nan, 'S'],
       [2, 1, 1, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
        'female', 38.0, 1, 0, 'PC 17599', 71.2833, 'C85', 'C'],
       [3, 1, 3, 'Heikkinen, Miss. Laina', 'female', 26.0, 0, 0,
        'STON/O2. 3101282', 7.925, nan, 'S'],
       [4, 1, 1, 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
        'female', 35.0, 1, 0, '113803', 53.1, 'C123', 'S'],
       [5, 0, 3, 'Allen, Mr. William Henry', 'male', 35.0, 0, 0,
        '373450', 8.05, nan, 'S'],
       [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583,
        nan, 'Q'],
       [7, 0, 1, 'McCarthy, Mr. Timothy J', 'male', 54.0, 0, 0, '17463',
        51.8625, 'E46', 'S'],
       [8, 0, 3, 'Palsson, Master. Gosta Leonard', 'male', 2.0, 3, 1,
        '349909', 21.075, nan, 'S'],
       [9, 1, 3, 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
        'female', 27.0, 0, 2, '347742', 11.1333, nan, 'S'],
       [10, 1, 2, 'Nasser, Mrs. Nicholas (Adele Achem)', 'female', 14.0,
        1, 0, '237736', 30.0708, nan, 'C']], dtype=object)

In [ ]:
# а этот метод покажет размерность датасета
data.shape

(891, 12)

Как к отдельным столбцам, так и ко всему датафрейму можно применять **агрегирующие функции**: сумму, минимум, максимум, среднее, медиану...

In [ ]:
print('Число выживших:', data['Survived'].sum())
print('Минимальное кол-во детей/родителей у пассажиров на борту:', data['Parch'].min())
print('Минимальная стоимость билета:', data['Fare'].min())
print('Максимальная стоимость билета:', data['Fare'].max())
print('Средний возраст пассажиров:', data['Age'].mean())
print('Медианный возраст пассажиров:', data['Age'].median())
print('Количество непропущенных возрастов в таблице:', data['Age'].count())

Число выживших: 342
Минимальное кол-во детей/родителей у пассажиров на борту: 0
Минимальная стоимость билета: 0.0
Максимальная стоимость билета: 512.3292
Средний возраст пассажиров: 29.69911764705882
Медианный возраст пассажиров: 28.0
Количество непропущенных возрастов в таблице: 714

Бывает интересно посмотреть на **уникальные категории** в признаках (и их количество):

In [ ]:
print('Количество уникальных классов:', data['Pclass'].nunique())
print('Непосредственно уникальные классы:', data['Pclass'].unique())

Количество уникальных классов: 3
Непосредственно уникальные классы: [3 1 2]

Часто бывает необходимо **отсортировать** таблицу по какому-либо столбцу/столбцам.

В параметрах метода можно уточнить эти столбцы, а также порядок сортировки - по возрастанию или убыванию (*ascening: True/False*):

In [ ]:
# сортировка по ОДНОЙ колонке ВОЗРАСТА в порядке УБЫВАНИЯ
data.sort_values('Age', ascending=False).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q

In [ ]:
# сортировка по ДВУМ колонкам КЛАССА и ВОЗРАСТА
# в порядке УБЫВАНИЯ и ВОЗРАСТАНИЯ соответственно
data.sort_values(['Pclass', 'Age'], ascending=[False, True]).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q

## 🟢 4. Индексация и срезы.

Индексация в Pandas позволяет подступаться к строкам и столбцам** `DataFrame` или `Series`.

**Основные способы:**

* `[]` — простая индексация по имени столбца,
* `.loc[]` — доступ по **меткам** (именам),
* `.iloc[]` — доступ по **позициям** (номерам строк/столбцов).

С **индексацией столбцов** мы уже имели дело:

In [ ]:
# Один столбец возвращает Series
data['Age'].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [ ]:
# Несколько столбцов возвращает DataFrame
data[['Name', 'Age', 'Fare']].head()

                                                Name   Age     Fare
0                            Braund, Mr. Owen Harris  22.0   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                             Heikkinen, Miss. Laina  26.0   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                           Allen, Mr. William Henry  35.0   8.0500

In [ ]:
# Можно обращаться к столбцу по его номеру
data.columns[8]

'Ticket'

**Доступ к строкам:**

In [ ]:
# По индексу (позиции)
data.iloc[0]     # первая строка

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
# По метке индекса (если переопределён, например, Name)
data.loc[0]      # тоже первая строка в текущем индексе

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

**Срезы строк** работают по аналогичному NumPy принципу: `.iloc` использует **позиции** (начало включительно, конец не включительно)

In [ ]:
# Первые 5 строк
data.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Строки с 10 по 14
data.iloc[10:15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

Можно сделать срез одновременно и по строкам, и по столбцам - в этом тоже помогает `iloc`:

In [ ]:
# Возраст и пол первых 5 пассажиров
data.loc[:4, ['Name', 'Sex', 'Age']]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

In [ ]:
# Первые 3 строки и первые 2 столбца
data.iloc[:3, :2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

Также нередко приходится выполнять **фильтрацию**, здесь главное -- правильно записать условие. Принцип почти тот же самый, что и в обычных `if`:

* каждое *атомарное условие* возвращает `True` или `False`;
* условие может быть *комплексным* -- т.е. состоять из нескольких *атомарных условий*, которые соединяются через "и", "или"; здесь важное отличие от `if`: **"и" записывается как `&`, "или"  как `|`**;
* чтобы избежать ошибок и неточностей, лучше обрамлять *атомарные условия* в отдельные скобки.

In [ ]:
# можно отфильтровать по любому условию
data[(data['Pclass'] == 3) | (data['Sex'].isin(data['Name'].values[:10]))].shape

(491, 12)

In [ ]:
# пример полезного применения:
# посчитаем средний тариф для женщин и мужчин
data_male = data[data['Sex'] == 'male']
data_female = data[data['Sex'] == 'female']
print('Средний возраст женщин:', data_female['Age'].mean())
print('Средний возраст мужчин:', data_male['Age'].mean())

Средний возраст женщин: 27.915708812260537
Средний возраст мужчин: 30.72664459161148

## 🟢 5. Изменение структуры и создание новых столбцов.

В предыдущих разделах мы познакомились с методами и атрибутами, которые позволяют просматривать и анализировать данные, не изменяя саму структуру/состав таблицы.

В этом разделе рассмотрим инструменты, которые могут вносить изменения в данные — например, добавлять, удалять или преобразовывать столбцы и строки.

Первым делом, давайте **переименуем** для удобства столбцы?

In [ ]:
# в этом поможет метод rename,
# не забываем сделать пересохранение!
# тут есть inplace=True !
data = data.rename(columns={
    'PassengerId': 'ID',
    'Survived': 'Выживаемость',
    'Pclass': 'Класс',
    'Name': 'Имя',
    'Sex': 'Пол',
    'Age': 'Возраст',
    'SibSp': 'Число_родств_1',
    'Parch': 'Число_родств_2',
    'Ticket': 'Билет',
    'Fare': 'Тариф',
    'Cabin': 'Каюта',
    'Embarked': 'Порт'
})
data.head()

,ID,Выживаемость,Класс,Имя,Пол,Возраст,Число_родств_1,Число_родств_2,Билет,Тариф,Каюта,Порт
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Неинформативные или ненужные столбцы можно **удалять**:

In [ ]:
# в этом поможет метод drop
# главное - указывайте axis=1, чтобы удалить столбец
# (axis=0) отвечает за удаление строк
data = data.drop('ID', axis=1)
# data.drop('ID', axis=1, inplace=True) # если не хотите пересоздавать копию!
data.head()

,Выживаемость,Класс,Имя,Пол,Возраст,Число_родств_1,Число_родств_2,Билет,Тариф,Каюта,Порт
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

А можно и **создавать новые**:

In [ ]:
data['Суммарное_число_родств'] = data['Число_родств_1'] + data['Число_родств_2']

Можно также применять функции, в т.ч. кастомные к столбцу/столбцам:

In [ ]:
# Создаем новую колонку с возрастной группой
data['Возрастная_группа'] = data['Возраст'].apply(lambda x: (x // 10) * 10)
data[['Возраст', 'Возрастная_группа']].head()

   Возраст  Возрастная_группа
0     22.0               20.0
1     38.0               30.0
2     26.0               20.0
3     35.0               30.0
4     35.0               30.0

In [ ]:
# альтернативная и более универсальна форма записи для позапредыдущего примера -
# если хотим создать новый столбец из нескольких других
data['Суммарное_число_родств'] = data.apply(
    lambda row: row['Число_родств_1'] + row['Число_родств_2'],
    axis=1
)

Ещё иногда в данных встречаются **дубликаты**, что может мешать исследованиям:

In [ ]:
# метод drop_duplicates убирает дубликаты из данных
# тут есть inplace=True !
print(data.shape)
data = data.drop_duplicates()
print(data.shape)

(891, 13)
(891, 13)

In [ ]:
# можно убирать дубли по конкретным столбцам
print(data.shape)
tmp = data.drop_duplicates(['Пол', 'Возраст'])
print(tmp.shape)

(891, 13)
(147, 13)

In [ ]:
# заполним пропуски: для возраста - медианой
data['Возраст'].fillna(data['Возраст'].median(), inplace=True)

# для кабины - модой
data['Каюта'].fillna(data['Каюта'].mode()[0], inplace=True)

Пример из предыдущего раздела про расчёт среднего возраста в разрезе пола можно было реализовать проще и лаконичнее, используя **метод группировки** - вот как это бы выглядело:

In [ ]:
data.groupby(['Пол', 'Класс'])[['Возраст', 'Тариф']].mean()

                Возраст       Тариф
Пол    Класс
female 1      33.978723  106.125798
       2      28.703947   21.970121
       3      23.572917   16.118810
male   1      38.995246   67.226127
       2      30.512315   19.741782
       3      26.911873   12.661633

In [ ]:
data.groupby('Пол')['Возраст'].mean()

Пол
female    27.929936
male      30.140676
Name: Возраст, dtype: float64

In [ ]:
# reset_index() сделает отдельный числовой индекс,
# это может быть полезным при объединении таблиц
data.groupby('Пол')['Возраст'].mean().reset_index()

      Пол    Возраст
0  female  27.929936
1    male  30.140676

Ну и наконец последняя на сегодня (но не по важности:)) группа методов сохраняет преобразованный датафрейм в отдельный csv или excel файл:

In [ ]:
# параметр index=False откинет лишний столбец индекса
data.to_csv('titanic_preprocessed.csv', index=False)
data.to_excel('titanic_preprocessed.xlsx', index=False)

/var/folders/8w/sx6j7f5d7td7tzr3k347hzkc0000gn/T/ipykernel_83028/3714763345.py:3: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.1' currently installed).
  data.to_excel('titanic_preprocessed.xlsx', index=False)

# 🌟 До скорых встреч!